/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PassportPermission } from './PassportPermission';
import {
    PassportPermissionFromJSON,
    PassportPermissionFromJSONTyped,
    PassportPermissionToJSON,
} from './PassportPermission';

/**
 * 
 * @export
 * @interface AuthResponseMobil
 */
export interface AuthResponseMobil {
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthResponseMobil
     */
    assignments?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AuthResponseMobil
     */
    locomotoUrl: string;
    /**
     * 
     * @type {string}
     * @memberof AuthResponseMobil
     */
    message?: string;
    /**
     * 
     * @type {Array<PassportPermission>}
     * @memberof AuthResponseMobil
     */
    passportPermissionsDescriptions?: Array<PassportPermission>;
    /**
     * 
     * @type {string}
     * @memberof AuthResponseMobil
     */
    passportPublicKey?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthResponseMobil
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthResponseMobil
     */
    username?: string;
}

/**
 * Check if a given object implements the AuthResponseMobil interface.
 */
export function instanceOfAuthResponseMobil(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "locomotoUrl" in value;

    return isInstance;
}

export function AuthResponseMobilFromJSON(json: any): AuthResponseMobil {
    return AuthResponseMobilFromJSONTyped(json, false);
}

export function AuthResponseMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthResponseMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assignments': !exists(json, 'assignments') ? undefined : json['assignments'],
        'locomotoUrl': json['locomoto_url'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'passportPermissionsDescriptions': !exists(json, 'passport_permissions_descriptions') ? undefined : ((json['passport_permissions_descriptions'] as Array<any>).map(PassportPermissionFromJSON)),
        'passportPublicKey': !exists(json, 'passport_public_key') ? undefined : json['passport_public_key'],
        'token': !exists(json, 'token') ? undefined : json['token'],
        'username': !exists(json, 'username') ? undefined : json['username'],
    };
}

export function AuthResponseMobilToJSON(value?: AuthResponseMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'assignments': value.assignments,
        'locomoto_url': value.locomotoUrl,
        'message': value.message,
        'passport_permissions_descriptions': value.passportPermissionsDescriptions === undefined ? undefined : ((value.passportPermissionsDescriptions as Array<any>).map(PassportPermissionToJSON)),
        'passport_public_key': value.passportPublicKey,
        'token': value.token,
        'username': value.username,
    };
}

