/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Bin
 */
export interface Bin {
    /**
     * 
     * @type {string}
     * @memberof Bin
     */
    max?: string;
    /**
     * 
     * @type {string}
     * @memberof Bin
     */
    min?: string;
    /**
     * 
     * @type {number}
     * @memberof Bin
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof Bin
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Bin
     */
    value: string;
}

/**
 * Check if a given object implements the Bin interface.
 */
export function instanceOfBin(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function BinFromJSON(json: any): Bin {
    return BinFromJSONTyped(json, false);
}

export function BinFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bin {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'max': !exists(json, '_max') ? undefined : json['_max'],
        'min': !exists(json, '_min') ? undefined : json['_min'],
        'count': json['count'],
        'title': json['title'],
        'value': json['value'],
    };
}

export function BinToJSON(value?: Bin | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_max': value.max,
        '_min': value.min,
        'count': value.count,
        'title': value.title,
        'value': value.value,
    };
}

