/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ItemId } from './ItemId';
import {
    ItemIdFromJSON,
    ItemIdFromJSONTyped,
    ItemIdToJSON,
} from './ItemId';

/**
 * 
 * @export
 * @interface ChangeItemZoneRequest
 */
export interface ChangeItemZoneRequest {
    /**
     * 
     * @type {ItemId}
     * @memberof ChangeItemZoneRequest
     */
    itemId: ItemId;
    /**
     * 
     * @type {number}
     * @memberof ChangeItemZoneRequest
     */
    quantity: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ChangeItemZoneRequest
     */
    serials?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ChangeItemZoneRequest
     */
    sourceZone: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeItemZoneRequest
     */
    targetZone: string;
}

/**
 * Check if a given object implements the ChangeItemZoneRequest interface.
 */
export function instanceOfChangeItemZoneRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "itemId" in value;
    isInstance = isInstance && "quantity" in value;
    isInstance = isInstance && "sourceZone" in value;
    isInstance = isInstance && "targetZone" in value;

    return isInstance;
}

export function ChangeItemZoneRequestFromJSON(json: any): ChangeItemZoneRequest {
    return ChangeItemZoneRequestFromJSONTyped(json, false);
}

export function ChangeItemZoneRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeItemZoneRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'itemId': ItemIdFromJSON(json['item_id']),
        'quantity': json['quantity'],
        'serials': !exists(json, 'serials') ? undefined : json['serials'],
        'sourceZone': json['source_zone'],
        'targetZone': json['target_zone'],
    };
}

export function ChangeItemZoneRequestToJSON(value?: ChangeItemZoneRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item_id': ItemIdToJSON(value.itemId),
        'quantity': value.quantity,
        'serials': value.serials,
        'source_zone': value.sourceZone,
        'target_zone': value.targetZone,
    };
}

