/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckinInformation
 */
export interface CheckinInformation {
    /**
     * 
     * @type {string}
     * @memberof CheckinInformation
     */
    label: string;
    /**
     * 
     * @type {number}
     * @memberof CheckinInformation
     */
    poId: number;
}

/**
 * Check if a given object implements the CheckinInformation interface.
 */
export function instanceOfCheckinInformation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "label" in value;
    isInstance = isInstance && "poId" in value;

    return isInstance;
}

export function CheckinInformationFromJSON(json: any): CheckinInformation {
    return CheckinInformationFromJSONTyped(json, false);
}

export function CheckinInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckinInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': json['label'],
        'poId': json['po_id'],
    };
}

export function CheckinInformationToJSON(value?: CheckinInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
        'po_id': value.poId,
    };
}

