/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CartItem } from './CartItem';
import {
    CartItemFromJSON,
    CartItemFromJSONTyped,
    CartItemToJSON,
} from './CartItem';
import type { SalesOrderDeliveryTime } from './SalesOrderDeliveryTime';
import {
    SalesOrderDeliveryTimeFromJSON,
    SalesOrderDeliveryTimeFromJSONTyped,
    SalesOrderDeliveryTimeToJSON,
} from './SalesOrderDeliveryTime';

/**
 * 
 * @export
 * @interface CreateSalesOrderRequest
 */
export interface CreateSalesOrderRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateSalesOrderRequest
     */
    addressId: number;
    /**
     * 
     * @type {string}
     * @memberof CreateSalesOrderRequest
     */
    couponCode?: string;
    /**
     * 
     * @type {SalesOrderDeliveryTime}
     * @memberof CreateSalesOrderRequest
     */
    etd?: SalesOrderDeliveryTime;
    /**
     * 
     * @type {Array<CartItem>}
     * @memberof CreateSalesOrderRequest
     */
    items: Array<CartItem>;
    /**
     * 
     * @type {string}
     * @memberof CreateSalesOrderRequest
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSalesOrderRequest
     */
    shippingService?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateSalesOrderRequest
     */
    useBalance?: boolean;
}

/**
 * Check if a given object implements the CreateSalesOrderRequest interface.
 */
export function instanceOfCreateSalesOrderRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "addressId" in value;
    isInstance = isInstance && "items" in value;

    return isInstance;
}

export function CreateSalesOrderRequestFromJSON(json: any): CreateSalesOrderRequest {
    return CreateSalesOrderRequestFromJSONTyped(json, false);
}

export function CreateSalesOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSalesOrderRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addressId': json['address_id'],
        'couponCode': !exists(json, 'coupon_code') ? undefined : json['coupon_code'],
        'etd': !exists(json, 'etd') ? undefined : SalesOrderDeliveryTimeFromJSON(json['etd']),
        'items': ((json['items'] as Array<any>).map(CartItemFromJSON)),
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'shippingService': !exists(json, 'shipping_service') ? undefined : json['shipping_service'],
        'useBalance': !exists(json, 'use_balance') ? undefined : json['use_balance'],
    };
}

export function CreateSalesOrderRequestToJSON(value?: CreateSalesOrderRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address_id': value.addressId,
        'coupon_code': value.couponCode,
        'etd': SalesOrderDeliveryTimeToJSON(value.etd),
        'items': ((value.items as Array<any>).map(CartItemToJSON)),
        'notes': value.notes,
        'shipping_service': value.shippingService,
        'use_balance': value.useBalance,
    };
}

