/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CryptoEarningsReportResponseReportEntryGraphData } from './CryptoEarningsReportResponseReportEntryGraphData';
import {
    CryptoEarningsReportResponseReportEntryGraphDataFromJSON,
    CryptoEarningsReportResponseReportEntryGraphDataFromJSONTyped,
    CryptoEarningsReportResponseReportEntryGraphDataToJSON,
} from './CryptoEarningsReportResponseReportEntryGraphData';

/**
 * 
 * @export
 * @interface CryptoEarningsReportResponseReportEntry
 */
export interface CryptoEarningsReportResponseReportEntry {
    /**
     * 
     * @type {CryptoEarningsReportResponseReportEntryGraphData}
     * @memberof CryptoEarningsReportResponseReportEntry
     */
    graphData: CryptoEarningsReportResponseReportEntryGraphData;
    /**
     * 
     * @type {string}
     * @memberof CryptoEarningsReportResponseReportEntry
     */
    lastRenueve: string;
    /**
     * 
     * @type {string}
     * @memberof CryptoEarningsReportResponseReportEntry
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CryptoEarningsReportResponseReportEntry
     */
    readable: string;
    /**
     * 
     * @type {string}
     * @memberof CryptoEarningsReportResponseReportEntry
     */
    renueve: string;
    /**
     * 
     * @type {string}
     * @memberof CryptoEarningsReportResponseReportEntry
     */
    timeFrame: CryptoEarningsReportResponseReportEntryTimeFrameEnum;
}


/**
 * @export
 */
export const CryptoEarningsReportResponseReportEntryTimeFrameEnum = {
    Monthly: 'monthly',
    Annual: 'annual'
} as const;
export type CryptoEarningsReportResponseReportEntryTimeFrameEnum = typeof CryptoEarningsReportResponseReportEntryTimeFrameEnum[keyof typeof CryptoEarningsReportResponseReportEntryTimeFrameEnum];


/**
 * Check if a given object implements the CryptoEarningsReportResponseReportEntry interface.
 */
export function instanceOfCryptoEarningsReportResponseReportEntry(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "graphData" in value;
    isInstance = isInstance && "lastRenueve" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "readable" in value;
    isInstance = isInstance && "renueve" in value;
    isInstance = isInstance && "timeFrame" in value;

    return isInstance;
}

export function CryptoEarningsReportResponseReportEntryFromJSON(json: any): CryptoEarningsReportResponseReportEntry {
    return CryptoEarningsReportResponseReportEntryFromJSONTyped(json, false);
}

export function CryptoEarningsReportResponseReportEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoEarningsReportResponseReportEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'graphData': CryptoEarningsReportResponseReportEntryGraphDataFromJSON(json['graph_data']),
        'lastRenueve': json['last_renueve'],
        'name': json['name'],
        'readable': json['readable'],
        'renueve': json['renueve'],
        'timeFrame': json['time_frame'],
    };
}

export function CryptoEarningsReportResponseReportEntryToJSON(value?: CryptoEarningsReportResponseReportEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'graph_data': CryptoEarningsReportResponseReportEntryGraphDataToJSON(value.graphData),
        'last_renueve': value.lastRenueve,
        'name': value.name,
        'readable': value.readable,
        'renueve': value.renueve,
        'time_frame': value.timeFrame,
    };
}

