/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CryptoEarningsReportResponseReportEntry } from './CryptoEarningsReportResponseReportEntry';
import {
    CryptoEarningsReportResponseReportEntryFromJSON,
    CryptoEarningsReportResponseReportEntryFromJSONTyped,
    CryptoEarningsReportResponseReportEntryToJSON,
} from './CryptoEarningsReportResponseReportEntry';

/**
 * 
 * @export
 * @interface CryptoEarningsReportResponse
 */
export interface CryptoEarningsReportResponse {
    /**
     * 
     * @type {string}
     * @memberof CryptoEarningsReportResponse
     */
    amountInvested: string;
    /**
     * 
     * @type {string}
     * @memberof CryptoEarningsReportResponse
     */
    estimatedProfitPercentage: string;
    /**
     * 
     * @type {Array<CryptoEarningsReportResponseReportEntry>}
     * @memberof CryptoEarningsReportResponse
     */
    report?: Array<CryptoEarningsReportResponseReportEntry>;
}

/**
 * Check if a given object implements the CryptoEarningsReportResponse interface.
 */
export function instanceOfCryptoEarningsReportResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amountInvested" in value;
    isInstance = isInstance && "estimatedProfitPercentage" in value;

    return isInstance;
}

export function CryptoEarningsReportResponseFromJSON(json: any): CryptoEarningsReportResponse {
    return CryptoEarningsReportResponseFromJSONTyped(json, false);
}

export function CryptoEarningsReportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoEarningsReportResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amountInvested': json['amount_invested'],
        'estimatedProfitPercentage': json['estimated_profit_percentage'],
        'report': !exists(json, 'report') ? undefined : ((json['report'] as Array<any>).map(CryptoEarningsReportResponseReportEntryFromJSON)),
    };
}

export function CryptoEarningsReportResponseToJSON(value?: CryptoEarningsReportResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount_invested': value.amountInvested,
        'estimated_profit_percentage': value.estimatedProfitPercentage,
        'report': value.report === undefined ? undefined : ((value.report as Array<any>).map(CryptoEarningsReportResponseReportEntryToJSON)),
    };
}

