/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CryptoProfileSnapshot
 */
export interface CryptoProfileSnapshot {
    /**
     * 
     * @type {string}
     * @memberof CryptoProfileSnapshot
     */
    imageType: CryptoProfileSnapshotImageTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CryptoProfileSnapshot
     */
    processingStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof CryptoProfileSnapshot
     */
    uri: string;
}


/**
 * @export
 */
export const CryptoProfileSnapshotImageTypeEnum = {
    DniFrente: 'dni_frente',
    DniDorso: 'dni_dorso',
    Selfie: 'selfie'
} as const;
export type CryptoProfileSnapshotImageTypeEnum = typeof CryptoProfileSnapshotImageTypeEnum[keyof typeof CryptoProfileSnapshotImageTypeEnum];


/**
 * Check if a given object implements the CryptoProfileSnapshot interface.
 */
export function instanceOfCryptoProfileSnapshot(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "imageType" in value;
    isInstance = isInstance && "uri" in value;

    return isInstance;
}

export function CryptoProfileSnapshotFromJSON(json: any): CryptoProfileSnapshot {
    return CryptoProfileSnapshotFromJSONTyped(json, false);
}

export function CryptoProfileSnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): CryptoProfileSnapshot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'imageType': json['image_type'],
        'processingStatus': !exists(json, 'processing_status') ? undefined : json['processing_status'],
        'uri': json['uri'],
    };
}

export function CryptoProfileSnapshotToJSON(value?: CryptoProfileSnapshot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image_type': value.imageType,
        'processing_status': value.processingStatus,
        'uri': value.uri,
    };
}

