/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeliveryTimeResponseDeliveryTime
 */
export interface DeliveryTimeResponseDeliveryTime {
    /**
     * 
     * @type {number}
     * @memberof DeliveryTimeResponseDeliveryTime
     */
    fromTime: number;
    /**
     * 
     * @type {string}
     * @memberof DeliveryTimeResponseDeliveryTime
     */
    key: string;
    /**
     * 
     * @type {number}
     * @memberof DeliveryTimeResponseDeliveryTime
     */
    toTime: number;
}

/**
 * Check if a given object implements the DeliveryTimeResponseDeliveryTime interface.
 */
export function instanceOfDeliveryTimeResponseDeliveryTime(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fromTime" in value;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "toTime" in value;

    return isInstance;
}

export function DeliveryTimeResponseDeliveryTimeFromJSON(json: any): DeliveryTimeResponseDeliveryTime {
    return DeliveryTimeResponseDeliveryTimeFromJSONTyped(json, false);
}

export function DeliveryTimeResponseDeliveryTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryTimeResponseDeliveryTime {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fromTime': json['from_time'],
        'key': json['key'],
        'toTime': json['to_time'],
    };
}

export function DeliveryTimeResponseDeliveryTimeToJSON(value?: DeliveryTimeResponseDeliveryTime | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from_time': value.fromTime,
        'key': value.key,
        'to_time': value.toTime,
    };
}

