/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeliveryOptionDeliveryTime
 */
export interface DeliveryOptionDeliveryTime {
    /**
     * 
     * @type {number}
     * @memberof DeliveryOptionDeliveryTime
     */
    fromTime: number;
    /**
     * 
     * @type {string}
     * @memberof DeliveryOptionDeliveryTime
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryOptionDeliveryTime
     */
    serviceDescription?: string;
    /**
     * 
     * @type {number}
     * @memberof DeliveryOptionDeliveryTime
     */
    toTime: number;
}

/**
 * Check if a given object implements the DeliveryOptionDeliveryTime interface.
 */
export function instanceOfDeliveryOptionDeliveryTime(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fromTime" in value;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "toTime" in value;

    return isInstance;
}

export function DeliveryOptionDeliveryTimeFromJSON(json: any): DeliveryOptionDeliveryTime {
    return DeliveryOptionDeliveryTimeFromJSONTyped(json, false);
}

export function DeliveryOptionDeliveryTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryOptionDeliveryTime {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fromTime': json['from_time'],
        'key': json['key'],
        'serviceDescription': !exists(json, 'service_description') ? undefined : json['service_description'],
        'toTime': json['to_time'],
    };
}

export function DeliveryOptionDeliveryTimeToJSON(value?: DeliveryOptionDeliveryTime | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from_time': value.fromTime,
        'key': value.key,
        'service_description': value.serviceDescription,
        'to_time': value.toTime,
    };
}

