/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeliveryTimeRequest
 */
export interface DeliveryTimeRequest {
    /**
     * 
     * @type {number}
     * @memberof DeliveryTimeRequest
     */
    addressId?: number;
}

/**
 * Check if a given object implements the DeliveryTimeRequest interface.
 */
export function instanceOfDeliveryTimeRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeliveryTimeRequestFromJSON(json: any): DeliveryTimeRequest {
    return DeliveryTimeRequestFromJSONTyped(json, false);
}

export function DeliveryTimeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryTimeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addressId': !exists(json, 'address_id') ? undefined : json['address_id'],
    };
}

export function DeliveryTimeRequestToJSON(value?: DeliveryTimeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address_id': value.addressId,
    };
}

