/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './Money';

/**
 * 
 * @export
 * @interface DeliveryPricesDeliveryPrice
 */
export interface DeliveryPricesDeliveryPrice {
    /**
     * 
     * @type {Money}
     * @memberof DeliveryPricesDeliveryPrice
     */
    below: Money;
    /**
     * 
     * @type {Money}
     * @memberof DeliveryPricesDeliveryPrice
     */
    over: Money;
}

/**
 * Check if a given object implements the DeliveryPricesDeliveryPrice interface.
 */
export function instanceOfDeliveryPricesDeliveryPrice(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "below" in value;
    isInstance = isInstance && "over" in value;

    return isInstance;
}

export function DeliveryPricesDeliveryPriceFromJSON(json: any): DeliveryPricesDeliveryPrice {
    return DeliveryPricesDeliveryPriceFromJSONTyped(json, false);
}

export function DeliveryPricesDeliveryPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryPricesDeliveryPrice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'below': MoneyFromJSON(json['below']),
        'over': MoneyFromJSON(json['over']),
    };
}

export function DeliveryPricesDeliveryPriceToJSON(value?: DeliveryPricesDeliveryPrice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'below': MoneyToJSON(value.below),
        'over': MoneyToJSON(value.over),
    };
}

