/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Measure } from './Measure';
import {
    MeasureFromJSON,
    MeasureFromJSONTyped,
    MeasureToJSON,
} from './Measure';

/**
 * 
 * @export
 * @interface Dimensions
 */
export interface Dimensions {
    /**
     * 
     * @type {Measure}
     * @memberof Dimensions
     */
    height: Measure;
    /**
     * 
     * @type {Measure}
     * @memberof Dimensions
     */
    length: Measure;
    /**
     * 
     * @type {Measure}
     * @memberof Dimensions
     */
    weight: Measure;
    /**
     * 
     * @type {Measure}
     * @memberof Dimensions
     */
    width: Measure;
}

/**
 * Check if a given object implements the Dimensions interface.
 */
export function instanceOfDimensions(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "height" in value;
    isInstance = isInstance && "length" in value;
    isInstance = isInstance && "weight" in value;
    isInstance = isInstance && "width" in value;

    return isInstance;
}

export function DimensionsFromJSON(json: any): Dimensions {
    return DimensionsFromJSONTyped(json, false);
}

export function DimensionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Dimensions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'height': MeasureFromJSON(json['height']),
        'length': MeasureFromJSON(json['length']),
        'weight': MeasureFromJSON(json['weight']),
        'width': MeasureFromJSON(json['width']),
    };
}

export function DimensionsToJSON(value?: Dimensions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'height': MeasureToJSON(value.height),
        'length': MeasureToJSON(value.length),
        'weight': MeasureToJSON(value.weight),
        'width': MeasureToJSON(value.width),
    };
}

