/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventCutoffTicketRequest
 */
export interface EventCutoffTicketRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof EventCutoffTicketRequest
     */
    orderIds: Array<number>;
}

/**
 * Check if a given object implements the EventCutoffTicketRequest interface.
 */
export function instanceOfEventCutoffTicketRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "orderIds" in value;

    return isInstance;
}

export function EventCutoffTicketRequestFromJSON(json: any): EventCutoffTicketRequest {
    return EventCutoffTicketRequestFromJSONTyped(json, false);
}

export function EventCutoffTicketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventCutoffTicketRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderIds': json['order_ids'],
    };
}

export function EventCutoffTicketRequestToJSON(value?: EventCutoffTicketRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order_ids': value.orderIds,
    };
}

