/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventTicketStatus
 */
export interface EventTicketStatus {
    /**
     * 
     * @type {number}
     * @memberof EventTicketStatus
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof EventTicketStatus
     */
    readable: string;
}

/**
 * Check if a given object implements the EventTicketStatus interface.
 */
export function instanceOfEventTicketStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "readable" in value;

    return isInstance;
}

export function EventTicketStatusFromJSON(json: any): EventTicketStatus {
    return EventTicketStatusFromJSONTyped(json, false);
}

export function EventTicketStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventTicketStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'readable': json['readable'],
    };
}

export function EventTicketStatusToJSON(value?: EventTicketStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'readable': value.readable,
    };
}

