/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EventTicketStatus } from './EventTicketStatus';
import {
    EventTicketStatusFromJSON,
    EventTicketStatusFromJSONTyped,
    EventTicketStatusToJSON,
} from './EventTicketStatus';

/**
 * 
 * @export
 * @interface EventCutoffTicketResponse
 */
export interface EventCutoffTicketResponse {
    /**
     * 
     * @type {EventTicketStatus}
     * @memberof EventCutoffTicketResponse
     */
    status: EventTicketStatus;
}

/**
 * Check if a given object implements the EventCutoffTicketResponse interface.
 */
export function instanceOfEventCutoffTicketResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function EventCutoffTicketResponseFromJSON(json: any): EventCutoffTicketResponse {
    return EventCutoffTicketResponseFromJSONTyped(json, false);
}

export function EventCutoffTicketResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventCutoffTicketResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': EventTicketStatusFromJSON(json['status']),
    };
}

export function EventCutoffTicketResponseToJSON(value?: EventCutoffTicketResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': EventTicketStatusToJSON(value.status),
    };
}

