/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EventFetchTicketResponseTicketOrder } from './EventFetchTicketResponseTicketOrder';
import {
    EventFetchTicketResponseTicketOrderFromJSON,
    EventFetchTicketResponseTicketOrderFromJSONTyped,
    EventFetchTicketResponseTicketOrderToJSON,
} from './EventFetchTicketResponseTicketOrder';
import type { EventTicketStatus } from './EventTicketStatus';
import {
    EventTicketStatusFromJSON,
    EventTicketStatusFromJSONTyped,
    EventTicketStatusToJSON,
} from './EventTicketStatus';

/**
 * 
 * @export
 * @interface EventFetchTicketResponse
 */
export interface EventFetchTicketResponse {
    /**
     * 
     * @type {string}
     * @memberof EventFetchTicketResponse
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof EventFetchTicketResponse
     */
    event: string;
    /**
     * 
     * @type {string}
     * @memberof EventFetchTicketResponse
     */
    legalName: string;
    /**
     * 
     * @type {string}
     * @memberof EventFetchTicketResponse
     */
    nid: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof EventFetchTicketResponse
     */
    orderIds: Array<number>;
    /**
     * 
     * @type {EventTicketStatus}
     * @memberof EventFetchTicketResponse
     */
    status: EventTicketStatus;
    /**
     * 
     * @type {Array<string>}
     * @memberof EventFetchTicketResponse
     */
    tickets: Array<string>;
    /**
     * 
     * @type {Array<EventFetchTicketResponseTicketOrder>}
     * @memberof EventFetchTicketResponse
     */
    ticketsV2?: Array<EventFetchTicketResponseTicketOrder>;
}

/**
 * Check if a given object implements the EventFetchTicketResponse interface.
 */
export function instanceOfEventFetchTicketResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "event" in value;
    isInstance = isInstance && "legalName" in value;
    isInstance = isInstance && "nid" in value;
    isInstance = isInstance && "orderIds" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "tickets" in value;

    return isInstance;
}

export function EventFetchTicketResponseFromJSON(json: any): EventFetchTicketResponse {
    return EventFetchTicketResponseFromJSONTyped(json, false);
}

export function EventFetchTicketResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventFetchTicketResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': json['date'],
        'event': json['event'],
        'legalName': json['legal_name'],
        'nid': json['nid'],
        'orderIds': json['order_ids'],
        'status': EventTicketStatusFromJSON(json['status']),
        'tickets': json['tickets'],
        'ticketsV2': !exists(json, 'tickets_v2') ? undefined : ((json['tickets_v2'] as Array<any>).map(EventFetchTicketResponseTicketOrderFromJSON)),
    };
}

export function EventFetchTicketResponseToJSON(value?: EventFetchTicketResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date,
        'event': value.event,
        'legal_name': value.legalName,
        'nid': value.nid,
        'order_ids': value.orderIds,
        'status': EventTicketStatusToJSON(value.status),
        'tickets': value.tickets,
        'tickets_v2': value.ticketsV2 === undefined ? undefined : ((value.ticketsV2 as Array<any>).map(EventFetchTicketResponseTicketOrderToJSON)),
    };
}

