/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FQRequest
 */
export interface FQRequest {
    /**
     * 
     * @type {string}
     * @memberof FQRequest
     */
    key: string;
    /**
     * 
     * @type {boolean}
     * @memberof FQRequest
     */
    negative?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FQRequest
     */
    tag?: string;
    /**
     * 
     * @type {string}
     * @memberof FQRequest
     */
    value: string;
}

/**
 * Check if a given object implements the FQRequest interface.
 */
export function instanceOfFQRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function FQRequestFromJSON(json: any): FQRequest {
    return FQRequestFromJSONTyped(json, false);
}

export function FQRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FQRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'negative': !exists(json, 'negative') ? undefined : json['negative'],
        'tag': !exists(json, 'tag') ? undefined : json['tag'],
        'value': json['value'],
    };
}

export function FQRequestToJSON(value?: FQRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'negative': value.negative,
        'tag': value.tag,
        'value': value.value,
    };
}

