/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { POPackingListItem } from './POPackingListItem';
import {
    POPackingListItemFromJSON,
    POPackingListItemFromJSONTyped,
    POPackingListItemToJSON,
} from './POPackingListItem';
import type { POZoneInformation } from './POZoneInformation';
import {
    POZoneInformationFromJSON,
    POZoneInformationFromJSONTyped,
    POZoneInformationToJSON,
} from './POZoneInformation';

/**
 * 
 * @export
 * @interface GenericPOPackingListResponseMobil
 */
export interface GenericPOPackingListResponseMobil {
    /**
     * 
     * @type {boolean}
     * @memberof GenericPOPackingListResponseMobil
     */
    canClose: boolean;
    /**
     * 
     * @type {string}
     * @memberof GenericPOPackingListResponseMobil
     */
    code: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenericPOPackingListResponseMobil
     */
    completed: boolean;
    /**
     * 
     * @type {number}
     * @memberof GenericPOPackingListResponseMobil
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof GenericPOPackingListResponseMobil
     */
    inProcess: boolean;
    /**
     * 
     * @type {Array<POPackingListItem>}
     * @memberof GenericPOPackingListResponseMobil
     */
    items?: Array<POPackingListItem>;
    /**
     * 
     * @type {string}
     * @memberof GenericPOPackingListResponseMobil
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof GenericPOPackingListResponseMobil
     */
    poId: number;
    /**
     * 
     * @type {Array<POZoneInformation>}
     * @memberof GenericPOPackingListResponseMobil
     */
    zoneInformation?: Array<POZoneInformation>;
}

/**
 * Check if a given object implements the GenericPOPackingListResponseMobil interface.
 */
export function instanceOfGenericPOPackingListResponseMobil(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "canClose" in value;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "completed" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "inProcess" in value;
    isInstance = isInstance && "poId" in value;

    return isInstance;
}

export function GenericPOPackingListResponseMobilFromJSON(json: any): GenericPOPackingListResponseMobil {
    return GenericPOPackingListResponseMobilFromJSONTyped(json, false);
}

export function GenericPOPackingListResponseMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericPOPackingListResponseMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'canClose': json['can_close'],
        'code': json['code'],
        'completed': json['completed'],
        'id': json['id'],
        'inProcess': json['in_process'],
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(POPackingListItemFromJSON)),
        'message': !exists(json, 'message') ? undefined : json['message'],
        'poId': json['po_id'],
        'zoneInformation': !exists(json, 'zone_information') ? undefined : ((json['zone_information'] as Array<any>).map(POZoneInformationFromJSON)),
    };
}

export function GenericPOPackingListResponseMobilToJSON(value?: GenericPOPackingListResponseMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'can_close': value.canClose,
        'code': value.code,
        'completed': value.completed,
        'id': value.id,
        'in_process': value.inProcess,
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(POPackingListItemToJSON)),
        'message': value.message,
        'po_id': value.poId,
        'zone_information': value.zoneInformation === undefined ? undefined : ((value.zoneInformation as Array<any>).map(POZoneInformationToJSON)),
    };
}

