/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPaymentRequestRequest
 */
export interface GetPaymentRequestRequest {
    /**
     * 
     * @type {string}
     * @memberof GetPaymentRequestRequest
     */
    pubId: string;
}

/**
 * Check if a given object implements the GetPaymentRequestRequest interface.
 */
export function instanceOfGetPaymentRequestRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pubId" in value;

    return isInstance;
}

export function GetPaymentRequestRequestFromJSON(json: any): GetPaymentRequestRequest {
    return GetPaymentRequestRequestFromJSONTyped(json, false);
}

export function GetPaymentRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPaymentRequestRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pubId': json['pub_id'],
    };
}

export function GetPaymentRequestRequestToJSON(value?: GetPaymentRequestRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pub_id': value.pubId,
    };
}

