/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Transaction } from './Transaction';
import {
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
} from './Transaction';

/**
 * 
 * @export
 * @interface GetPaymentRequestResponse
 */
export interface GetPaymentRequestResponse {
    /**
     * 
     * @type {Transaction}
     * @memberof GetPaymentRequestResponse
     */
    transaction: Transaction;
}

/**
 * Check if a given object implements the GetPaymentRequestResponse interface.
 */
export function instanceOfGetPaymentRequestResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "transaction" in value;

    return isInstance;
}

export function GetPaymentRequestResponseFromJSON(json: any): GetPaymentRequestResponse {
    return GetPaymentRequestResponseFromJSONTyped(json, false);
}

export function GetPaymentRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPaymentRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transaction': TransactionFromJSON(json['transaction']),
    };
}

export function GetPaymentRequestResponseToJSON(value?: GetPaymentRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transaction': TransactionToJSON(value.transaction),
    };
}

