/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GITEcommerceMCPCartItem } from './GITEcommerceMCPCartItem';
import {
    GITEcommerceMCPCartItemFromJSON,
    GITEcommerceMCPCartItemFromJSONTyped,
    GITEcommerceMCPCartItemToJSON,
} from './GITEcommerceMCPCartItem';

/**
 * 
 * @export
 * @interface GITEcommerceMCPCartDataResponse
 */
export interface GITEcommerceMCPCartDataResponse {
    /**
     * 
     * @type {Array<GITEcommerceMCPCartItem>}
     * @memberof GITEcommerceMCPCartDataResponse
     */
    cartItems: Array<GITEcommerceMCPCartItem>;
    /**
     * 
     * @type {string}
     * @memberof GITEcommerceMCPCartDataResponse
     */
    cartSubtotal: string;
    /**
     * 
     * @type {string}
     * @memberof GITEcommerceMCPCartDataResponse
     */
    cartTotal: string;
    /**
     * 
     * @type {string}
     * @memberof GITEcommerceMCPCartDataResponse
     */
    shippingAmount: string;
}

/**
 * Check if a given object implements the GITEcommerceMCPCartDataResponse interface.
 */
export function instanceOfGITEcommerceMCPCartDataResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cartItems" in value;
    isInstance = isInstance && "cartSubtotal" in value;
    isInstance = isInstance && "cartTotal" in value;
    isInstance = isInstance && "shippingAmount" in value;

    return isInstance;
}

export function GITEcommerceMCPCartDataResponseFromJSON(json: any): GITEcommerceMCPCartDataResponse {
    return GITEcommerceMCPCartDataResponseFromJSONTyped(json, false);
}

export function GITEcommerceMCPCartDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITEcommerceMCPCartDataResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cartItems': ((json['cart_items'] as Array<any>).map(GITEcommerceMCPCartItemFromJSON)),
        'cartSubtotal': json['cart_subtotal'],
        'cartTotal': json['cart_total'],
        'shippingAmount': json['shipping_amount'],
    };
}

export function GITEcommerceMCPCartDataResponseToJSON(value?: GITEcommerceMCPCartDataResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cart_items': ((value.cartItems as Array<any>).map(GITEcommerceMCPCartItemToJSON)),
        'cart_subtotal': value.cartSubtotal,
        'cart_total': value.cartTotal,
        'shipping_amount': value.shippingAmount,
    };
}

