/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CartItem } from './CartItem';
import {
    CartItemFromJSON,
    CartItemFromJSONTyped,
    CartItemToJSON,
} from './CartItem';
import type { GITEcommerceMCPCheckoutCustomerData } from './GITEcommerceMCPCheckoutCustomerData';
import {
    GITEcommerceMCPCheckoutCustomerDataFromJSON,
    GITEcommerceMCPCheckoutCustomerDataFromJSONTyped,
    GITEcommerceMCPCheckoutCustomerDataToJSON,
} from './GITEcommerceMCPCheckoutCustomerData';

/**
 * 
 * @export
 * @interface GITEcommerceMCPCreateCheckoutRequest
 */
export interface GITEcommerceMCPCreateCheckoutRequest {
    /**
     * 
     * @type {Array<CartItem>}
     * @memberof GITEcommerceMCPCreateCheckoutRequest
     */
    cartItems: Array<CartItem>;
    /**
     * 
     * @type {GITEcommerceMCPCheckoutCustomerData}
     * @memberof GITEcommerceMCPCreateCheckoutRequest
     */
    customerData: GITEcommerceMCPCheckoutCustomerData;
    /**
     * 
     * @type {string}
     * @memberof GITEcommerceMCPCreateCheckoutRequest
     */
    shippingAmount: string;
}

/**
 * Check if a given object implements the GITEcommerceMCPCreateCheckoutRequest interface.
 */
export function instanceOfGITEcommerceMCPCreateCheckoutRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cartItems" in value;
    isInstance = isInstance && "customerData" in value;
    isInstance = isInstance && "shippingAmount" in value;

    return isInstance;
}

export function GITEcommerceMCPCreateCheckoutRequestFromJSON(json: any): GITEcommerceMCPCreateCheckoutRequest {
    return GITEcommerceMCPCreateCheckoutRequestFromJSONTyped(json, false);
}

export function GITEcommerceMCPCreateCheckoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITEcommerceMCPCreateCheckoutRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cartItems': ((json['cart_items'] as Array<any>).map(CartItemFromJSON)),
        'customerData': GITEcommerceMCPCheckoutCustomerDataFromJSON(json['customer_data']),
        'shippingAmount': json['shipping_amount'],
    };
}

export function GITEcommerceMCPCreateCheckoutRequestToJSON(value?: GITEcommerceMCPCreateCheckoutRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cart_items': ((value.cartItems as Array<any>).map(CartItemToJSON)),
        'customer_data': GITEcommerceMCPCheckoutCustomerDataToJSON(value.customerData),
        'shipping_amount': value.shippingAmount,
    };
}

