/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LineCard } from './LineCard';
import {
    LineCardFromJSON,
    LineCardFromJSONTyped,
    LineCardToJSON,
} from './LineCard';

/**
 * 
 * @export
 * @interface GITEcommerceMCPLineCheckoutRequest
 */
export interface GITEcommerceMCPLineCheckoutRequest {
    /**
     * 
     * @type {LineCard}
     * @memberof GITEcommerceMCPLineCheckoutRequest
     */
    card: LineCard;
    /**
     * 
     * @type {string}
     * @memberof GITEcommerceMCPLineCheckoutRequest
     */
    checkoutCode: string;
}

/**
 * Check if a given object implements the GITEcommerceMCPLineCheckoutRequest interface.
 */
export function instanceOfGITEcommerceMCPLineCheckoutRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "card" in value;
    isInstance = isInstance && "checkoutCode" in value;

    return isInstance;
}

export function GITEcommerceMCPLineCheckoutRequestFromJSON(json: any): GITEcommerceMCPLineCheckoutRequest {
    return GITEcommerceMCPLineCheckoutRequestFromJSONTyped(json, false);
}

export function GITEcommerceMCPLineCheckoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITEcommerceMCPLineCheckoutRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'card': LineCardFromJSON(json['card']),
        'checkoutCode': json['checkout_code'],
    };
}

export function GITEcommerceMCPLineCheckoutRequestToJSON(value?: GITEcommerceMCPLineCheckoutRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'card': LineCardToJSON(value.card),
        'checkout_code': value.checkoutCode,
    };
}

