/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GITEcommerceMCPLineCheckoutResponse
 */
export interface GITEcommerceMCPLineCheckoutResponse {
    /**
     * 
     * @type {number}
     * @memberof GITEcommerceMCPLineCheckoutResponse
     */
    ostId: number;
    /**
     * 
     * @type {string}
     * @memberof GITEcommerceMCPLineCheckoutResponse
     */
    status: string;
}

/**
 * Check if a given object implements the GITEcommerceMCPLineCheckoutResponse interface.
 */
export function instanceOfGITEcommerceMCPLineCheckoutResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ostId" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function GITEcommerceMCPLineCheckoutResponseFromJSON(json: any): GITEcommerceMCPLineCheckoutResponse {
    return GITEcommerceMCPLineCheckoutResponseFromJSONTyped(json, false);
}

export function GITEcommerceMCPLineCheckoutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITEcommerceMCPLineCheckoutResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ostId': json['ost_id'],
        'status': json['status'],
    };
}

export function GITEcommerceMCPLineCheckoutResponseToJSON(value?: GITEcommerceMCPLineCheckoutResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ost_id': value.ostId,
        'status': value.status,
    };
}

