/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GITEcommerceMCPOrderStatusRequest
 */
export interface GITEcommerceMCPOrderStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof GITEcommerceMCPOrderStatusRequest
     */
    phoneNumber: string;
}

/**
 * Check if a given object implements the GITEcommerceMCPOrderStatusRequest interface.
 */
export function instanceOfGITEcommerceMCPOrderStatusRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "phoneNumber" in value;

    return isInstance;
}

export function GITEcommerceMCPOrderStatusRequestFromJSON(json: any): GITEcommerceMCPOrderStatusRequest {
    return GITEcommerceMCPOrderStatusRequestFromJSONTyped(json, false);
}

export function GITEcommerceMCPOrderStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITEcommerceMCPOrderStatusRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'phoneNumber': json['phone_number'],
    };
}

export function GITEcommerceMCPOrderStatusRequestToJSON(value?: GITEcommerceMCPOrderStatusRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'phone_number': value.phoneNumber,
    };
}

