/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GITEcommerceMCPOrdersReportMoneyTransfer
 */
export interface GITEcommerceMCPOrdersReportMoneyTransfer {
    /**
     * 
     * @type {string}
     * @memberof GITEcommerceMCPOrdersReportMoneyTransfer
     */
    confirmedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof GITEcommerceMCPOrdersReportMoneyTransfer
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof GITEcommerceMCPOrdersReportMoneyTransfer
     */
    status: string;
}

/**
 * Check if a given object implements the GITEcommerceMCPOrdersReportMoneyTransfer interface.
 */
export function instanceOfGITEcommerceMCPOrdersReportMoneyTransfer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function GITEcommerceMCPOrdersReportMoneyTransferFromJSON(json: any): GITEcommerceMCPOrdersReportMoneyTransfer {
    return GITEcommerceMCPOrdersReportMoneyTransferFromJSONTyped(json, false);
}

export function GITEcommerceMCPOrdersReportMoneyTransferFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITEcommerceMCPOrdersReportMoneyTransfer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'confirmedAt': !exists(json, 'confirmed_at') ? undefined : json['confirmed_at'],
        'description': json['description'],
        'status': json['status'],
    };
}

export function GITEcommerceMCPOrdersReportMoneyTransferToJSON(value?: GITEcommerceMCPOrdersReportMoneyTransfer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'confirmed_at': value.confirmedAt,
        'description': value.description,
        'status': value.status,
    };
}

