/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GITEcommerceMCPOrdersReportMoneyTransfer } from './GITEcommerceMCPOrdersReportMoneyTransfer';
import {
    GITEcommerceMCPOrdersReportMoneyTransferFromJSON,
    GITEcommerceMCPOrdersReportMoneyTransferFromJSONTyped,
    GITEcommerceMCPOrdersReportMoneyTransferToJSON,
} from './GITEcommerceMCPOrdersReportMoneyTransfer';
import type { GITEcommerceMCPOrdersReportOrders } from './GITEcommerceMCPOrdersReportOrders';
import {
    GITEcommerceMCPOrdersReportOrdersFromJSON,
    GITEcommerceMCPOrdersReportOrdersFromJSONTyped,
    GITEcommerceMCPOrdersReportOrdersToJSON,
} from './GITEcommerceMCPOrdersReportOrders';

/**
 * 
 * @export
 * @interface GITEcommerceMCPOrderStatusResponse
 */
export interface GITEcommerceMCPOrderStatusResponse {
    /**
     * 
     * @type {Array<GITEcommerceMCPOrdersReportMoneyTransfer>}
     * @memberof GITEcommerceMCPOrderStatusResponse
     */
    moneyTransfers?: Array<GITEcommerceMCPOrdersReportMoneyTransfer>;
    /**
     * 
     * @type {Array<GITEcommerceMCPOrdersReportOrders>}
     * @memberof GITEcommerceMCPOrderStatusResponse
     */
    orders?: Array<GITEcommerceMCPOrdersReportOrders>;
}

/**
 * Check if a given object implements the GITEcommerceMCPOrderStatusResponse interface.
 */
export function instanceOfGITEcommerceMCPOrderStatusResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GITEcommerceMCPOrderStatusResponseFromJSON(json: any): GITEcommerceMCPOrderStatusResponse {
    return GITEcommerceMCPOrderStatusResponseFromJSONTyped(json, false);
}

export function GITEcommerceMCPOrderStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITEcommerceMCPOrderStatusResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'moneyTransfers': !exists(json, 'money_transfers') ? undefined : ((json['money_transfers'] as Array<any>).map(GITEcommerceMCPOrdersReportMoneyTransferFromJSON)),
        'orders': !exists(json, 'orders') ? undefined : ((json['orders'] as Array<any>).map(GITEcommerceMCPOrdersReportOrdersFromJSON)),
    };
}

export function GITEcommerceMCPOrderStatusResponseToJSON(value?: GITEcommerceMCPOrderStatusResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'money_transfers': value.moneyTransfers === undefined ? undefined : ((value.moneyTransfers as Array<any>).map(GITEcommerceMCPOrdersReportMoneyTransferToJSON)),
        'orders': value.orders === undefined ? undefined : ((value.orders as Array<any>).map(GITEcommerceMCPOrdersReportOrdersToJSON)),
    };
}

