/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CartItem } from './CartItem';
import {
    CartItemFromJSON,
    CartItemFromJSONTyped,
    CartItemToJSON,
} from './CartItem';

/**
 * 
 * @export
 * @interface GITEcommerceMCPCartDataRequest
 */
export interface GITEcommerceMCPCartDataRequest {
    /**
     * 
     * @type {Array<CartItem>}
     * @memberof GITEcommerceMCPCartDataRequest
     */
    cartItems: Array<CartItem>;
    /**
     * 
     * @type {string}
     * @memberof GITEcommerceMCPCartDataRequest
     */
    shippingAmount: string;
}

/**
 * Check if a given object implements the GITEcommerceMCPCartDataRequest interface.
 */
export function instanceOfGITEcommerceMCPCartDataRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cartItems" in value;
    isInstance = isInstance && "shippingAmount" in value;

    return isInstance;
}

export function GITEcommerceMCPCartDataRequestFromJSON(json: any): GITEcommerceMCPCartDataRequest {
    return GITEcommerceMCPCartDataRequestFromJSONTyped(json, false);
}

export function GITEcommerceMCPCartDataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITEcommerceMCPCartDataRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cartItems': ((json['cart_items'] as Array<any>).map(CartItemFromJSON)),
        'shippingAmount': json['shipping_amount'],
    };
}

export function GITEcommerceMCPCartDataRequestToJSON(value?: GITEcommerceMCPCartDataRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cart_items': ((value.cartItems as Array<any>).map(CartItemToJSON)),
        'shipping_amount': value.shippingAmount,
    };
}

