/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GITEcommerceMCPMercadoPagoCancelResponse
 */
export interface GITEcommerceMCPMercadoPagoCancelResponse {
    /**
     * 
     * @type {string}
     * @memberof GITEcommerceMCPMercadoPagoCancelResponse
     */
    status: string;
}

/**
 * Check if a given object implements the GITEcommerceMCPMercadoPagoCancelResponse interface.
 */
export function instanceOfGITEcommerceMCPMercadoPagoCancelResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function GITEcommerceMCPMercadoPagoCancelResponseFromJSON(json: any): GITEcommerceMCPMercadoPagoCancelResponse {
    return GITEcommerceMCPMercadoPagoCancelResponseFromJSONTyped(json, false);
}

export function GITEcommerceMCPMercadoPagoCancelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITEcommerceMCPMercadoPagoCancelResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function GITEcommerceMCPMercadoPagoCancelResponseToJSON(value?: GITEcommerceMCPMercadoPagoCancelResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}

