/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GITEcommerceMCPGetCheckoutRequest
 */
export interface GITEcommerceMCPGetCheckoutRequest {
    /**
     * 
     * @type {string}
     * @memberof GITEcommerceMCPGetCheckoutRequest
     */
    checkoutCode: string;
}

/**
 * Check if a given object implements the GITEcommerceMCPGetCheckoutRequest interface.
 */
export function instanceOfGITEcommerceMCPGetCheckoutRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "checkoutCode" in value;

    return isInstance;
}

export function GITEcommerceMCPGetCheckoutRequestFromJSON(json: any): GITEcommerceMCPGetCheckoutRequest {
    return GITEcommerceMCPGetCheckoutRequestFromJSONTyped(json, false);
}

export function GITEcommerceMCPGetCheckoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITEcommerceMCPGetCheckoutRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checkoutCode': json['checkout_code'],
    };
}

export function GITEcommerceMCPGetCheckoutRequestToJSON(value?: GITEcommerceMCPGetCheckoutRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'checkout_code': value.checkoutCode,
    };
}

