/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GITEcommerceMCPMercadoPagoCancelRequest
 */
export interface GITEcommerceMCPMercadoPagoCancelRequest {
    /**
     * 
     * @type {string}
     * @memberof GITEcommerceMCPMercadoPagoCancelRequest
     */
    externalReference: string;
    /**
     * 
     * @type {string}
     * @memberof GITEcommerceMCPMercadoPagoCancelRequest
     */
    preferenceId: string;
}

/**
 * Check if a given object implements the GITEcommerceMCPMercadoPagoCancelRequest interface.
 */
export function instanceOfGITEcommerceMCPMercadoPagoCancelRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "externalReference" in value;
    isInstance = isInstance && "preferenceId" in value;

    return isInstance;
}

export function GITEcommerceMCPMercadoPagoCancelRequestFromJSON(json: any): GITEcommerceMCPMercadoPagoCancelRequest {
    return GITEcommerceMCPMercadoPagoCancelRequestFromJSONTyped(json, false);
}

export function GITEcommerceMCPMercadoPagoCancelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITEcommerceMCPMercadoPagoCancelRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'externalReference': json['external_reference'],
        'preferenceId': json['preference_id'],
    };
}

export function GITEcommerceMCPMercadoPagoCancelRequestToJSON(value?: GITEcommerceMCPMercadoPagoCancelRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'external_reference': value.externalReference,
        'preference_id': value.preferenceId,
    };
}

