/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GITEcommerceMCPSendMediaWhatsappResponse
 */
export interface GITEcommerceMCPSendMediaWhatsappResponse {
    /**
     * 
     * @type {string}
     * @memberof GITEcommerceMCPSendMediaWhatsappResponse
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof GITEcommerceMCPSendMediaWhatsappResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the GITEcommerceMCPSendMediaWhatsappResponse interface.
 */
export function instanceOfGITEcommerceMCPSendMediaWhatsappResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "success" in value;

    return isInstance;
}

export function GITEcommerceMCPSendMediaWhatsappResponseFromJSON(json: any): GITEcommerceMCPSendMediaWhatsappResponse {
    return GITEcommerceMCPSendMediaWhatsappResponseFromJSONTyped(json, false);
}

export function GITEcommerceMCPSendMediaWhatsappResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITEcommerceMCPSendMediaWhatsappResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'success': json['success'],
    };
}

export function GITEcommerceMCPSendMediaWhatsappResponseToJSON(value?: GITEcommerceMCPSendMediaWhatsappResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'success': value.success,
    };
}

