/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GITEcommerceMCPMercadoPagoCheckoutResponse
 */
export interface GITEcommerceMCPMercadoPagoCheckoutResponse {
    /**
     * 
     * @type {string}
     * @memberof GITEcommerceMCPMercadoPagoCheckoutResponse
     */
    paymentLink: string;
}

/**
 * Check if a given object implements the GITEcommerceMCPMercadoPagoCheckoutResponse interface.
 */
export function instanceOfGITEcommerceMCPMercadoPagoCheckoutResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "paymentLink" in value;

    return isInstance;
}

export function GITEcommerceMCPMercadoPagoCheckoutResponseFromJSON(json: any): GITEcommerceMCPMercadoPagoCheckoutResponse {
    return GITEcommerceMCPMercadoPagoCheckoutResponseFromJSONTyped(json, false);
}

export function GITEcommerceMCPMercadoPagoCheckoutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITEcommerceMCPMercadoPagoCheckoutResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'paymentLink': json['payment_link'],
    };
}

export function GITEcommerceMCPMercadoPagoCheckoutResponseToJSON(value?: GITEcommerceMCPMercadoPagoCheckoutResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'payment_link': value.paymentLink,
    };
}

