/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GITViarapidaUpdateOrder3PStatusRequest
 */
export interface GITViarapidaUpdateOrder3PStatusRequest {
    /**
     * 
     * @type {number}
     * @memberof GITViarapidaUpdateOrder3PStatusRequest
     */
    orderId: number;
    /**
     * 
     * @type {number}
     * @memberof GITViarapidaUpdateOrder3PStatusRequest
     */
    preparationMinutes?: number;
    /**
     * 
     * @type {number}
     * @memberof GITViarapidaUpdateOrder3PStatusRequest
     */
    status: number;
}

/**
 * Check if a given object implements the GITViarapidaUpdateOrder3PStatusRequest interface.
 */
export function instanceOfGITViarapidaUpdateOrder3PStatusRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "orderId" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function GITViarapidaUpdateOrder3PStatusRequestFromJSON(json: any): GITViarapidaUpdateOrder3PStatusRequest {
    return GITViarapidaUpdateOrder3PStatusRequestFromJSONTyped(json, false);
}

export function GITViarapidaUpdateOrder3PStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITViarapidaUpdateOrder3PStatusRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderId': json['order_id'],
        'preparationMinutes': !exists(json, 'preparation_minutes') ? undefined : json['preparation_minutes'],
        'status': json['status'],
    };
}

export function GITViarapidaUpdateOrder3PStatusRequestToJSON(value?: GITViarapidaUpdateOrder3PStatusRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order_id': value.orderId,
        'preparation_minutes': value.preparationMinutes,
        'status': value.status,
    };
}

