/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GITViaRapidaOrderItem } from './GITViaRapidaOrderItem';
import {
    GITViaRapidaOrderItemFromJSON,
    GITViaRapidaOrderItemFromJSONTyped,
    GITViaRapidaOrderItemToJSON,
} from './GITViaRapidaOrderItem';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './Money';
import type { ShortAddress } from './ShortAddress';
import {
    ShortAddressFromJSON,
    ShortAddressFromJSONTyped,
    ShortAddressToJSON,
} from './ShortAddress';
import type { ViaRapida3PSeller } from './ViaRapida3PSeller';
import {
    ViaRapida3PSellerFromJSON,
    ViaRapida3PSellerFromJSONTyped,
    ViaRapida3PSellerToJSON,
} from './ViaRapida3PSeller';
import type { ViarapidaOrderStatus } from './ViarapidaOrderStatus';
import {
    ViarapidaOrderStatusFromJSON,
    ViarapidaOrderStatusFromJSONTyped,
    ViarapidaOrderStatusToJSON,
} from './ViarapidaOrderStatus';

/**
 * 
 * @export
 * @interface GITViarapidaOrder3P
 */
export interface GITViarapidaOrder3P {
    /**
     * 
     * @type {string}
     * @memberof GITViarapidaOrder3P
     */
    authorizedAt: string;
    /**
     * 
     * @type {string}
     * @memberof GITViarapidaOrder3P
     */
    customerName: string;
    /**
     * 
     * @type {ShortAddress}
     * @memberof GITViarapidaOrder3P
     */
    deliveryAddress: ShortAddress;
    /**
     * 
     * @type {number}
     * @memberof GITViarapidaOrder3P
     */
    id: number;
    /**
     * 
     * @type {Array<GITViaRapidaOrderItem>}
     * @memberof GITViarapidaOrder3P
     */
    items: Array<GITViaRapidaOrderItem>;
    /**
     * 
     * @type {string}
     * @memberof GITViarapidaOrder3P
     */
    pickupAt: string;
    /**
     * 
     * @type {number}
     * @memberof GITViarapidaOrder3P
     */
    quoteId?: number;
    /**
     * 
     * @type {ViaRapida3PSeller}
     * @memberof GITViarapidaOrder3P
     */
    seller: ViaRapida3PSeller;
    /**
     * 
     * @type {string}
     * @memberof GITViarapidaOrder3P
     */
    sellerPaymentMethod?: string;
    /**
     * 
     * @type {ViarapidaOrderStatus}
     * @memberof GITViarapidaOrder3P
     */
    status: ViarapidaOrderStatus;
    /**
     * 
     * @type {Money}
     * @memberof GITViarapidaOrder3P
     */
    total: Money;
}

/**
 * Check if a given object implements the GITViarapidaOrder3P interface.
 */
export function instanceOfGITViarapidaOrder3P(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "authorizedAt" in value;
    isInstance = isInstance && "customerName" in value;
    isInstance = isInstance && "deliveryAddress" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "items" in value;
    isInstance = isInstance && "pickupAt" in value;
    isInstance = isInstance && "seller" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function GITViarapidaOrder3PFromJSON(json: any): GITViarapidaOrder3P {
    return GITViarapidaOrder3PFromJSONTyped(json, false);
}

export function GITViarapidaOrder3PFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITViarapidaOrder3P {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authorizedAt': json['authorized_at'],
        'customerName': json['customer_name'],
        'deliveryAddress': ShortAddressFromJSON(json['delivery_address']),
        'id': json['id'],
        'items': ((json['items'] as Array<any>).map(GITViaRapidaOrderItemFromJSON)),
        'pickupAt': json['pickup_at'],
        'quoteId': !exists(json, 'quote_id') ? undefined : json['quote_id'],
        'seller': ViaRapida3PSellerFromJSON(json['seller']),
        'sellerPaymentMethod': !exists(json, 'seller_payment_method') ? undefined : json['seller_payment_method'],
        'status': ViarapidaOrderStatusFromJSON(json['status']),
        'total': MoneyFromJSON(json['total']),
    };
}

export function GITViarapidaOrder3PToJSON(value?: GITViarapidaOrder3P | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authorized_at': value.authorizedAt,
        'customer_name': value.customerName,
        'delivery_address': ShortAddressToJSON(value.deliveryAddress),
        'id': value.id,
        'items': ((value.items as Array<any>).map(GITViaRapidaOrderItemToJSON)),
        'pickup_at': value.pickupAt,
        'quote_id': value.quoteId,
        'seller': ViaRapida3PSellerToJSON(value.seller),
        'seller_payment_method': value.sellerPaymentMethod,
        'status': ViarapidaOrderStatusToJSON(value.status),
        'total': MoneyToJSON(value.total),
    };
}

