/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GITViarapidaEditOrder3PResponse
 */
export interface GITViarapidaEditOrder3PResponse {
    /**
     * 
     * @type {string}
     * @memberof GITViarapidaEditOrder3PResponse
     */
    status: string;
}

/**
 * Check if a given object implements the GITViarapidaEditOrder3PResponse interface.
 */
export function instanceOfGITViarapidaEditOrder3PResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function GITViarapidaEditOrder3PResponseFromJSON(json: any): GITViarapidaEditOrder3PResponse {
    return GITViarapidaEditOrder3PResponseFromJSONTyped(json, false);
}

export function GITViarapidaEditOrder3PResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITViarapidaEditOrder3PResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function GITViarapidaEditOrder3PResponseToJSON(value?: GITViarapidaEditOrder3PResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}

