/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GITViarapidaEditItem3PRequestOptionPrice
 */
export interface GITViarapidaEditItem3PRequestOptionPrice {
    /**
     * 
     * @type {number}
     * @memberof GITViarapidaEditItem3PRequestOptionPrice
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GITViarapidaEditItem3PRequestOptionPrice
     */
    price?: string;
}

/**
 * Check if a given object implements the GITViarapidaEditItem3PRequestOptionPrice interface.
 */
export function instanceOfGITViarapidaEditItem3PRequestOptionPrice(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function GITViarapidaEditItem3PRequestOptionPriceFromJSON(json: any): GITViarapidaEditItem3PRequestOptionPrice {
    return GITViarapidaEditItem3PRequestOptionPriceFromJSONTyped(json, false);
}

export function GITViarapidaEditItem3PRequestOptionPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITViarapidaEditItem3PRequestOptionPrice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'price': !exists(json, 'price') ? undefined : json['price'],
    };
}

export function GITViarapidaEditItem3PRequestOptionPriceToJSON(value?: GITViarapidaEditItem3PRequestOptionPrice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'price': value.price,
    };
}

