/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ImageMetadata } from './ImageMetadata';
import {
    ImageMetadataFromJSON,
    ImageMetadataFromJSONTyped,
    ImageMetadataToJSON,
} from './ImageMetadata';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './Money';
import type { ViaRapida3PCartItemOptionsGroupSelections } from './ViaRapida3PCartItemOptionsGroupSelections';
import {
    ViaRapida3PCartItemOptionsGroupSelectionsFromJSON,
    ViaRapida3PCartItemOptionsGroupSelectionsFromJSONTyped,
    ViaRapida3PCartItemOptionsGroupSelectionsToJSON,
} from './ViaRapida3PCartItemOptionsGroupSelections';

/**
 * 
 * @export
 * @interface GITViaRapidaOrderItem
 */
export interface GITViaRapidaOrderItem {
    /**
     * 
     * @type {boolean}
     * @memberof GITViaRapidaOrderItem
     */
    cancelled: boolean;
    /**
     * 
     * @type {string}
     * @memberof GITViaRapidaOrderItem
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof GITViaRapidaOrderItem
     */
    id: number;
    /**
     * 
     * @type {ImageMetadata}
     * @memberof GITViaRapidaOrderItem
     */
    image: ImageMetadata;
    /**
     * 
     * @type {number}
     * @memberof GITViaRapidaOrderItem
     */
    itemId: number;
    /**
     * 
     * @type {string}
     * @memberof GITViaRapidaOrderItem
     */
    notes?: string;
    /**
     * 
     * @type {Array<ViaRapida3PCartItemOptionsGroupSelections>}
     * @memberof GITViaRapidaOrderItem
     */
    options?: Array<ViaRapida3PCartItemOptionsGroupSelections>;
    /**
     * 
     * @type {number}
     * @memberof GITViaRapidaOrderItem
     */
    orderId: number;
    /**
     * 
     * @type {Money}
     * @memberof GITViaRapidaOrderItem
     */
    price: Money;
    /**
     * 
     * @type {number}
     * @memberof GITViaRapidaOrderItem
     */
    quantity: number;
    /**
     * 
     * @type {boolean}
     * @memberof GITViaRapidaOrderItem
     */
    stock: boolean;
    /**
     * 
     * @type {Money}
     * @memberof GITViaRapidaOrderItem
     */
    total: Money;
}

/**
 * Check if a given object implements the GITViaRapidaOrderItem interface.
 */
export function instanceOfGITViaRapidaOrderItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cancelled" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "image" in value;
    isInstance = isInstance && "itemId" in value;
    isInstance = isInstance && "orderId" in value;
    isInstance = isInstance && "price" in value;
    isInstance = isInstance && "quantity" in value;
    isInstance = isInstance && "stock" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function GITViaRapidaOrderItemFromJSON(json: any): GITViaRapidaOrderItem {
    return GITViaRapidaOrderItemFromJSONTyped(json, false);
}

export function GITViaRapidaOrderItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITViaRapidaOrderItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cancelled': json['cancelled'],
        'description': json['description'],
        'id': json['id'],
        'image': ImageMetadataFromJSON(json['image']),
        'itemId': json['item_id'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'options': !exists(json, 'options') ? undefined : ((json['options'] as Array<any>).map(ViaRapida3PCartItemOptionsGroupSelectionsFromJSON)),
        'orderId': json['order_id'],
        'price': MoneyFromJSON(json['price']),
        'quantity': json['quantity'],
        'stock': json['stock'],
        'total': MoneyFromJSON(json['total']),
    };
}

export function GITViaRapidaOrderItemToJSON(value?: GITViaRapidaOrderItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cancelled': value.cancelled,
        'description': value.description,
        'id': value.id,
        'image': ImageMetadataToJSON(value.image),
        'item_id': value.itemId,
        'notes': value.notes,
        'options': value.options === undefined ? undefined : ((value.options as Array<any>).map(ViaRapida3PCartItemOptionsGroupSelectionsToJSON)),
        'order_id': value.orderId,
        'price': MoneyToJSON(value.price),
        'quantity': value.quantity,
        'stock': value.stock,
        'total': MoneyToJSON(value.total),
    };
}

