/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GITViarapidaOrders3PRequest
 */
export interface GITViarapidaOrders3PRequest {
    /**
     * 
     * @type {boolean}
     * @memberof GITViarapidaOrders3PRequest
     */
    acceptingNewOrders: boolean;
}

/**
 * Check if a given object implements the GITViarapidaOrders3PRequest interface.
 */
export function instanceOfGITViarapidaOrders3PRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "acceptingNewOrders" in value;

    return isInstance;
}

export function GITViarapidaOrders3PRequestFromJSON(json: any): GITViarapidaOrders3PRequest {
    return GITViarapidaOrders3PRequestFromJSONTyped(json, false);
}

export function GITViarapidaOrders3PRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITViarapidaOrders3PRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'acceptingNewOrders': json['accepting_new_orders'],
    };
}

export function GITViarapidaOrders3PRequestToJSON(value?: GITViarapidaOrders3PRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accepting_new_orders': value.acceptingNewOrders,
    };
}

