/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GITViarapidaPreparationTimeOrders3PRequest
 */
export interface GITViarapidaPreparationTimeOrders3PRequest {
    /**
     * 
     * @type {number}
     * @memberof GITViarapidaPreparationTimeOrders3PRequest
     */
    preparationTime: number;
}

/**
 * Check if a given object implements the GITViarapidaPreparationTimeOrders3PRequest interface.
 */
export function instanceOfGITViarapidaPreparationTimeOrders3PRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "preparationTime" in value;

    return isInstance;
}

export function GITViarapidaPreparationTimeOrders3PRequestFromJSON(json: any): GITViarapidaPreparationTimeOrders3PRequest {
    return GITViarapidaPreparationTimeOrders3PRequestFromJSONTyped(json, false);
}

export function GITViarapidaPreparationTimeOrders3PRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITViarapidaPreparationTimeOrders3PRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'preparationTime': json['preparation_time'],
    };
}

export function GITViarapidaPreparationTimeOrders3PRequestToJSON(value?: GITViarapidaPreparationTimeOrders3PRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'preparation_time': value.preparationTime,
    };
}

