/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GITViarapidaRemoveItem3P
 */
export interface GITViarapidaRemoveItem3P {
    /**
     * 
     * @type {number}
     * @memberof GITViarapidaRemoveItem3P
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof GITViarapidaRemoveItem3P
     */
    quoteId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GITViarapidaRemoveItem3P
     */
    withoutStockUntilTommorrow: boolean;
}

/**
 * Check if a given object implements the GITViarapidaRemoveItem3P interface.
 */
export function instanceOfGITViarapidaRemoveItem3P(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "withoutStockUntilTommorrow" in value;

    return isInstance;
}

export function GITViarapidaRemoveItem3PFromJSON(json: any): GITViarapidaRemoveItem3P {
    return GITViarapidaRemoveItem3PFromJSONTyped(json, false);
}

export function GITViarapidaRemoveItem3PFromJSONTyped(json: any, ignoreDiscriminator: boolean): GITViarapidaRemoveItem3P {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'quoteId': !exists(json, 'quote_id') ? undefined : json['quote_id'],
        'withoutStockUntilTommorrow': json['withoutStockUntilTommorrow'],
    };
}

export function GITViarapidaRemoveItem3PToJSON(value?: GITViarapidaRemoveItem3P | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'quote_id': value.quoteId,
        'withoutStockUntilTommorrow': value.withoutStockUntilTommorrow,
    };
}

