/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Identification
 */
export interface Identification {
    /**
     * 
     * @type {string}
     * @memberof Identification
     */
    number?: string;
    /**
     * 
     * @type {string}
     * @memberof Identification
     */
    type?: string;
}

/**
 * Check if a given object implements the Identification interface.
 */
export function instanceOfIdentification(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IdentificationFromJSON(json: any): Identification {
    return IdentificationFromJSONTyped(json, false);
}

export function IdentificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Identification {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': !exists(json, 'number') ? undefined : json['number'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function IdentificationToJSON(value?: Identification | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'type': value.type,
    };
}

