/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseImageMetadata } from './BaseImageMetadata';
import {
    BaseImageMetadataFromJSON,
    BaseImageMetadataFromJSONTyped,
    BaseImageMetadataToJSON,
} from './BaseImageMetadata';

/**
 * 
 * @export
 * @interface ImageMetadata
 */
export interface ImageMetadata {
    /**
     * 
     * @type {string}
     * @memberof ImageMetadata
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ImageMetadata
     */
    height: number;
    /**
     * 
     * @type {string}
     * @memberof ImageMetadata
     */
    id: string;
    /**
     * 
     * @type {Array<BaseImageMetadata>}
     * @memberof ImageMetadata
     */
    thumbnails?: Array<BaseImageMetadata>;
    /**
     * 
     * @type {Date}
     * @memberof ImageMetadata
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof ImageMetadata
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof ImageMetadata
     */
    width: number;
}

/**
 * Check if a given object implements the ImageMetadata interface.
 */
export function instanceOfImageMetadata(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "height" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "width" in value;

    return isInstance;
}

export function ImageMetadataFromJSON(json: any): ImageMetadata {
    return ImageMetadataFromJSONTyped(json, false);
}

export function ImageMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'height': json['height'],
        'id': json['id'],
        'thumbnails': !exists(json, 'thumbnails') ? undefined : ((json['thumbnails'] as Array<any>).map(BaseImageMetadataFromJSON)),
        'timestamp': !exists(json, 'timestamp') ? undefined : (new Date(json['timestamp'])),
        'url': json['url'],
        'width': json['width'],
    };
}

export function ImageMetadataToJSON(value?: ImageMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'height': value.height,
        'id': value.id,
        'thumbnails': value.thumbnails === undefined ? undefined : ((value.thumbnails as Array<any>).map(BaseImageMetadataToJSON)),
        'timestamp': value.timestamp === undefined ? undefined : (value.timestamp.toISOString()),
        'url': value.url,
        'width': value.width,
    };
}

