/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ItemId } from './ItemId';
import {
    ItemIdFromJSON,
    ItemIdFromJSONTyped,
    ItemIdToJSON,
} from './ItemId';

/**
 * 
 * @export
 * @interface ItemInventoryInfoRequest
 */
export interface ItemInventoryInfoRequest {
    /**
     * 
     * @type {ItemId}
     * @memberof ItemInventoryInfoRequest
     */
    itemId: ItemId;
}

/**
 * Check if a given object implements the ItemInventoryInfoRequest interface.
 */
export function instanceOfItemInventoryInfoRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "itemId" in value;

    return isInstance;
}

export function ItemInventoryInfoRequestFromJSON(json: any): ItemInventoryInfoRequest {
    return ItemInventoryInfoRequestFromJSONTyped(json, false);
}

export function ItemInventoryInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemInventoryInfoRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'itemId': ItemIdFromJSON(json['item_id']),
    };
}

export function ItemInventoryInfoRequestToJSON(value?: ItemInventoryInfoRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item_id': ItemIdToJSON(value.itemId),
    };
}

