/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FQRequest } from './FQRequest';
import {
    FQRequestFromJSON,
    FQRequestFromJSONTyped,
    FQRequestToJSON,
} from './FQRequest';

/**
 * 
 * @export
 * @interface ItemSearchRequest
 */
export interface ItemSearchRequest {
    /**
     * 
     * @type {string}
     * @memberof ItemSearchRequest
     */
    boost?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ItemSearchRequest
     */
    canValidateOver18?: boolean;
    /**
     * 
     * @type {Array<FQRequest>}
     * @memberof ItemSearchRequest
     */
    fqs?: Array<FQRequest>;
    /**
     * 
     * @type {string}
     * @memberof ItemSearchRequest
     */
    groupField?: string;
    /**
     * 
     * @type {number}
     * @memberof ItemSearchRequest
     */
    groupLimit?: number;
    /**
     * 
     * @type {string}
     * @memberof ItemSearchRequest
     */
    keywords?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ItemSearchRequest
     */
    over18?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ItemSearchRequest
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemSearchRequest
     */
    resultsPerPage?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemSearchRequest
     */
    sort?: number;
    /**
     * 
     * @type {string}
     * @memberof ItemSearchRequest
     */
    statsFacet?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemSearchRequest
     */
    statsField?: string;
}

/**
 * Check if a given object implements the ItemSearchRequest interface.
 */
export function instanceOfItemSearchRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ItemSearchRequestFromJSON(json: any): ItemSearchRequest {
    return ItemSearchRequestFromJSONTyped(json, false);
}

export function ItemSearchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemSearchRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'boost': !exists(json, 'boost') ? undefined : json['boost'],
        'canValidateOver18': !exists(json, 'can_validate_over18') ? undefined : json['can_validate_over18'],
        'fqs': !exists(json, 'fqs') ? undefined : ((json['fqs'] as Array<any>).map(FQRequestFromJSON)),
        'groupField': !exists(json, 'group_field') ? undefined : json['group_field'],
        'groupLimit': !exists(json, 'group_limit') ? undefined : json['group_limit'],
        'keywords': !exists(json, 'keywords') ? undefined : json['keywords'],
        'over18': !exists(json, 'over18') ? undefined : json['over18'],
        'page': !exists(json, 'page') ? undefined : json['page'],
        'resultsPerPage': !exists(json, 'results_per_page') ? undefined : json['results_per_page'],
        'sort': !exists(json, 'sort') ? undefined : json['sort'],
        'statsFacet': !exists(json, 'stats_facet') ? undefined : json['stats_facet'],
        'statsField': !exists(json, 'stats_field') ? undefined : json['stats_field'],
    };
}

export function ItemSearchRequestToJSON(value?: ItemSearchRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'boost': value.boost,
        'can_validate_over18': value.canValidateOver18,
        'fqs': value.fqs === undefined ? undefined : ((value.fqs as Array<any>).map(FQRequestToJSON)),
        'group_field': value.groupField,
        'group_limit': value.groupLimit,
        'keywords': value.keywords,
        'over18': value.over18,
        'page': value.page,
        'results_per_page': value.resultsPerPage,
        'sort': value.sort,
        'stats_facet': value.statsFacet,
        'stats_field': value.statsField,
    };
}

