/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ItemId } from './ItemId';
import {
    ItemIdFromJSON,
    ItemIdFromJSONTyped,
    ItemIdToJSON,
} from './ItemId';

/**
 * 
 * @export
 * @interface ItemRequest
 */
export interface ItemRequest {
    /**
     * 
     * @type {ItemId}
     * @memberof ItemRequest
     */
    itemId: ItemId;
}

/**
 * Check if a given object implements the ItemRequest interface.
 */
export function instanceOfItemRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "itemId" in value;

    return isInstance;
}

export function ItemRequestFromJSON(json: any): ItemRequest {
    return ItemRequestFromJSONTyped(json, false);
}

export function ItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'itemId': ItemIdFromJSON(json['item_id']),
    };
}

export function ItemRequestToJSON(value?: ItemRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item_id': ItemIdToJSON(value.itemId),
    };
}

