/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VariantItem } from './VariantItem';
import {
    VariantItemFromJSON,
    VariantItemFromJSONTyped,
    VariantItemToJSON,
} from './VariantItem';

/**
 * 
 * @export
 * @interface ItemVariantsVariant
 */
export interface ItemVariantsVariant {
    /**
     * 
     * @type {VariantItem}
     * @memberof ItemVariantsVariant
     */
    item: VariantItem;
    /**
     * 
     * @type {Array<string>}
     * @memberof ItemVariantsVariant
     */
    values: Array<string>;
}

/**
 * Check if a given object implements the ItemVariantsVariant interface.
 */
export function instanceOfItemVariantsVariant(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "item" in value;
    isInstance = isInstance && "values" in value;

    return isInstance;
}

export function ItemVariantsVariantFromJSON(json: any): ItemVariantsVariant {
    return ItemVariantsVariantFromJSONTyped(json, false);
}

export function ItemVariantsVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemVariantsVariant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'item': VariantItemFromJSON(json['item']),
        'values': json['values'],
    };
}

export function ItemVariantsVariantToJSON(value?: ItemVariantsVariant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item': VariantItemToJSON(value.item),
        'values': value.values,
    };
}

