/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemId
 */
export interface ItemId {
    /**
     * 
     * @type {string}
     * @memberof ItemId
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof ItemId
     */
    idType: number;
}

/**
 * Check if a given object implements the ItemId interface.
 */
export function instanceOfItemId(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "idType" in value;

    return isInstance;
}

export function ItemIdFromJSON(json: any): ItemId {
    return ItemIdFromJSONTyped(json, false);
}

export function ItemIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'idType': json['id_type'],
    };
}

export function ItemIdToJSON(value?: ItemId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'id_type': value.idType,
    };
}

