/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './Money';

/**
 * 
 * @export
 * @interface ItemWithPOv2InfoLastPurchase
 */
export interface ItemWithPOv2InfoLastPurchase {
    /**
     * 
     * @type {Money}
     * @memberof ItemWithPOv2InfoLastPurchase
     */
    cost: Money;
    /**
     * 
     * @type {Date}
     * @memberof ItemWithPOv2InfoLastPurchase
     */
    datetimeActivated: Date;
    /**
     * 
     * @type {number}
     * @memberof ItemWithPOv2InfoLastPurchase
     */
    purchaseOrderId: number;
    /**
     * 
     * @type {number}
     * @memberof ItemWithPOv2InfoLastPurchase
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof ItemWithPOv2InfoLastPurchase
     */
    supplier: string;
}

/**
 * Check if a given object implements the ItemWithPOv2InfoLastPurchase interface.
 */
export function instanceOfItemWithPOv2InfoLastPurchase(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cost" in value;
    isInstance = isInstance && "datetimeActivated" in value;
    isInstance = isInstance && "purchaseOrderId" in value;
    isInstance = isInstance && "quantity" in value;
    isInstance = isInstance && "supplier" in value;

    return isInstance;
}

export function ItemWithPOv2InfoLastPurchaseFromJSON(json: any): ItemWithPOv2InfoLastPurchase {
    return ItemWithPOv2InfoLastPurchaseFromJSONTyped(json, false);
}

export function ItemWithPOv2InfoLastPurchaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemWithPOv2InfoLastPurchase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cost': MoneyFromJSON(json['cost']),
        'datetimeActivated': (new Date(json['datetime_activated'])),
        'purchaseOrderId': json['purchase_order_id'],
        'quantity': json['quantity'],
        'supplier': json['supplier'],
    };
}

export function ItemWithPOv2InfoLastPurchaseToJSON(value?: ItemWithPOv2InfoLastPurchase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cost': MoneyToJSON(value.cost),
        'datetime_activated': (value.datetimeActivated.toISOString()),
        'purchase_order_id': value.purchaseOrderId,
        'quantity': value.quantity,
        'supplier': value.supplier,
    };
}

