/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Item } from './Item';
import {
    ItemFromJSON,
    ItemFromJSONTyped,
    ItemToJSON,
} from './Item';

/**
 * 
 * @export
 * @interface ItemResponse
 */
export interface ItemResponse {
    /**
     * 
     * @type {Item}
     * @memberof ItemResponse
     */
    item: Item;
}

/**
 * Check if a given object implements the ItemResponse interface.
 */
export function instanceOfItemResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "item" in value;

    return isInstance;
}

export function ItemResponseFromJSON(json: any): ItemResponse {
    return ItemResponseFromJSONTyped(json, false);
}

export function ItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'item': ItemFromJSON(json['item']),
    };
}

export function ItemResponseToJSON(value?: ItemResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item': ItemToJSON(value.item),
    };
}

