/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemAttributeGroupValue
 */
export interface ItemAttributeGroupValue {
    /**
     * 
     * @type {string}
     * @memberof ItemAttributeGroupValue
     */
    facet?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemAttributeGroupValue
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ItemAttributeGroupValue
     */
    value: string;
}

/**
 * Check if a given object implements the ItemAttributeGroupValue interface.
 */
export function instanceOfItemAttributeGroupValue(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function ItemAttributeGroupValueFromJSON(json: any): ItemAttributeGroupValue {
    return ItemAttributeGroupValueFromJSONTyped(json, false);
}

export function ItemAttributeGroupValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemAttributeGroupValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'facet': !exists(json, 'facet') ? undefined : json['facet'],
        'name': json['name'],
        'value': json['value'],
    };
}

export function ItemAttributeGroupValueToJSON(value?: ItemAttributeGroupValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'facet': value.facet,
        'name': value.name,
        'value': value.value,
    };
}

