/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ItemAttributeGroupValue } from './ItemAttributeGroupValue';
import {
    ItemAttributeGroupValueFromJSON,
    ItemAttributeGroupValueFromJSONTyped,
    ItemAttributeGroupValueToJSON,
} from './ItemAttributeGroupValue';

/**
 * 
 * @export
 * @interface ItemAttributeGroup
 */
export interface ItemAttributeGroup {
    /**
     * 
     * @type {Array<ItemAttributeGroupValue>}
     * @memberof ItemAttributeGroup
     */
    attributes: Array<ItemAttributeGroupValue>;
    /**
     * 
     * @type {string}
     * @memberof ItemAttributeGroup
     */
    name: string;
}

/**
 * Check if a given object implements the ItemAttributeGroup interface.
 */
export function instanceOfItemAttributeGroup(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ItemAttributeGroupFromJSON(json: any): ItemAttributeGroup {
    return ItemAttributeGroupFromJSONTyped(json, false);
}

export function ItemAttributeGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemAttributeGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributes': ((json['attributes'] as Array<any>).map(ItemAttributeGroupValueFromJSON)),
        'name': json['name'],
    };
}

export function ItemAttributeGroupToJSON(value?: ItemAttributeGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributes': ((value.attributes as Array<any>).map(ItemAttributeGroupValueToJSON)),
        'name': value.name,
    };
}

