/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Dimensions } from './Dimensions';
import {
    DimensionsFromJSON,
    DimensionsFromJSONTyped,
    DimensionsToJSON,
} from './Dimensions';
import type { ImageMetadata } from './ImageMetadata';
import {
    ImageMetadataFromJSON,
    ImageMetadataFromJSONTyped,
    ImageMetadataToJSON,
} from './ImageMetadata';
import type { ItemAttributeGroup } from './ItemAttributeGroup';
import {
    ItemAttributeGroupFromJSON,
    ItemAttributeGroupFromJSONTyped,
    ItemAttributeGroupToJSON,
} from './ItemAttributeGroup';
import type { ItemCategory } from './ItemCategory';
import {
    ItemCategoryFromJSON,
    ItemCategoryFromJSONTyped,
    ItemCategoryToJSON,
} from './ItemCategory';
import type { ItemId } from './ItemId';
import {
    ItemIdFromJSON,
    ItemIdFromJSONTyped,
    ItemIdToJSON,
} from './ItemId';
import type { ItemRating } from './ItemRating';
import {
    ItemRatingFromJSON,
    ItemRatingFromJSONTyped,
    ItemRatingToJSON,
} from './ItemRating';
import type { ItemVariants } from './ItemVariants';
import {
    ItemVariantsFromJSON,
    ItemVariantsFromJSONTyped,
    ItemVariantsToJSON,
} from './ItemVariants';
import type { MerchantItemOffer } from './MerchantItemOffer';
import {
    MerchantItemOfferFromJSON,
    MerchantItemOfferFromJSONTyped,
    MerchantItemOfferToJSON,
} from './MerchantItemOffer';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './Money';
import type { SimilarItem } from './SimilarItem';
import {
    SimilarItemFromJSON,
    SimilarItemFromJSONTyped,
    SimilarItemToJSON,
} from './SimilarItem';

/**
 * 
 * @export
 * @interface ItemWithPriceAdjusterInfo
 */
export interface ItemWithPriceAdjusterInfo {
    /**
     * 
     * @type {Array<ItemAttributeGroup>}
     * @memberof ItemWithPriceAdjusterInfo
     */
    attributeGroups?: Array<ItemAttributeGroup>;
    /**
     * 
     * @type {string}
     * @memberof ItemWithPriceAdjusterInfo
     */
    brand?: string;
    /**
     * 
     * @type {Array<ItemCategory>}
     * @memberof ItemWithPriceAdjusterInfo
     */
    category?: Array<ItemCategory>;
    /**
     * 
     * @type {string}
     * @memberof ItemWithPriceAdjusterInfo
     */
    currentMarkup?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemWithPriceAdjusterInfo
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemWithPriceAdjusterInfo
     */
    expirationDate?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ItemWithPriceAdjusterInfo
     */
    hasExpirationDate?: boolean;
    /**
     * 
     * @type {Array<ItemId>}
     * @memberof ItemWithPriceAdjusterInfo
     */
    ids?: Array<ItemId>;
    /**
     * 
     * @type {Array<ImageMetadata>}
     * @memberof ItemWithPriceAdjusterInfo
     */
    images?: Array<ImageMetadata>;
    /**
     * 
     * @type {string}
     * @memberof ItemWithPriceAdjusterInfo
     */
    internalCode?: string;
    /**
     * 
     * @type {Dimensions}
     * @memberof ItemWithPriceAdjusterInfo
     */
    masterBoxDimensions?: Dimensions;
    /**
     * 
     * @type {Array<MerchantItemOffer>}
     * @memberof ItemWithPriceAdjusterInfo
     */
    offers?: Array<MerchantItemOffer>;
    /**
     * 
     * @type {Dimensions}
     * @memberof ItemWithPriceAdjusterInfo
     */
    packageDimensions?: Dimensions;
    /**
     * 
     * @type {string}
     * @memberof ItemWithPriceAdjusterInfo
     */
    plaBrand?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemWithPriceAdjusterInfo
     */
    plaCategory?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemWithPriceAdjusterInfo
     */
    plaItem?: string;
    /**
     * 
     * @type {Money}
     * @memberof ItemWithPriceAdjusterInfo
     */
    purchaseCost?: Money;
    /**
     * 
     * @type {ItemRating}
     * @memberof ItemWithPriceAdjusterInfo
     */
    rating?: ItemRating;
    /**
     * 
     * @type {Array<string>}
     * @memberof ItemWithPriceAdjusterInfo
     */
    searchTerms?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ItemWithPriceAdjusterInfo
     */
    serialNumberTracking?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ItemWithPriceAdjusterInfo
     */
    shareLink?: string;
    /**
     * 
     * @type {Array<SimilarItem>}
     * @memberof ItemWithPriceAdjusterInfo
     */
    similars?: Array<SimilarItem>;
    /**
     * 
     * @type {string}
     * @memberof ItemWithPriceAdjusterInfo
     */
    sourceId: string;
    /**
     * 
     * @type {string}
     * @memberof ItemWithPriceAdjusterInfo
     */
    title?: string;
    /**
     * 
     * @type {Dimensions}
     * @memberof ItemWithPriceAdjusterInfo
     */
    unitDimensions?: Dimensions;
    /**
     * 
     * @type {ItemVariants}
     * @memberof ItemWithPriceAdjusterInfo
     */
    variants?: ItemVariants;
    /**
     * 
     * @type {string}
     * @memberof ItemWithPriceAdjusterInfo
     */
    vat?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ItemWithPriceAdjusterInfo
     */
    youtubeVideos?: Array<string>;
}

/**
 * Check if a given object implements the ItemWithPriceAdjusterInfo interface.
 */
export function instanceOfItemWithPriceAdjusterInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sourceId" in value;

    return isInstance;
}

export function ItemWithPriceAdjusterInfoFromJSON(json: any): ItemWithPriceAdjusterInfo {
    return ItemWithPriceAdjusterInfoFromJSONTyped(json, false);
}

export function ItemWithPriceAdjusterInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemWithPriceAdjusterInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributeGroups': !exists(json, 'attribute_groups') ? undefined : ((json['attribute_groups'] as Array<any>).map(ItemAttributeGroupFromJSON)),
        'brand': !exists(json, 'brand') ? undefined : json['brand'],
        'category': !exists(json, 'category') ? undefined : ((json['category'] as Array<any>).map(ItemCategoryFromJSON)),
        'currentMarkup': !exists(json, 'current_markup') ? undefined : json['current_markup'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'expirationDate': !exists(json, 'expiration_date') ? undefined : json['expiration_date'],
        'hasExpirationDate': !exists(json, 'has_expiration_date') ? undefined : json['has_expiration_date'],
        'ids': !exists(json, 'ids') ? undefined : ((json['ids'] as Array<any>).map(ItemIdFromJSON)),
        'images': !exists(json, 'images') ? undefined : ((json['images'] as Array<any>).map(ImageMetadataFromJSON)),
        'internalCode': !exists(json, 'internal_code') ? undefined : json['internal_code'],
        'masterBoxDimensions': !exists(json, 'master_box_dimensions') ? undefined : DimensionsFromJSON(json['master_box_dimensions']),
        'offers': !exists(json, 'offers') ? undefined : ((json['offers'] as Array<any>).map(MerchantItemOfferFromJSON)),
        'packageDimensions': !exists(json, 'package_dimensions') ? undefined : DimensionsFromJSON(json['package_dimensions']),
        'plaBrand': !exists(json, 'pla_brand') ? undefined : json['pla_brand'],
        'plaCategory': !exists(json, 'pla_category') ? undefined : json['pla_category'],
        'plaItem': !exists(json, 'pla_item') ? undefined : json['pla_item'],
        'purchaseCost': !exists(json, 'purchase_cost') ? undefined : MoneyFromJSON(json['purchase_cost']),
        'rating': !exists(json, 'rating') ? undefined : ItemRatingFromJSON(json['rating']),
        'searchTerms': !exists(json, 'search_terms') ? undefined : json['search_terms'],
        'serialNumberTracking': !exists(json, 'serial_number_tracking') ? undefined : json['serial_number_tracking'],
        'shareLink': !exists(json, 'share_link') ? undefined : json['share_link'],
        'similars': !exists(json, 'similars') ? undefined : ((json['similars'] as Array<any>).map(SimilarItemFromJSON)),
        'sourceId': json['source_id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'unitDimensions': !exists(json, 'unit_dimensions') ? undefined : DimensionsFromJSON(json['unit_dimensions']),
        'variants': !exists(json, 'variants') ? undefined : ItemVariantsFromJSON(json['variants']),
        'vat': !exists(json, 'vat') ? undefined : json['vat'],
        'youtubeVideos': !exists(json, 'youtube_videos') ? undefined : json['youtube_videos'],
    };
}

export function ItemWithPriceAdjusterInfoToJSON(value?: ItemWithPriceAdjusterInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attribute_groups': value.attributeGroups === undefined ? undefined : ((value.attributeGroups as Array<any>).map(ItemAttributeGroupToJSON)),
        'brand': value.brand,
        'category': value.category === undefined ? undefined : ((value.category as Array<any>).map(ItemCategoryToJSON)),
        'current_markup': value.currentMarkup,
        'description': value.description,
        'expiration_date': value.expirationDate,
        'has_expiration_date': value.hasExpirationDate,
        'ids': value.ids === undefined ? undefined : ((value.ids as Array<any>).map(ItemIdToJSON)),
        'images': value.images === undefined ? undefined : ((value.images as Array<any>).map(ImageMetadataToJSON)),
        'internal_code': value.internalCode,
        'master_box_dimensions': DimensionsToJSON(value.masterBoxDimensions),
        'offers': value.offers === undefined ? undefined : ((value.offers as Array<any>).map(MerchantItemOfferToJSON)),
        'package_dimensions': DimensionsToJSON(value.packageDimensions),
        'pla_brand': value.plaBrand,
        'pla_category': value.plaCategory,
        'pla_item': value.plaItem,
        'purchase_cost': MoneyToJSON(value.purchaseCost),
        'rating': ItemRatingToJSON(value.rating),
        'search_terms': value.searchTerms,
        'serial_number_tracking': value.serialNumberTracking,
        'share_link': value.shareLink,
        'similars': value.similars === undefined ? undefined : ((value.similars as Array<any>).map(SimilarItemToJSON)),
        'source_id': value.sourceId,
        'title': value.title,
        'unit_dimensions': DimensionsToJSON(value.unitDimensions),
        'variants': ItemVariantsToJSON(value.variants),
        'vat': value.vat,
        'youtube_videos': value.youtubeVideos,
    };
}

