/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LinePaymentMethod } from './LinePaymentMethod';
import {
    LinePaymentMethodFromJSON,
    LinePaymentMethodFromJSONTyped,
    LinePaymentMethodToJSON,
} from './LinePaymentMethod';

/**
 * 
 * @export
 * @interface LinePaymentMethodsResponse
 */
export interface LinePaymentMethodsResponse {
    /**
     * 
     * @type {Array<LinePaymentMethod>}
     * @memberof LinePaymentMethodsResponse
     */
    methods: Array<LinePaymentMethod>;
}

/**
 * Check if a given object implements the LinePaymentMethodsResponse interface.
 */
export function instanceOfLinePaymentMethodsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "methods" in value;

    return isInstance;
}

export function LinePaymentMethodsResponseFromJSON(json: any): LinePaymentMethodsResponse {
    return LinePaymentMethodsResponseFromJSONTyped(json, false);
}

export function LinePaymentMethodsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinePaymentMethodsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'methods': ((json['methods'] as Array<any>).map(LinePaymentMethodFromJSON)),
    };
}

export function LinePaymentMethodsResponseToJSON(value?: LinePaymentMethodsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'methods': ((value.methods as Array<any>).map(LinePaymentMethodToJSON)),
    };
}

