/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LineIdentification } from './LineIdentification';
import {
    LineIdentificationFromJSON,
    LineIdentificationFromJSONTyped,
    LineIdentificationToJSON,
} from './LineIdentification';

/**
 * 
 * @export
 * @interface LineCardDataCardHolder
 */
export interface LineCardDataCardHolder {
    /**
     * 
     * @type {LineIdentification}
     * @memberof LineCardDataCardHolder
     */
    identification: LineIdentification;
    /**
     * 
     * @type {string}
     * @memberof LineCardDataCardHolder
     */
    name: string;
}

/**
 * Check if a given object implements the LineCardDataCardHolder interface.
 */
export function instanceOfLineCardDataCardHolder(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "identification" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function LineCardDataCardHolderFromJSON(json: any): LineCardDataCardHolder {
    return LineCardDataCardHolderFromJSONTyped(json, false);
}

export function LineCardDataCardHolderFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineCardDataCardHolder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identification': LineIdentificationFromJSON(json['identification']),
        'name': json['name'],
    };
}

export function LineCardDataCardHolderToJSON(value?: LineCardDataCardHolder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identification': LineIdentificationToJSON(value.identification),
        'name': value.name,
    };
}

