/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinePaymentMethodsRequest
 */
export interface LinePaymentMethodsRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof LinePaymentMethodsRequest
     */
    items?: Array<number>;
}

/**
 * Check if a given object implements the LinePaymentMethodsRequest interface.
 */
export function instanceOfLinePaymentMethodsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LinePaymentMethodsRequestFromJSON(json: any): LinePaymentMethodsRequest {
    return LinePaymentMethodsRequestFromJSONTyped(json, false);
}

export function LinePaymentMethodsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinePaymentMethodsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : json['items'],
    };
}

export function LinePaymentMethodsRequestToJSON(value?: LinePaymentMethodsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items,
    };
}

