/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LineCardData } from './LineCardData';
import {
    LineCardDataFromJSON,
    LineCardDataFromJSONTyped,
    LineCardDataToJSON,
} from './LineCardData';
import type { LineCardToken } from './LineCardToken';
import {
    LineCardTokenFromJSON,
    LineCardTokenFromJSONTyped,
    LineCardTokenToJSON,
} from './LineCardToken';

/**
 * 
 * @export
 * @interface LineCard
 */
export interface LineCard {
    /**
     * 
     * @type {LineCardData}
     * @memberof LineCard
     */
    cardData?: LineCardData;
    /**
     * 
     * @type {LineCardToken}
     * @memberof LineCard
     */
    cardDataToken?: LineCardToken;
    /**
     * 
     * @type {number}
     * @memberof LineCard
     */
    installments: number;
    /**
     * 
     * @type {boolean}
     * @memberof LineCard
     */
    saveCc: boolean;
}

/**
 * Check if a given object implements the LineCard interface.
 */
export function instanceOfLineCard(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "installments" in value;
    isInstance = isInstance && "saveCc" in value;

    return isInstance;
}

export function LineCardFromJSON(json: any): LineCard {
    return LineCardFromJSONTyped(json, false);
}

export function LineCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineCard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cardData': !exists(json, 'card_data') ? undefined : LineCardDataFromJSON(json['card_data']),
        'cardDataToken': !exists(json, 'card_data_token') ? undefined : LineCardTokenFromJSON(json['card_data_token']),
        'installments': json['installments'],
        'saveCc': json['save_cc'],
    };
}

export function LineCardToJSON(value?: LineCard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'card_data': LineCardDataToJSON(value.cardData),
        'card_data_token': LineCardTokenToJSON(value.cardDataToken),
        'installments': value.installments,
        'save_cc': value.saveCc,
    };
}

