/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LineCreatePaymentResponse
 */
export interface LineCreatePaymentResponse {
    /**
     * 
     * @type {number}
     * @memberof LineCreatePaymentResponse
     */
    orderId: number;
    /**
     * 
     * @type {string}
     * @memberof LineCreatePaymentResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof LineCreatePaymentResponse
     */
    statusDetail: string;
}

/**
 * Check if a given object implements the LineCreatePaymentResponse interface.
 */
export function instanceOfLineCreatePaymentResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "orderId" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "statusDetail" in value;

    return isInstance;
}

export function LineCreatePaymentResponseFromJSON(json: any): LineCreatePaymentResponse {
    return LineCreatePaymentResponseFromJSONTyped(json, false);
}

export function LineCreatePaymentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineCreatePaymentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderId': json['order_id'],
        'status': json['status'],
        'statusDetail': json['status_detail'],
    };
}

export function LineCreatePaymentResponseToJSON(value?: LineCreatePaymentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order_id': value.orderId,
        'status': value.status,
        'status_detail': value.statusDetail,
    };
}

