/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LineCardToken
 */
export interface LineCardToken {
    /**
     * 
     * @type {string}
     * @memberof LineCardToken
     */
    cardId: string;
    /**
     * 
     * @type {string}
     * @memberof LineCardToken
     */
    token: string;
}

/**
 * Check if a given object implements the LineCardToken interface.
 */
export function instanceOfLineCardToken(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cardId" in value;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function LineCardTokenFromJSON(json: any): LineCardToken {
    return LineCardTokenFromJSONTyped(json, false);
}

export function LineCardTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineCardToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cardId': json['card_id'],
        'token': json['token'],
    };
}

export function LineCardTokenToJSON(value?: LineCardToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'card_id': value.cardId,
        'token': value.token,
    };
}

