/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CartItem } from './CartItem';
import {
    CartItemFromJSON,
    CartItemFromJSONTyped,
    CartItemToJSON,
} from './CartItem';
import type { LineCardData } from './LineCardData';
import {
    LineCardDataFromJSON,
    LineCardDataFromJSONTyped,
    LineCardDataToJSON,
} from './LineCardData';
import type { LineCardToken } from './LineCardToken';
import {
    LineCardTokenFromJSON,
    LineCardTokenFromJSONTyped,
    LineCardTokenToJSON,
} from './LineCardToken';
import type { SalesOrderDeliveryTime } from './SalesOrderDeliveryTime';
import {
    SalesOrderDeliveryTimeFromJSON,
    SalesOrderDeliveryTimeFromJSONTyped,
    SalesOrderDeliveryTimeToJSON,
} from './SalesOrderDeliveryTime';

/**
 * 
 * @export
 * @interface LineCreatePaymentRequest
 */
export interface LineCreatePaymentRequest {
    /**
     * 
     * @type {number}
     * @memberof LineCreatePaymentRequest
     */
    addressId: number;
    /**
     * 
     * @type {LineCardData}
     * @memberof LineCreatePaymentRequest
     */
    cardData?: LineCardData;
    /**
     * 
     * @type {LineCardToken}
     * @memberof LineCreatePaymentRequest
     */
    cardDataToken?: LineCardToken;
    /**
     * 
     * @type {string}
     * @memberof LineCreatePaymentRequest
     */
    couponCode?: string;
    /**
     * 
     * @type {SalesOrderDeliveryTime}
     * @memberof LineCreatePaymentRequest
     */
    etd?: SalesOrderDeliveryTime;
    /**
     * 
     * @type {number}
     * @memberof LineCreatePaymentRequest
     */
    installments: number;
    /**
     * 
     * @type {Array<CartItem>}
     * @memberof LineCreatePaymentRequest
     */
    items: Array<CartItem>;
    /**
     * 
     * @type {string}
     * @memberof LineCreatePaymentRequest
     */
    notes?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LineCreatePaymentRequest
     */
    saveCc: boolean;
    /**
     * 
     * @type {string}
     * @memberof LineCreatePaymentRequest
     */
    shippingService?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LineCreatePaymentRequest
     */
    useBalance?: boolean;
}

/**
 * Check if a given object implements the LineCreatePaymentRequest interface.
 */
export function instanceOfLineCreatePaymentRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "addressId" in value;
    isInstance = isInstance && "installments" in value;
    isInstance = isInstance && "items" in value;
    isInstance = isInstance && "saveCc" in value;

    return isInstance;
}

export function LineCreatePaymentRequestFromJSON(json: any): LineCreatePaymentRequest {
    return LineCreatePaymentRequestFromJSONTyped(json, false);
}

export function LineCreatePaymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineCreatePaymentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addressId': json['address_id'],
        'cardData': !exists(json, 'card_data') ? undefined : LineCardDataFromJSON(json['card_data']),
        'cardDataToken': !exists(json, 'card_data_token') ? undefined : LineCardTokenFromJSON(json['card_data_token']),
        'couponCode': !exists(json, 'coupon_code') ? undefined : json['coupon_code'],
        'etd': !exists(json, 'etd') ? undefined : SalesOrderDeliveryTimeFromJSON(json['etd']),
        'installments': json['installments'],
        'items': ((json['items'] as Array<any>).map(CartItemFromJSON)),
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'saveCc': json['save_cc'],
        'shippingService': !exists(json, 'shipping_service') ? undefined : json['shipping_service'],
        'useBalance': !exists(json, 'use_balance') ? undefined : json['use_balance'],
    };
}

export function LineCreatePaymentRequestToJSON(value?: LineCreatePaymentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address_id': value.addressId,
        'card_data': LineCardDataToJSON(value.cardData),
        'card_data_token': LineCardTokenToJSON(value.cardDataToken),
        'coupon_code': value.couponCode,
        'etd': SalesOrderDeliveryTimeToJSON(value.etd),
        'installments': value.installments,
        'items': ((value.items as Array<any>).map(CartItemToJSON)),
        'notes': value.notes,
        'save_cc': value.saveCc,
        'shipping_service': value.shippingService,
        'use_balance': value.useBalance,
    };
}

