/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LineCardDataCardHolder } from './LineCardDataCardHolder';
import {
    LineCardDataCardHolderFromJSON,
    LineCardDataCardHolderFromJSONTyped,
    LineCardDataCardHolderToJSON,
} from './LineCardDataCardHolder';
import type { LinePaymentMethod } from './LinePaymentMethod';
import {
    LinePaymentMethodFromJSON,
    LinePaymentMethodFromJSONTyped,
    LinePaymentMethodToJSON,
} from './LinePaymentMethod';

/**
 * 
 * @export
 * @interface LineCardData
 */
export interface LineCardData {
    /**
     * 
     * @type {string}
     * @memberof LineCardData
     */
    cardNumber: string;
    /**
     * 
     * @type {LineCardDataCardHolder}
     * @memberof LineCardData
     */
    cardholder: LineCardDataCardHolder;
    /**
     * 
     * @type {LinePaymentMethod}
     * @memberof LineCardData
     */
    emiter: LinePaymentMethod;
    /**
     * 
     * @type {string}
     * @memberof LineCardData
     */
    expirationMonth: string;
    /**
     * 
     * @type {string}
     * @memberof LineCardData
     */
    expirationYear: string;
    /**
     * 
     * @type {string}
     * @memberof LineCardData
     */
    securityCode: string;
}

/**
 * Check if a given object implements the LineCardData interface.
 */
export function instanceOfLineCardData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cardNumber" in value;
    isInstance = isInstance && "cardholder" in value;
    isInstance = isInstance && "emiter" in value;
    isInstance = isInstance && "expirationMonth" in value;
    isInstance = isInstance && "expirationYear" in value;
    isInstance = isInstance && "securityCode" in value;

    return isInstance;
}

export function LineCardDataFromJSON(json: any): LineCardData {
    return LineCardDataFromJSONTyped(json, false);
}

export function LineCardDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineCardData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cardNumber': json['card_number'],
        'cardholder': LineCardDataCardHolderFromJSON(json['cardholder']),
        'emiter': LinePaymentMethodFromJSON(json['emiter']),
        'expirationMonth': json['expiration_month'],
        'expirationYear': json['expiration_year'],
        'securityCode': json['security_code'],
    };
}

export function LineCardDataToJSON(value?: LineCardData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'card_number': value.cardNumber,
        'cardholder': LineCardDataCardHolderToJSON(value.cardholder),
        'emiter': LinePaymentMethodToJSON(value.emiter),
        'expiration_month': value.expirationMonth,
        'expiration_year': value.expirationYear,
        'security_code': value.securityCode,
    };
}

