/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MercadoPagoAuthorization
 */
export interface MercadoPagoAuthorization {
    /**
     * 
     * @type {number}
     * @memberof MercadoPagoAuthorization
     */
    installments: number;
    /**
     * 
     * @type {number}
     * @memberof MercadoPagoAuthorization
     */
    issuerId?: number;
    /**
     * 
     * @type {string}
     * @memberof MercadoPagoAuthorization
     */
    paymentMethodId: string;
    /**
     * 
     * @type {boolean}
     * @memberof MercadoPagoAuthorization
     */
    saveCc: boolean;
    /**
     * 
     * @type {string}
     * @memberof MercadoPagoAuthorization
     */
    token: string;
}

/**
 * Check if a given object implements the MercadoPagoAuthorization interface.
 */
export function instanceOfMercadoPagoAuthorization(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "installments" in value;
    isInstance = isInstance && "paymentMethodId" in value;
    isInstance = isInstance && "saveCc" in value;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function MercadoPagoAuthorizationFromJSON(json: any): MercadoPagoAuthorization {
    return MercadoPagoAuthorizationFromJSONTyped(json, false);
}

export function MercadoPagoAuthorizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MercadoPagoAuthorization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'installments': json['installments'],
        'issuerId': !exists(json, 'issuer_id') ? undefined : json['issuer_id'],
        'paymentMethodId': json['payment_method_id'],
        'saveCc': json['save_cc'],
        'token': json['token'],
    };
}

export function MercadoPagoAuthorizationToJSON(value?: MercadoPagoAuthorization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'installments': value.installments,
        'issuer_id': value.issuerId,
        'payment_method_id': value.paymentMethodId,
        'save_cc': value.saveCc,
        'token': value.token,
    };
}

