/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MercadoPagoCCTokensResponseCardCardHolder } from './MercadoPagoCCTokensResponseCardCardHolder';
import {
    MercadoPagoCCTokensResponseCardCardHolderFromJSON,
    MercadoPagoCCTokensResponseCardCardHolderFromJSONTyped,
    MercadoPagoCCTokensResponseCardCardHolderToJSON,
} from './MercadoPagoCCTokensResponseCardCardHolder';
import type { MercadoPagoCCTokensResponseCardIssuer } from './MercadoPagoCCTokensResponseCardIssuer';
import {
    MercadoPagoCCTokensResponseCardIssuerFromJSON,
    MercadoPagoCCTokensResponseCardIssuerFromJSONTyped,
    MercadoPagoCCTokensResponseCardIssuerToJSON,
} from './MercadoPagoCCTokensResponseCardIssuer';
import type { MercadoPagoCCTokensResponseCardPaymentMethod } from './MercadoPagoCCTokensResponseCardPaymentMethod';
import {
    MercadoPagoCCTokensResponseCardPaymentMethodFromJSON,
    MercadoPagoCCTokensResponseCardPaymentMethodFromJSONTyped,
    MercadoPagoCCTokensResponseCardPaymentMethodToJSON,
} from './MercadoPagoCCTokensResponseCardPaymentMethod';
import type { MercadoPagoCCTokensResponseCardSecurityCode } from './MercadoPagoCCTokensResponseCardSecurityCode';
import {
    MercadoPagoCCTokensResponseCardSecurityCodeFromJSON,
    MercadoPagoCCTokensResponseCardSecurityCodeFromJSONTyped,
    MercadoPagoCCTokensResponseCardSecurityCodeToJSON,
} from './MercadoPagoCCTokensResponseCardSecurityCode';

/**
 * 
 * @export
 * @interface MercadoPagoCCTokensResponseCard
 */
export interface MercadoPagoCCTokensResponseCard {
    /**
     * 
     * @type {string}
     * @memberof MercadoPagoCCTokensResponseCard
     */
    cardNumberId?: string;
    /**
     * 
     * @type {MercadoPagoCCTokensResponseCardCardHolder}
     * @memberof MercadoPagoCCTokensResponseCard
     */
    cardholder: MercadoPagoCCTokensResponseCardCardHolder;
    /**
     * 
     * @type {string}
     * @memberof MercadoPagoCCTokensResponseCard
     */
    customerId: string;
    /**
     * 
     * @type {string}
     * @memberof MercadoPagoCCTokensResponseCard
     */
    dateCreated: string;
    /**
     * 
     * @type {string}
     * @memberof MercadoPagoCCTokensResponseCard
     */
    dateLastUpdated?: string;
    /**
     * 
     * @type {number}
     * @memberof MercadoPagoCCTokensResponseCard
     */
    expirationMonth: number;
    /**
     * 
     * @type {number}
     * @memberof MercadoPagoCCTokensResponseCard
     */
    expirationYear: number;
    /**
     * 
     * @type {string}
     * @memberof MercadoPagoCCTokensResponseCard
     */
    firstSixDigits: string;
    /**
     * 
     * @type {string}
     * @memberof MercadoPagoCCTokensResponseCard
     */
    id: string;
    /**
     * 
     * @type {MercadoPagoCCTokensResponseCardIssuer}
     * @memberof MercadoPagoCCTokensResponseCard
     */
    issuer: MercadoPagoCCTokensResponseCardIssuer;
    /**
     * 
     * @type {string}
     * @memberof MercadoPagoCCTokensResponseCard
     */
    lastFourDigits: string;
    /**
     * 
     * @type {MercadoPagoCCTokensResponseCardPaymentMethod}
     * @memberof MercadoPagoCCTokensResponseCard
     */
    paymentMethod: MercadoPagoCCTokensResponseCardPaymentMethod;
    /**
     * 
     * @type {MercadoPagoCCTokensResponseCardSecurityCode}
     * @memberof MercadoPagoCCTokensResponseCard
     */
    securityCode: MercadoPagoCCTokensResponseCardSecurityCode;
    /**
     * 
     * @type {string}
     * @memberof MercadoPagoCCTokensResponseCard
     */
    userId: string;
}

/**
 * Check if a given object implements the MercadoPagoCCTokensResponseCard interface.
 */
export function instanceOfMercadoPagoCCTokensResponseCard(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cardholder" in value;
    isInstance = isInstance && "customerId" in value;
    isInstance = isInstance && "dateCreated" in value;
    isInstance = isInstance && "expirationMonth" in value;
    isInstance = isInstance && "expirationYear" in value;
    isInstance = isInstance && "firstSixDigits" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "issuer" in value;
    isInstance = isInstance && "lastFourDigits" in value;
    isInstance = isInstance && "paymentMethod" in value;
    isInstance = isInstance && "securityCode" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function MercadoPagoCCTokensResponseCardFromJSON(json: any): MercadoPagoCCTokensResponseCard {
    return MercadoPagoCCTokensResponseCardFromJSONTyped(json, false);
}

export function MercadoPagoCCTokensResponseCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): MercadoPagoCCTokensResponseCard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cardNumberId': !exists(json, 'card_number_id') ? undefined : json['card_number_id'],
        'cardholder': MercadoPagoCCTokensResponseCardCardHolderFromJSON(json['cardholder']),
        'customerId': json['customer_id'],
        'dateCreated': json['date_created'],
        'dateLastUpdated': !exists(json, 'date_last_updated') ? undefined : json['date_last_updated'],
        'expirationMonth': json['expiration_month'],
        'expirationYear': json['expiration_year'],
        'firstSixDigits': json['first_six_digits'],
        'id': json['id'],
        'issuer': MercadoPagoCCTokensResponseCardIssuerFromJSON(json['issuer']),
        'lastFourDigits': json['last_four_digits'],
        'paymentMethod': MercadoPagoCCTokensResponseCardPaymentMethodFromJSON(json['payment_method']),
        'securityCode': MercadoPagoCCTokensResponseCardSecurityCodeFromJSON(json['security_code']),
        'userId': json['user_id'],
    };
}

export function MercadoPagoCCTokensResponseCardToJSON(value?: MercadoPagoCCTokensResponseCard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'card_number_id': value.cardNumberId,
        'cardholder': MercadoPagoCCTokensResponseCardCardHolderToJSON(value.cardholder),
        'customer_id': value.customerId,
        'date_created': value.dateCreated,
        'date_last_updated': value.dateLastUpdated,
        'expiration_month': value.expirationMonth,
        'expiration_year': value.expirationYear,
        'first_six_digits': value.firstSixDigits,
        'id': value.id,
        'issuer': MercadoPagoCCTokensResponseCardIssuerToJSON(value.issuer),
        'last_four_digits': value.lastFourDigits,
        'payment_method': MercadoPagoCCTokensResponseCardPaymentMethodToJSON(value.paymentMethod),
        'security_code': MercadoPagoCCTokensResponseCardSecurityCodeToJSON(value.securityCode),
        'user_id': value.userId,
    };
}

