/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './Money';

/**
 * 
 * @export
 * @interface MerchantItemOfferComponent
 */
export interface MerchantItemOfferComponent {
    /**
     * 
     * @type {number}
     * @memberof MerchantItemOfferComponent
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof MerchantItemOfferComponent
     */
    sourceId: string;
    /**
     * 
     * @type {Money}
     * @memberof MerchantItemOfferComponent
     */
    total: Money;
}

/**
 * Check if a given object implements the MerchantItemOfferComponent interface.
 */
export function instanceOfMerchantItemOfferComponent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "quantity" in value;
    isInstance = isInstance && "sourceId" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function MerchantItemOfferComponentFromJSON(json: any): MerchantItemOfferComponent {
    return MerchantItemOfferComponentFromJSONTyped(json, false);
}

export function MerchantItemOfferComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchantItemOfferComponent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'quantity': json['quantity'],
        'sourceId': json['source_id'],
        'total': MoneyFromJSON(json['total']),
    };
}

export function MerchantItemOfferComponentToJSON(value?: MerchantItemOfferComponent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'quantity': value.quantity,
        'source_id': value.sourceId,
        'total': MoneyToJSON(value.total),
    };
}

