/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MercadoPagoCCTokensResponseCardSecurityCode
 */
export interface MercadoPagoCCTokensResponseCardSecurityCode {
    /**
     * 
     * @type {string}
     * @memberof MercadoPagoCCTokensResponseCardSecurityCode
     */
    cardLocation: string;
    /**
     * 
     * @type {number}
     * @memberof MercadoPagoCCTokensResponseCardSecurityCode
     */
    length: number;
}

/**
 * Check if a given object implements the MercadoPagoCCTokensResponseCardSecurityCode interface.
 */
export function instanceOfMercadoPagoCCTokensResponseCardSecurityCode(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cardLocation" in value;
    isInstance = isInstance && "length" in value;

    return isInstance;
}

export function MercadoPagoCCTokensResponseCardSecurityCodeFromJSON(json: any): MercadoPagoCCTokensResponseCardSecurityCode {
    return MercadoPagoCCTokensResponseCardSecurityCodeFromJSONTyped(json, false);
}

export function MercadoPagoCCTokensResponseCardSecurityCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MercadoPagoCCTokensResponseCardSecurityCode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cardLocation': json['card_location'],
        'length': json['length'],
    };
}

export function MercadoPagoCCTokensResponseCardSecurityCodeToJSON(value?: MercadoPagoCCTokensResponseCardSecurityCode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'card_location': value.cardLocation,
        'length': value.length,
    };
}

