/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MercadoPagoCCTokensResponseCardIssuer
 */
export interface MercadoPagoCCTokensResponseCardIssuer {
    /**
     * 
     * @type {number}
     * @memberof MercadoPagoCCTokensResponseCardIssuer
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof MercadoPagoCCTokensResponseCardIssuer
     */
    name: string;
}

/**
 * Check if a given object implements the MercadoPagoCCTokensResponseCardIssuer interface.
 */
export function instanceOfMercadoPagoCCTokensResponseCardIssuer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function MercadoPagoCCTokensResponseCardIssuerFromJSON(json: any): MercadoPagoCCTokensResponseCardIssuer {
    return MercadoPagoCCTokensResponseCardIssuerFromJSONTyped(json, false);
}

export function MercadoPagoCCTokensResponseCardIssuerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MercadoPagoCCTokensResponseCardIssuer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function MercadoPagoCCTokensResponseCardIssuerToJSON(value?: MercadoPagoCCTokensResponseCardIssuer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

