/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MercadoPagoCCTokensResponsePhone
 */
export interface MercadoPagoCCTokensResponsePhone {
    /**
     * 
     * @type {string}
     * @memberof MercadoPagoCCTokensResponsePhone
     */
    areaCode?: string;
    /**
     * 
     * @type {string}
     * @memberof MercadoPagoCCTokensResponsePhone
     */
    number?: string;
}

/**
 * Check if a given object implements the MercadoPagoCCTokensResponsePhone interface.
 */
export function instanceOfMercadoPagoCCTokensResponsePhone(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MercadoPagoCCTokensResponsePhoneFromJSON(json: any): MercadoPagoCCTokensResponsePhone {
    return MercadoPagoCCTokensResponsePhoneFromJSONTyped(json, false);
}

export function MercadoPagoCCTokensResponsePhoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): MercadoPagoCCTokensResponsePhone {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'areaCode': !exists(json, 'area_code') ? undefined : json['area_code'],
        'number': !exists(json, 'number') ? undefined : json['number'],
    };
}

export function MercadoPagoCCTokensResponsePhoneToJSON(value?: MercadoPagoCCTokensResponsePhone | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'area_code': value.areaCode,
        'number': value.number,
    };
}

