/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MobilCryptoProfileResponse
 */
export interface MobilCryptoProfileResponse {
    /**
     * 
     * @type {number}
     * @memberof MobilCryptoProfileResponse
     */
    cryptoProfileId: number;
    /**
     * 
     * @type {string}
     * @memberof MobilCryptoProfileResponse
     */
    processingStatus: MobilCryptoProfileResponseProcessingStatusEnum;
}


/**
 * @export
 */
export const MobilCryptoProfileResponseProcessingStatusEnum = {
    Processing: 'processing',
    Completed: 'completed',
    Cancelled: 'cancelled'
} as const;
export type MobilCryptoProfileResponseProcessingStatusEnum = typeof MobilCryptoProfileResponseProcessingStatusEnum[keyof typeof MobilCryptoProfileResponseProcessingStatusEnum];


/**
 * Check if a given object implements the MobilCryptoProfileResponse interface.
 */
export function instanceOfMobilCryptoProfileResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cryptoProfileId" in value;
    isInstance = isInstance && "processingStatus" in value;

    return isInstance;
}

export function MobilCryptoProfileResponseFromJSON(json: any): MobilCryptoProfileResponse {
    return MobilCryptoProfileResponseFromJSONTyped(json, false);
}

export function MobilCryptoProfileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MobilCryptoProfileResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cryptoProfileId': json['crypto_profile_id'],
        'processingStatus': json['processing_status'],
    };
}

export function MobilCryptoProfileResponseToJSON(value?: MobilCryptoProfileResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'crypto_profile_id': value.cryptoProfileId,
        'processing_status': value.processingStatus,
    };
}

