/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Coordinates } from './Coordinates';
import {
    CoordinatesFromJSON,
    CoordinatesFromJSONTyped,
    CoordinatesToJSON,
} from './Coordinates';

/**
 * 
 * @export
 * @interface OfflinePassportAuditRequest
 */
export interface OfflinePassportAuditRequest {
    /**
     * 
     * @type {Coordinates}
     * @memberof OfflinePassportAuditRequest
     */
    coordinates: Coordinates;
    /**
     * 
     * @type {string}
     * @memberof OfflinePassportAuditRequest
     */
    data: string;
}

/**
 * Check if a given object implements the OfflinePassportAuditRequest interface.
 */
export function instanceOfOfflinePassportAuditRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "coordinates" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function OfflinePassportAuditRequestFromJSON(json: any): OfflinePassportAuditRequest {
    return OfflinePassportAuditRequestFromJSONTyped(json, false);
}

export function OfflinePassportAuditRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfflinePassportAuditRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'coordinates': CoordinatesFromJSON(json['coordinates']),
        'data': json['data'],
    };
}

export function OfflinePassportAuditRequestToJSON(value?: OfflinePassportAuditRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'coordinates': CoordinatesToJSON(value.coordinates),
        'data': value.data,
    };
}

