/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PODocumentType
 */
export interface PODocumentType {
    /**
     * 
     * @type {string}
     * @memberof PODocumentType
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PODocumentType
     */
    name: string;
}

/**
 * Check if a given object implements the PODocumentType interface.
 */
export function instanceOfPODocumentType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function PODocumentTypeFromJSON(json: any): PODocumentType {
    return PODocumentTypeFromJSONTyped(json, false);
}

export function PODocumentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PODocumentType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
    };
}

export function PODocumentTypeToJSON(value?: PODocumentType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

