/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface POLoadDocumentRequestResponseMobil
 */
export interface POLoadDocumentRequestResponseMobil {
    /**
     * 
     * @type {number}
     * @memberof POLoadDocumentRequestResponseMobil
     */
    poId?: number;
}

/**
 * Check if a given object implements the POLoadDocumentRequestResponseMobil interface.
 */
export function instanceOfPOLoadDocumentRequestResponseMobil(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function POLoadDocumentRequestResponseMobilFromJSON(json: any): POLoadDocumentRequestResponseMobil {
    return POLoadDocumentRequestResponseMobilFromJSONTyped(json, false);
}

export function POLoadDocumentRequestResponseMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): POLoadDocumentRequestResponseMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'poId': !exists(json, 'po_id') ? undefined : json['po_id'],
    };
}

export function POLoadDocumentRequestResponseMobilToJSON(value?: POLoadDocumentRequestResponseMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'po_id': value.poId,
    };
}

