/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ImageMetadata } from './ImageMetadata';
import {
    ImageMetadataFromJSON,
    ImageMetadataFromJSONTyped,
    ImageMetadataToJSON,
} from './ImageMetadata';

/**
 * 
 * @export
 * @interface POPackingListItem
 */
export interface POPackingListItem {
    /**
     * 
     * @type {string}
     * @memberof POPackingListItem
     */
    brand: string;
    /**
     * 
     * @type {string}
     * @memberof POPackingListItem
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof POPackingListItem
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof POPackingListItem
     */
    id: number;
    /**
     * 
     * @type {Array<ImageMetadata>}
     * @memberof POPackingListItem
     */
    images?: Array<ImageMetadata>;
    /**
     * 
     * @type {number}
     * @memberof POPackingListItem
     */
    loaded: number;
    /**
     * 
     * @type {string}
     * @memberof POPackingListItem
     */
    longDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof POPackingListItem
     */
    mnfc: string;
    /**
     * 
     * @type {number}
     * @memberof POPackingListItem
     */
    quantity: number;
    /**
     * 
     * @type {boolean}
     * @memberof POPackingListItem
     */
    serialTracking?: boolean;
    /**
     * 
     * @type {string}
     * @memberof POPackingListItem
     */
    upc?: string;
}

/**
 * Check if a given object implements the POPackingListItem interface.
 */
export function instanceOfPOPackingListItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "brand" in value;
    isInstance = isInstance && "category" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "loaded" in value;
    isInstance = isInstance && "mnfc" in value;
    isInstance = isInstance && "quantity" in value;

    return isInstance;
}

export function POPackingListItemFromJSON(json: any): POPackingListItem {
    return POPackingListItemFromJSONTyped(json, false);
}

export function POPackingListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): POPackingListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'brand': json['brand'],
        'category': json['category'],
        'description': json['description'],
        'id': json['id'],
        'images': !exists(json, 'images') ? undefined : ((json['images'] as Array<any>).map(ImageMetadataFromJSON)),
        'loaded': json['loaded'],
        'longDescription': !exists(json, 'long_description') ? undefined : json['long_description'],
        'mnfc': json['mnfc'],
        'quantity': json['quantity'],
        'serialTracking': !exists(json, 'serial_tracking') ? undefined : json['serial_tracking'],
        'upc': !exists(json, 'upc') ? undefined : json['upc'],
    };
}

export function POPackingListItemToJSON(value?: POPackingListItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'brand': value.brand,
        'category': value.category,
        'description': value.description,
        'id': value.id,
        'images': value.images === undefined ? undefined : ((value.images as Array<any>).map(ImageMetadataToJSON)),
        'loaded': value.loaded,
        'long_description': value.longDescription,
        'mnfc': value.mnfc,
        'quantity': value.quantity,
        'serial_tracking': value.serialTracking,
        'upc': value.upc,
    };
}

