/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface POPLCheckinWOSerialRequestMobil
 */
export interface POPLCheckinWOSerialRequestMobil {
    /**
     * 
     * @type {number}
     * @memberof POPLCheckinWOSerialRequestMobil
     */
    poplitemId: number;
    /**
     * 
     * @type {string}
     * @memberof POPLCheckinWOSerialRequestMobil
     */
    zoneId?: string;
}

/**
 * Check if a given object implements the POPLCheckinWOSerialRequestMobil interface.
 */
export function instanceOfPOPLCheckinWOSerialRequestMobil(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "poplitemId" in value;

    return isInstance;
}

export function POPLCheckinWOSerialRequestMobilFromJSON(json: any): POPLCheckinWOSerialRequestMobil {
    return POPLCheckinWOSerialRequestMobilFromJSONTyped(json, false);
}

export function POPLCheckinWOSerialRequestMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): POPLCheckinWOSerialRequestMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'poplitemId': json['poplitem_id'],
        'zoneId': !exists(json, 'zone_id') ? undefined : json['zone_id'],
    };
}

export function POPLCheckinWOSerialRequestMobilToJSON(value?: POPLCheckinWOSerialRequestMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'poplitem_id': value.poplitemId,
        'zone_id': value.zoneId,
    };
}

