/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ItemId } from './ItemId';
import {
    ItemIdFromJSON,
    ItemIdFromJSONTyped,
    ItemIdToJSON,
} from './ItemId';

/**
 * 
 * @export
 * @interface POQuickCheckinRequest
 */
export interface POQuickCheckinRequest {
    /**
     * 
     * @type {string}
     * @memberof POQuickCheckinRequest
     */
    expirationDate?: string;
    /**
     * 
     * @type {ItemId}
     * @memberof POQuickCheckinRequest
     */
    itemId: ItemId;
    /**
     * 
     * @type {number}
     * @memberof POQuickCheckinRequest
     */
    poId: number;
    /**
     * 
     * @type {number}
     * @memberof POQuickCheckinRequest
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof POQuickCheckinRequest
     */
    targetZone: string;
}

/**
 * Check if a given object implements the POQuickCheckinRequest interface.
 */
export function instanceOfPOQuickCheckinRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "itemId" in value;
    isInstance = isInstance && "poId" in value;
    isInstance = isInstance && "quantity" in value;
    isInstance = isInstance && "targetZone" in value;

    return isInstance;
}

export function POQuickCheckinRequestFromJSON(json: any): POQuickCheckinRequest {
    return POQuickCheckinRequestFromJSONTyped(json, false);
}

export function POQuickCheckinRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): POQuickCheckinRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expirationDate': !exists(json, 'expiration_date') ? undefined : json['expiration_date'],
        'itemId': ItemIdFromJSON(json['item_id']),
        'poId': json['po_id'],
        'quantity': json['quantity'],
        'targetZone': json['target_zone'],
    };
}

export function POQuickCheckinRequestToJSON(value?: POQuickCheckinRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expiration_date': value.expirationDate,
        'item_id': ItemIdToJSON(value.itemId),
        'po_id': value.poId,
        'quantity': value.quantity,
        'target_zone': value.targetZone,
    };
}

