/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { POSSearchItemData } from './POSSearchItemData';
import {
    POSSearchItemDataFromJSON,
    POSSearchItemDataFromJSONTyped,
    POSSearchItemDataToJSON,
} from './POSSearchItemData';

/**
 * 
 * @export
 * @interface POSSearchItemDataResponse
 */
export interface POSSearchItemDataResponse {
    /**
     * 
     * @type {Array<POSSearchItemData>}
     * @memberof POSSearchItemDataResponse
     */
    results?: Array<POSSearchItemData>;
}

/**
 * Check if a given object implements the POSSearchItemDataResponse interface.
 */
export function instanceOfPOSSearchItemDataResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function POSSearchItemDataResponseFromJSON(json: any): POSSearchItemDataResponse {
    return POSSearchItemDataResponseFromJSONTyped(json, false);
}

export function POSSearchItemDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): POSSearchItemDataResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(POSSearchItemDataFromJSON)),
    };
}

export function POSSearchItemDataResponseToJSON(value?: POSSearchItemDataResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(POSSearchItemDataToJSON)),
    };
}

