/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface POv2Supplier
 */
export interface POv2Supplier {
    /**
     * 
     * @type {string}
     * @memberof POv2Supplier
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof POv2Supplier
     */
    supplierId: number;
}

/**
 * Check if a given object implements the POv2Supplier interface.
 */
export function instanceOfPOv2Supplier(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "supplierId" in value;

    return isInstance;
}

export function POv2SupplierFromJSON(json: any): POv2Supplier {
    return POv2SupplierFromJSONTyped(json, false);
}

export function POv2SupplierFromJSONTyped(json: any, ignoreDiscriminator: boolean): POv2Supplier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'supplierId': json['supplier_id'],
    };
}

export function POv2SupplierToJSON(value?: POv2Supplier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'supplier_id': value.supplierId,
    };
}

