/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface POZoneInformation
 */
export interface POZoneInformation {
    /**
     * 
     * @type {string}
     * @memberof POZoneInformation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof POZoneInformation
     */
    zone: string;
}

/**
 * Check if a given object implements the POZoneInformation interface.
 */
export function instanceOfPOZoneInformation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "zone" in value;

    return isInstance;
}

export function POZoneInformationFromJSON(json: any): POZoneInformation {
    return POZoneInformationFromJSONTyped(json, false);
}

export function POZoneInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): POZoneInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'zone': json['zone'],
    };
}

export function POZoneInformationToJSON(value?: POZoneInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'zone': value.zone,
    };
}

