/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GenericSOPackingListRequestMobil } from './GenericSOPackingListRequestMobil';
import {
    GenericSOPackingListRequestMobilFromJSON,
    GenericSOPackingListRequestMobilFromJSONTyped,
    GenericSOPackingListRequestMobilToJSON,
} from './GenericSOPackingListRequestMobil';

/**
 * 
 * @export
 * @interface PrepareShipmentRequestMobil
 */
export interface PrepareShipmentRequestMobil {
    /**
     * 
     * @type {number}
     * @memberof PrepareShipmentRequestMobil
     */
    packages: number;
    /**
     * 
     * @type {Array<GenericSOPackingListRequestMobil>}
     * @memberof PrepareShipmentRequestMobil
     */
    packingLists: Array<GenericSOPackingListRequestMobil>;
    /**
     * 
     * @type {number}
     * @memberof PrepareShipmentRequestMobil
     */
    salesOrderId: number;
}

/**
 * Check if a given object implements the PrepareShipmentRequestMobil interface.
 */
export function instanceOfPrepareShipmentRequestMobil(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "packages" in value;
    isInstance = isInstance && "packingLists" in value;
    isInstance = isInstance && "salesOrderId" in value;

    return isInstance;
}

export function PrepareShipmentRequestMobilFromJSON(json: any): PrepareShipmentRequestMobil {
    return PrepareShipmentRequestMobilFromJSONTyped(json, false);
}

export function PrepareShipmentRequestMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrepareShipmentRequestMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'packages': json['packages'],
        'packingLists': ((json['packing_lists'] as Array<any>).map(GenericSOPackingListRequestMobilFromJSON)),
        'salesOrderId': json['sales_order_id'],
    };
}

export function PrepareShipmentRequestMobilToJSON(value?: PrepareShipmentRequestMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'packages': value.packages,
        'packing_lists': ((value.packingLists as Array<any>).map(GenericSOPackingListRequestMobilToJSON)),
        'sales_order_id': value.salesOrderId,
    };
}

