/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GenericSOPackingListRequestMobil } from './GenericSOPackingListRequestMobil';
import {
    GenericSOPackingListRequestMobilFromJSON,
    GenericSOPackingListRequestMobilFromJSONTyped,
    GenericSOPackingListRequestMobilToJSON,
} from './GenericSOPackingListRequestMobil';
import type { QuickShipmentLabel } from './QuickShipmentLabel';
import {
    QuickShipmentLabelFromJSON,
    QuickShipmentLabelFromJSONTyped,
    QuickShipmentLabelToJSON,
} from './QuickShipmentLabel';

/**
 * 
 * @export
 * @interface PrepareShipmentResponseMobil
 */
export interface PrepareShipmentResponseMobil {
    /**
     * 
     * @type {Array<GenericSOPackingListRequestMobil>}
     * @memberof PrepareShipmentResponseMobil
     */
    preparedPackingLists: Array<GenericSOPackingListRequestMobil>;
    /**
     * 
     * @type {number}
     * @memberof PrepareShipmentResponseMobil
     */
    salesOrderId: number;
    /**
     * 
     * @type {number}
     * @memberof PrepareShipmentResponseMobil
     */
    shipmentId: number;
    /**
     * 
     * @type {QuickShipmentLabel}
     * @memberof PrepareShipmentResponseMobil
     */
    shipmentLabel?: QuickShipmentLabel;
}

/**
 * Check if a given object implements the PrepareShipmentResponseMobil interface.
 */
export function instanceOfPrepareShipmentResponseMobil(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "preparedPackingLists" in value;
    isInstance = isInstance && "salesOrderId" in value;
    isInstance = isInstance && "shipmentId" in value;

    return isInstance;
}

export function PrepareShipmentResponseMobilFromJSON(json: any): PrepareShipmentResponseMobil {
    return PrepareShipmentResponseMobilFromJSONTyped(json, false);
}

export function PrepareShipmentResponseMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrepareShipmentResponseMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'preparedPackingLists': ((json['prepared_packing_lists'] as Array<any>).map(GenericSOPackingListRequestMobilFromJSON)),
        'salesOrderId': json['sales_order_id'],
        'shipmentId': json['shipment_id'],
        'shipmentLabel': !exists(json, 'shipment_label') ? undefined : QuickShipmentLabelFromJSON(json['shipment_label']),
    };
}

export function PrepareShipmentResponseMobilToJSON(value?: PrepareShipmentResponseMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prepared_packing_lists': ((value.preparedPackingLists as Array<any>).map(GenericSOPackingListRequestMobilToJSON)),
        'sales_order_id': value.salesOrderId,
        'shipment_id': value.shipmentId,
        'shipment_label': QuickShipmentLabelToJSON(value.shipmentLabel),
    };
}

