/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './Money';

/**
 * 
 * @export
 * @interface PriceBreak
 */
export interface PriceBreak {
    /**
     * 
     * @type {string}
     * @memberof PriceBreak
     */
    key?: string;
    /**
     * 
     * @type {Money}
     * @memberof PriceBreak
     */
    price: Money;
    /**
     * 
     * @type {number}
     * @memberof PriceBreak
     */
    quantity: number;
}

/**
 * Check if a given object implements the PriceBreak interface.
 */
export function instanceOfPriceBreak(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "price" in value;
    isInstance = isInstance && "quantity" in value;

    return isInstance;
}

export function PriceBreakFromJSON(json: any): PriceBreak {
    return PriceBreakFromJSONTyped(json, false);
}

export function PriceBreakFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceBreak {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
        'price': MoneyFromJSON(json['price']),
        'quantity': json['quantity'],
    };
}

export function PriceBreakToJSON(value?: PriceBreak | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'price': MoneyToJSON(value.price),
        'quantity': value.quantity,
    };
}

