/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PurchaseOrderRequestMobil
 */
export interface PurchaseOrderRequestMobil {
    /**
     * 
     * @type {number}
     * @memberof PurchaseOrderRequestMobil
     */
    purchaseOrderId: number;
}

/**
 * Check if a given object implements the PurchaseOrderRequestMobil interface.
 */
export function instanceOfPurchaseOrderRequestMobil(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "purchaseOrderId" in value;

    return isInstance;
}

export function PurchaseOrderRequestMobilFromJSON(json: any): PurchaseOrderRequestMobil {
    return PurchaseOrderRequestMobilFromJSONTyped(json, false);
}

export function PurchaseOrderRequestMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchaseOrderRequestMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'purchaseOrderId': json['purchase_order_id'],
    };
}

export function PurchaseOrderRequestMobilToJSON(value?: PurchaseOrderRequestMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'purchase_order_id': value.purchaseOrderId,
    };
}

