/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuickShipmentLabel
 */
export interface QuickShipmentLabel {
    /**
     * 
     * @type {string}
     * @memberof QuickShipmentLabel
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof QuickShipmentLabel
     */
    customer: string;
    /**
     * 
     * @type {string}
     * @memberof QuickShipmentLabel
     */
    fromTime: string;
    /**
     * 
     * @type {string}
     * @memberof QuickShipmentLabel
     */
    order: string;
    /**
     * 
     * @type {number}
     * @memberof QuickShipmentLabel
     */
    _package: number;
    /**
     * 
     * @type {number}
     * @memberof QuickShipmentLabel
     */
    packages: number;
    /**
     * 
     * @type {string}
     * @memberof QuickShipmentLabel
     */
    phone?: string;
    /**
     * 
     * @type {number}
     * @memberof QuickShipmentLabel
     */
    shipmentId: number;
    /**
     * 
     * @type {string}
     * @memberof QuickShipmentLabel
     */
    toTime: string;
}

/**
 * Check if a given object implements the QuickShipmentLabel interface.
 */
export function instanceOfQuickShipmentLabel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "customer" in value;
    isInstance = isInstance && "fromTime" in value;
    isInstance = isInstance && "order" in value;
    isInstance = isInstance && "_package" in value;
    isInstance = isInstance && "packages" in value;
    isInstance = isInstance && "shipmentId" in value;
    isInstance = isInstance && "toTime" in value;

    return isInstance;
}

export function QuickShipmentLabelFromJSON(json: any): QuickShipmentLabel {
    return QuickShipmentLabelFromJSONTyped(json, false);
}

export function QuickShipmentLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuickShipmentLabel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
        'customer': json['customer'],
        'fromTime': json['from_time'],
        'order': json['order'],
        '_package': json['package'],
        'packages': json['packages'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'shipmentId': json['shipment_id'],
        'toTime': json['to_time'],
    };
}

export function QuickShipmentLabelToJSON(value?: QuickShipmentLabel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'customer': value.customer,
        'from_time': value.fromTime,
        'order': value.order,
        'package': value._package,
        'packages': value.packages,
        'phone': value.phone,
        'shipment_id': value.shipmentId,
        'to_time': value.toTime,
    };
}

