/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuoteSnapshot
 */
export interface QuoteSnapshot {
    /**
     * 
     * @type {string}
     * @memberof QuoteSnapshot
     */
    imageType: QuoteSnapshotImageTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof QuoteSnapshot
     */
    processingStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof QuoteSnapshot
     */
    uri: string;
}


/**
 * @export
 */
export const QuoteSnapshotImageTypeEnum = {
    Prescription: 'prescription',
    Ssc: 'ssc'
} as const;
export type QuoteSnapshotImageTypeEnum = typeof QuoteSnapshotImageTypeEnum[keyof typeof QuoteSnapshotImageTypeEnum];


/**
 * Check if a given object implements the QuoteSnapshot interface.
 */
export function instanceOfQuoteSnapshot(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "imageType" in value;
    isInstance = isInstance && "uri" in value;

    return isInstance;
}

export function QuoteSnapshotFromJSON(json: any): QuoteSnapshot {
    return QuoteSnapshotFromJSONTyped(json, false);
}

export function QuoteSnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuoteSnapshot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'imageType': json['image_type'],
        'processingStatus': !exists(json, 'processing_status') ? undefined : json['processing_status'],
        'uri': json['uri'],
    };
}

export function QuoteSnapshotToJSON(value?: QuoteSnapshot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image_type': value.imageType,
        'processing_status': value.processingStatus,
        'uri': value.uri,
    };
}

