/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReturnVehicleRequestMobil
 */
export interface ReturnVehicleRequestMobil {
    /**
     * 
     * @type {string}
     * @memberof ReturnVehicleRequestMobil
     */
    identifier?: string;
    /**
     * 
     * @type {number}
     * @memberof ReturnVehicleRequestMobil
     */
    kilometers?: number;
}

/**
 * Check if a given object implements the ReturnVehicleRequestMobil interface.
 */
export function instanceOfReturnVehicleRequestMobil(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReturnVehicleRequestMobilFromJSON(json: any): ReturnVehicleRequestMobil {
    return ReturnVehicleRequestMobilFromJSONTyped(json, false);
}

export function ReturnVehicleRequestMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReturnVehicleRequestMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identifier': !exists(json, 'identifier') ? undefined : json['identifier'],
        'kilometers': !exists(json, 'kilometers') ? undefined : json['kilometers'],
    };
}

export function ReturnVehicleRequestMobilToJSON(value?: ReturnVehicleRequestMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identifier': value.identifier,
        'kilometers': value.kilometers,
    };
}

