/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VRVehicle } from './VRVehicle';
import {
    VRVehicleFromJSON,
    VRVehicleFromJSONTyped,
    VRVehicleToJSON,
} from './VRVehicle';

/**
 * 
 * @export
 * @interface ReturnVehicleResponseMobil
 */
export interface ReturnVehicleResponseMobil {
    /**
     * 
     * @type {VRVehicle}
     * @memberof ReturnVehicleResponseMobil
     */
    vehicle: VRVehicle;
}

/**
 * Check if a given object implements the ReturnVehicleResponseMobil interface.
 */
export function instanceOfReturnVehicleResponseMobil(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "vehicle" in value;

    return isInstance;
}

export function ReturnVehicleResponseMobilFromJSON(json: any): ReturnVehicleResponseMobil {
    return ReturnVehicleResponseMobilFromJSONTyped(json, false);
}

export function ReturnVehicleResponseMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReturnVehicleResponseMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'vehicle': VRVehicleFromJSON(json['vehicle']),
    };
}

export function ReturnVehicleResponseMobilToJSON(value?: ReturnVehicleResponseMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'vehicle': VRVehicleToJSON(value.vehicle),
    };
}

