/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RNDynamicView
 */
export interface RNDynamicView {
    /**
     * 
     * @type {Array<RNDynamicView>}
     * @memberof RNDynamicView
     */
    children?: Array<RNDynamicView>;
    /**
     * 
     * @type {string}
     * @memberof RNDynamicView
     */
    component: string;
    /**
     * 
     * @type {string}
     * @memberof RNDynamicView
     */
    properties?: string;
    /**
     * 
     * @type {string}
     * @memberof RNDynamicView
     */
    text?: string;
}

/**
 * Check if a given object implements the RNDynamicView interface.
 */
export function instanceOfRNDynamicView(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "component" in value;

    return isInstance;
}

export function RNDynamicViewFromJSON(json: any): RNDynamicView {
    return RNDynamicViewFromJSONTyped(json, false);
}

export function RNDynamicViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): RNDynamicView {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'children': !exists(json, 'children') ? undefined : ((json['children'] as Array<any>).map(RNDynamicViewFromJSON)),
        'component': json['component'],
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
        'text': !exists(json, 'text') ? undefined : json['text'],
    };
}

export function RNDynamicViewToJSON(value?: RNDynamicView | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'children': value.children === undefined ? undefined : ((value.children as Array<any>).map(RNDynamicViewToJSON)),
        'component': value.component,
        'properties': value.properties,
        'text': value.text,
    };
}

