/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RouteLegStep } from './RouteLegStep';
import {
    RouteLegStepFromJSON,
    RouteLegStepFromJSONTyped,
    RouteLegStepToJSON,
} from './RouteLegStep';

/**
 * 
 * @export
 * @interface RouteLeg
 */
export interface RouteLeg {
    /**
     * 
     * @type {number}
     * @memberof RouteLeg
     */
    distanceM: number;
    /**
     * 
     * @type {number}
     * @memberof RouteLeg
     */
    durationS: number;
    /**
     * 
     * @type {Array<RouteLegStep>}
     * @memberof RouteLeg
     */
    steps: Array<RouteLegStep>;
}

/**
 * Check if a given object implements the RouteLeg interface.
 */
export function instanceOfRouteLeg(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "distanceM" in value;
    isInstance = isInstance && "durationS" in value;
    isInstance = isInstance && "steps" in value;

    return isInstance;
}

export function RouteLegFromJSON(json: any): RouteLeg {
    return RouteLegFromJSONTyped(json, false);
}

export function RouteLegFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteLeg {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'distanceM': json['distance_m'],
        'durationS': json['duration_s'],
        'steps': ((json['steps'] as Array<any>).map(RouteLegStepFromJSON)),
    };
}

export function RouteLegToJSON(value?: RouteLeg | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'distance_m': value.distanceM,
        'duration_s': value.durationS,
        'steps': ((value.steps as Array<any>).map(RouteLegStepToJSON)),
    };
}

