/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Coordinates } from './Coordinates';
import {
    CoordinatesFromJSON,
    CoordinatesFromJSONTyped,
    CoordinatesToJSON,
} from './Coordinates';
import type { RouteLeg } from './RouteLeg';
import {
    RouteLegFromJSON,
    RouteLegFromJSONTyped,
    RouteLegToJSON,
} from './RouteLeg';

/**
 * 
 * @export
 * @interface Route
 */
export interface Route {
    /**
     * 
     * @type {Coordinates}
     * @memberof Route
     */
    boundsNe: Coordinates;
    /**
     * 
     * @type {Coordinates}
     * @memberof Route
     */
    boundsSw: Coordinates;
    /**
     * 
     * @type {Array<RouteLeg>}
     * @memberof Route
     */
    legs: Array<RouteLeg>;
}

/**
 * Check if a given object implements the Route interface.
 */
export function instanceOfRoute(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "boundsNe" in value;
    isInstance = isInstance && "boundsSw" in value;
    isInstance = isInstance && "legs" in value;

    return isInstance;
}

export function RouteFromJSON(json: any): Route {
    return RouteFromJSONTyped(json, false);
}

export function RouteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Route {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'boundsNe': CoordinatesFromJSON(json['bounds_ne']),
        'boundsSw': CoordinatesFromJSON(json['bounds_sw']),
        'legs': ((json['legs'] as Array<any>).map(RouteLegFromJSON)),
    };
}

export function RouteToJSON(value?: Route | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bounds_ne': CoordinatesToJSON(value.boundsNe),
        'bounds_sw': CoordinatesToJSON(value.boundsSw),
        'legs': ((value.legs as Array<any>).map(RouteLegToJSON)),
    };
}

