/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RPIEvent
 */
export interface RPIEvent {
    /**
     * 
     * @type {string}
     * @memberof RPIEvent
     */
    permissions?: string;
    /**
     * 
     * @type {string}
     * @memberof RPIEvent
     */
    source: string;
    /**
     * 
     * @type {boolean}
     * @memberof RPIEvent
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof RPIEvent
     */
    timestamp: string;
    /**
     * 
     * @type {number}
     * @memberof RPIEvent
     */
    userId: number;
}

/**
 * Check if a given object implements the RPIEvent interface.
 */
export function instanceOfRPIEvent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "source" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "timestamp" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function RPIEventFromJSON(json: any): RPIEvent {
    return RPIEventFromJSONTyped(json, false);
}

export function RPIEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): RPIEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'permissions': !exists(json, 'permissions') ? undefined : json['permissions'],
        'source': json['source'],
        'success': json['success'],
        'timestamp': json['timestamp'],
        'userId': json['user_id'],
    };
}

export function RPIEventToJSON(value?: RPIEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'permissions': value.permissions,
        'source': value.source,
        'success': value.success,
        'timestamp': value.timestamp,
        'user_id': value.userId,
    };
}

