/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RPILastTimestampResponse
 */
export interface RPILastTimestampResponse {
    /**
     * 
     * @type {number}
     * @memberof RPILastTimestampResponse
     */
    timestamp?: number;
}

/**
 * Check if a given object implements the RPILastTimestampResponse interface.
 */
export function instanceOfRPILastTimestampResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RPILastTimestampResponseFromJSON(json: any): RPILastTimestampResponse {
    return RPILastTimestampResponseFromJSONTyped(json, false);
}

export function RPILastTimestampResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RPILastTimestampResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
    };
}

export function RPILastTimestampResponseToJSON(value?: RPILastTimestampResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timestamp': value.timestamp,
    };
}

