/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SalesOrderDeliveryTimeDeliveryTime } from './SalesOrderDeliveryTimeDeliveryTime';
import {
    SalesOrderDeliveryTimeDeliveryTimeFromJSON,
    SalesOrderDeliveryTimeDeliveryTimeFromJSONTyped,
    SalesOrderDeliveryTimeDeliveryTimeToJSON,
} from './SalesOrderDeliveryTimeDeliveryTime';

/**
 * 
 * @export
 * @interface SalesOrderDeliveryTime
 */
export interface SalesOrderDeliveryTime {
    /**
     * 
     * @type {string}
     * @memberof SalesOrderDeliveryTime
     */
    date: string;
    /**
     * 
     * @type {boolean}
     * @memberof SalesOrderDeliveryTime
     */
    express: boolean;
    /**
     * 
     * @type {SalesOrderDeliveryTimeDeliveryTime}
     * @memberof SalesOrderDeliveryTime
     */
    time?: SalesOrderDeliveryTimeDeliveryTime;
}

/**
 * Check if a given object implements the SalesOrderDeliveryTime interface.
 */
export function instanceOfSalesOrderDeliveryTime(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "express" in value;

    return isInstance;
}

export function SalesOrderDeliveryTimeFromJSON(json: any): SalesOrderDeliveryTime {
    return SalesOrderDeliveryTimeFromJSONTyped(json, false);
}

export function SalesOrderDeliveryTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesOrderDeliveryTime {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': json['date'],
        'express': json['express'],
        'time': !exists(json, 'time') ? undefined : SalesOrderDeliveryTimeDeliveryTimeFromJSON(json['time']),
    };
}

export function SalesOrderDeliveryTimeToJSON(value?: SalesOrderDeliveryTime | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date,
        'express': value.express,
        'time': SalesOrderDeliveryTimeDeliveryTimeToJSON(value.time),
    };
}

