/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SalesOrderDeliveryTimeDeliveryTime
 */
export interface SalesOrderDeliveryTimeDeliveryTime {
    /**
     * 
     * @type {number}
     * @memberof SalesOrderDeliveryTimeDeliveryTime
     */
    fromTime: number;
    /**
     * 
     * @type {number}
     * @memberof SalesOrderDeliveryTimeDeliveryTime
     */
    toTime: number;
}

/**
 * Check if a given object implements the SalesOrderDeliveryTimeDeliveryTime interface.
 */
export function instanceOfSalesOrderDeliveryTimeDeliveryTime(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fromTime" in value;
    isInstance = isInstance && "toTime" in value;

    return isInstance;
}

export function SalesOrderDeliveryTimeDeliveryTimeFromJSON(json: any): SalesOrderDeliveryTimeDeliveryTime {
    return SalesOrderDeliveryTimeDeliveryTimeFromJSONTyped(json, false);
}

export function SalesOrderDeliveryTimeDeliveryTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesOrderDeliveryTimeDeliveryTime {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fromTime': json['from_time'],
        'toTime': json['to_time'],
    };
}

export function SalesOrderDeliveryTimeDeliveryTimeToJSON(value?: SalesOrderDeliveryTimeDeliveryTime | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from_time': value.fromTime,
        'to_time': value.toTime,
    };
}

