/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GenericSOPackingListResponseMobil } from './GenericSOPackingListResponseMobil';
import {
    GenericSOPackingListResponseMobilFromJSON,
    GenericSOPackingListResponseMobilFromJSONTyped,
    GenericSOPackingListResponseMobilToJSON,
} from './GenericSOPackingListResponseMobil';
import type { QuickShipmentLabel } from './QuickShipmentLabel';
import {
    QuickShipmentLabelFromJSON,
    QuickShipmentLabelFromJSONTyped,
    QuickShipmentLabelToJSON,
} from './QuickShipmentLabel';

/**
 * 
 * @export
 * @interface SalesOrderResponseMobil
 */
export interface SalesOrderResponseMobil {
    /**
     * 
     * @type {string}
     * @memberof SalesOrderResponseMobil
     */
    customer: string;
    /**
     * 
     * @type {number}
     * @memberof SalesOrderResponseMobil
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof SalesOrderResponseMobil
     */
    inProcess: boolean;
    /**
     * 
     * @type {string}
     * @memberof SalesOrderResponseMobil
     */
    internalNotes?: string;
    /**
     * 
     * @type {string}
     * @memberof SalesOrderResponseMobil
     */
    notes?: string;
    /**
     * 
     * @type {Array<GenericSOPackingListResponseMobil>}
     * @memberof SalesOrderResponseMobil
     */
    packingLists?: Array<GenericSOPackingListResponseMobil>;
    /**
     * 
     * @type {Array<QuickShipmentLabel>}
     * @memberof SalesOrderResponseMobil
     */
    shipmentLabels?: Array<QuickShipmentLabel>;
    /**
     * 
     * @type {string}
     * @memberof SalesOrderResponseMobil
     */
    title: string;
}

/**
 * Check if a given object implements the SalesOrderResponseMobil interface.
 */
export function instanceOfSalesOrderResponseMobil(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "customer" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "inProcess" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function SalesOrderResponseMobilFromJSON(json: any): SalesOrderResponseMobil {
    return SalesOrderResponseMobilFromJSONTyped(json, false);
}

export function SalesOrderResponseMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesOrderResponseMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customer': json['customer'],
        'id': json['id'],
        'inProcess': json['in_process'],
        'internalNotes': !exists(json, 'internal_notes') ? undefined : json['internal_notes'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'packingLists': !exists(json, 'packing_lists') ? undefined : ((json['packing_lists'] as Array<any>).map(GenericSOPackingListResponseMobilFromJSON)),
        'shipmentLabels': !exists(json, 'shipment_labels') ? undefined : ((json['shipment_labels'] as Array<any>).map(QuickShipmentLabelFromJSON)),
        'title': json['title'],
    };
}

export function SalesOrderResponseMobilToJSON(value?: SalesOrderResponseMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customer': value.customer,
        'id': value.id,
        'in_process': value.inProcess,
        'internal_notes': value.internalNotes,
        'notes': value.notes,
        'packing_lists': value.packingLists === undefined ? undefined : ((value.packingLists as Array<any>).map(GenericSOPackingListResponseMobilToJSON)),
        'shipment_labels': value.shipmentLabels === undefined ? undefined : ((value.shipmentLabels as Array<any>).map(QuickShipmentLabelToJSON)),
        'title': value.title,
    };
}

