/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SalesOrder
 */
export interface SalesOrder {
    /**
     * 
     * @type {boolean}
     * @memberof SalesOrder
     */
    backorder: boolean;
    /**
     * 
     * @type {string}
     * @memberof SalesOrder
     */
    customer: string;
    /**
     * 
     * @type {string}
     * @memberof SalesOrder
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof SalesOrder
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SalesOrder
     */
    minsFromCreation: string;
    /**
     * 
     * @type {string}
     * @memberof SalesOrder
     */
    prepared?: string;
}

/**
 * Check if a given object implements the SalesOrder interface.
 */
export function instanceOfSalesOrder(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "backorder" in value;
    isInstance = isInstance && "customer" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "minsFromCreation" in value;

    return isInstance;
}

export function SalesOrderFromJSON(json: any): SalesOrder {
    return SalesOrderFromJSONTyped(json, false);
}

export function SalesOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'backorder': json['backorder'],
        'customer': json['customer'],
        'date': json['date'],
        'id': json['id'],
        'minsFromCreation': json['mins_from_creation'],
        'prepared': !exists(json, 'prepared') ? undefined : json['prepared'],
    };
}

export function SalesOrderToJSON(value?: SalesOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'backorder': value.backorder,
        'customer': value.customer,
        'date': value.date,
        'id': value.id,
        'mins_from_creation': value.minsFromCreation,
        'prepared': value.prepared,
    };
}

