/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Coordinates } from './Coordinates';
import {
    CoordinatesFromJSON,
    CoordinatesFromJSONTyped,
    CoordinatesToJSON,
} from './Coordinates';

/**
 * 
 * @export
 * @interface SearchDeliveriesRequestMobil
 */
export interface SearchDeliveriesRequestMobil {
    /**
     * 
     * @type {Coordinates}
     * @memberof SearchDeliveriesRequestMobil
     */
    currentLocation?: Coordinates;
}

/**
 * Check if a given object implements the SearchDeliveriesRequestMobil interface.
 */
export function instanceOfSearchDeliveriesRequestMobil(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchDeliveriesRequestMobilFromJSON(json: any): SearchDeliveriesRequestMobil {
    return SearchDeliveriesRequestMobilFromJSONTyped(json, false);
}

export function SearchDeliveriesRequestMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchDeliveriesRequestMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentLocation': !exists(json, 'current_location') ? undefined : CoordinatesFromJSON(json['current_location']),
    };
}

export function SearchDeliveriesRequestMobilToJSON(value?: SearchDeliveriesRequestMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'current_location': CoordinatesToJSON(value.currentLocation),
    };
}

