/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VRVehicle } from './VRVehicle';
import {
    VRVehicleFromJSON,
    VRVehicleFromJSONTyped,
    VRVehicleToJSON,
} from './VRVehicle';

/**
 * 
 * @export
 * @interface SearchAssignedVehicleResponseMobil
 */
export interface SearchAssignedVehicleResponseMobil {
    /**
     * 
     * @type {VRVehicle}
     * @memberof SearchAssignedVehicleResponseMobil
     */
    vehicle: VRVehicle;
}

/**
 * Check if a given object implements the SearchAssignedVehicleResponseMobil interface.
 */
export function instanceOfSearchAssignedVehicleResponseMobil(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "vehicle" in value;

    return isInstance;
}

export function SearchAssignedVehicleResponseMobilFromJSON(json: any): SearchAssignedVehicleResponseMobil {
    return SearchAssignedVehicleResponseMobilFromJSONTyped(json, false);
}

export function SearchAssignedVehicleResponseMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchAssignedVehicleResponseMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'vehicle': VRVehicleFromJSON(json['vehicle']),
    };
}

export function SearchAssignedVehicleResponseMobilToJSON(value?: SearchAssignedVehicleResponseMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'vehicle': VRVehicleToJSON(value.vehicle),
    };
}

