/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ViaRapidaDelivery } from './ViaRapidaDelivery';
import {
    ViaRapidaDeliveryFromJSON,
    ViaRapidaDeliveryFromJSONTyped,
    ViaRapidaDeliveryToJSON,
} from './ViaRapidaDelivery';
import type { ViaRapidaDriver } from './ViaRapidaDriver';
import {
    ViaRapidaDriverFromJSON,
    ViaRapidaDriverFromJSONTyped,
    ViaRapidaDriverToJSON,
} from './ViaRapidaDriver';

/**
 * 
 * @export
 * @interface SearchDeliveriesResponseMobil
 */
export interface SearchDeliveriesResponseMobil {
    /**
     * 
     * @type {ViaRapidaDriver}
     * @memberof SearchDeliveriesResponseMobil
     */
    driver?: ViaRapidaDriver;
    /**
     * 
     * @type {string}
     * @memberof SearchDeliveriesResponseMobil
     */
    now?: string;
    /**
     * 
     * @type {Array<ViaRapidaDelivery>}
     * @memberof SearchDeliveriesResponseMobil
     */
    shipments?: Array<ViaRapidaDelivery>;
}

/**
 * Check if a given object implements the SearchDeliveriesResponseMobil interface.
 */
export function instanceOfSearchDeliveriesResponseMobil(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchDeliveriesResponseMobilFromJSON(json: any): SearchDeliveriesResponseMobil {
    return SearchDeliveriesResponseMobilFromJSONTyped(json, false);
}

export function SearchDeliveriesResponseMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchDeliveriesResponseMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'driver': !exists(json, 'driver') ? undefined : ViaRapidaDriverFromJSON(json['driver']),
        'now': !exists(json, 'now') ? undefined : json['now'],
        'shipments': !exists(json, 'shipments') ? undefined : ((json['shipments'] as Array<any>).map(ViaRapidaDeliveryFromJSON)),
    };
}

export function SearchDeliveriesResponseMobilToJSON(value?: SearchDeliveriesResponseMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'driver': ViaRapidaDriverToJSON(value.driver),
        'now': value.now,
        'shipments': value.shipments === undefined ? undefined : ((value.shipments as Array<any>).map(ViaRapidaDeliveryToJSON)),
    };
}

