/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Coordinates } from './Coordinates';
import {
    CoordinatesFromJSON,
    CoordinatesFromJSONTyped,
    CoordinatesToJSON,
} from './Coordinates';

/**
 * 
 * @export
 * @interface ShortAddress
 */
export interface ShortAddress {
    /**
     * 
     * @type {string}
     * @memberof ShortAddress
     */
    address: string;
    /**
     * 
     * @type {Coordinates}
     * @memberof ShortAddress
     */
    coordinates?: Coordinates;
    /**
     * 
     * @type {string}
     * @memberof ShortAddress
     */
    geocodableAddress: string;
    /**
     * 
     * @type {number}
     * @memberof ShortAddress
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ShortAddress
     */
    phoneNumber?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ShortAddress
     */
    zonesAvailable?: Array<number>;
}

/**
 * Check if a given object implements the ShortAddress interface.
 */
export function instanceOfShortAddress(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "geocodableAddress" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function ShortAddressFromJSON(json: any): ShortAddress {
    return ShortAddressFromJSONTyped(json, false);
}

export function ShortAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShortAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
        'coordinates': !exists(json, 'coordinates') ? undefined : CoordinatesFromJSON(json['coordinates']),
        'geocodableAddress': json['geocodable_address'],
        'id': json['id'],
        'phoneNumber': !exists(json, 'phone_number') ? undefined : json['phone_number'],
        'zonesAvailable': !exists(json, 'zones_available') ? undefined : json['zones_available'],
    };
}

export function ShortAddressToJSON(value?: ShortAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'coordinates': CoordinatesToJSON(value.coordinates),
        'geocodable_address': value.geocodableAddress,
        'id': value.id,
        'phone_number': value.phoneNumber,
        'zones_available': value.zonesAvailable,
    };
}

