/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SalesOrder } from './SalesOrder';
import {
    SalesOrderFromJSON,
    SalesOrderFromJSONTyped,
    SalesOrderToJSON,
} from './SalesOrder';

/**
 * 
 * @export
 * @interface SOListResponseMobil
 */
export interface SOListResponseMobil {
    /**
     * 
     * @type {Array<SalesOrder>}
     * @memberof SOListResponseMobil
     */
    salesOrders?: Array<SalesOrder>;
}

/**
 * Check if a given object implements the SOListResponseMobil interface.
 */
export function instanceOfSOListResponseMobil(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SOListResponseMobilFromJSON(json: any): SOListResponseMobil {
    return SOListResponseMobilFromJSONTyped(json, false);
}

export function SOListResponseMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): SOListResponseMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'salesOrders': !exists(json, 'sales_orders') ? undefined : ((json['sales_orders'] as Array<any>).map(SalesOrderFromJSON)),
    };
}

export function SOListResponseMobilToJSON(value?: SOListResponseMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sales_orders': value.salesOrders === undefined ? undefined : ((value.salesOrders as Array<any>).map(SalesOrderToJSON)),
    };
}

