/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SOPackingListCloseRequestMobil
 */
export interface SOPackingListCloseRequestMobil {
    /**
     * 
     * @type {number}
     * @memberof SOPackingListCloseRequestMobil
     */
    packingListId: number;
}

/**
 * Check if a given object implements the SOPackingListCloseRequestMobil interface.
 */
export function instanceOfSOPackingListCloseRequestMobil(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "packingListId" in value;

    return isInstance;
}

export function SOPackingListCloseRequestMobilFromJSON(json: any): SOPackingListCloseRequestMobil {
    return SOPackingListCloseRequestMobilFromJSONTyped(json, false);
}

export function SOPackingListCloseRequestMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): SOPackingListCloseRequestMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'packingListId': json['packing_list_id'],
    };
}

export function SOPackingListCloseRequestMobilToJSON(value?: SOPackingListCloseRequestMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'packing_list_id': value.packingListId,
    };
}

