/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SOPackingListItem } from './SOPackingListItem';
import {
    SOPackingListItemFromJSON,
    SOPackingListItemFromJSONTyped,
    SOPackingListItemToJSON,
} from './SOPackingListItem';

/**
 * 
 * @export
 * @interface SOPackingListResponseMobil
 */
export interface SOPackingListResponseMobil {
    /**
     * 
     * @type {boolean}
     * @memberof SOPackingListResponseMobil
     */
    canClose: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SOPackingListResponseMobil
     */
    completed: boolean;
    /**
     * 
     * @type {number}
     * @memberof SOPackingListResponseMobil
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof SOPackingListResponseMobil
     */
    inProcess: boolean;
    /**
     * 
     * @type {Array<SOPackingListItem>}
     * @memberof SOPackingListResponseMobil
     */
    items?: Array<SOPackingListItem>;
    /**
     * 
     * @type {number}
     * @memberof SOPackingListResponseMobil
     */
    shipmentId: number;
    /**
     * 
     * @type {number}
     * @memberof SOPackingListResponseMobil
     */
    soId: number;
}

/**
 * Check if a given object implements the SOPackingListResponseMobil interface.
 */
export function instanceOfSOPackingListResponseMobil(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "canClose" in value;
    isInstance = isInstance && "completed" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "inProcess" in value;
    isInstance = isInstance && "shipmentId" in value;
    isInstance = isInstance && "soId" in value;

    return isInstance;
}

export function SOPackingListResponseMobilFromJSON(json: any): SOPackingListResponseMobil {
    return SOPackingListResponseMobilFromJSONTyped(json, false);
}

export function SOPackingListResponseMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): SOPackingListResponseMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'canClose': json['can_close'],
        'completed': json['completed'],
        'id': json['id'],
        'inProcess': json['in_process'],
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(SOPackingListItemFromJSON)),
        'shipmentId': json['shipment_id'],
        'soId': json['so_id'],
    };
}

export function SOPackingListResponseMobilToJSON(value?: SOPackingListResponseMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'can_close': value.canClose,
        'completed': value.completed,
        'id': value.id,
        'in_process': value.inProcess,
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(SOPackingListItemToJSON)),
        'shipment_id': value.shipmentId,
        'so_id': value.soId,
    };
}

