/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuggestRequest
 */
export interface SuggestRequest {
    /**
     * 
     * @type {string}
     * @memberof SuggestRequest
     */
    q: string;
}

/**
 * Check if a given object implements the SuggestRequest interface.
 */
export function instanceOfSuggestRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "q" in value;

    return isInstance;
}

export function SuggestRequestFromJSON(json: any): SuggestRequest {
    return SuggestRequestFromJSONTyped(json, false);
}

export function SuggestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'q': json['q'],
    };
}

export function SuggestRequestToJSON(value?: SuggestRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'q': value.q,
    };
}

