/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaxiSetOrderDelayedOnDropoffRequest
 */
export interface TaxiSetOrderDelayedOnDropoffRequest {
    /**
     * 
     * @type {number}
     * @memberof TaxiSetOrderDelayedOnDropoffRequest
     */
    tripId: number;
}

/**
 * Check if a given object implements the TaxiSetOrderDelayedOnDropoffRequest interface.
 */
export function instanceOfTaxiSetOrderDelayedOnDropoffRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tripId" in value;

    return isInstance;
}

export function TaxiSetOrderDelayedOnDropoffRequestFromJSON(json: any): TaxiSetOrderDelayedOnDropoffRequest {
    return TaxiSetOrderDelayedOnDropoffRequestFromJSONTyped(json, false);
}

export function TaxiSetOrderDelayedOnDropoffRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxiSetOrderDelayedOnDropoffRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tripId': json['trip_id'],
    };
}

export function TaxiSetOrderDelayedOnDropoffRequestToJSON(value?: TaxiSetOrderDelayedOnDropoffRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'trip_id': value.tripId,
    };
}

