/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaxiChatMessage
 */
export interface TaxiChatMessage {
    /**
     * 
     * @type {number}
     * @memberof TaxiChatMessage
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TaxiChatMessage
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof TaxiChatMessage
     */
    sender: string;
    /**
     * 
     * @type {string}
     * @memberof TaxiChatMessage
     */
    timestamp: string;
}

/**
 * Check if a given object implements the TaxiChatMessage interface.
 */
export function instanceOfTaxiChatMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "sender" in value;
    isInstance = isInstance && "timestamp" in value;

    return isInstance;
}

export function TaxiChatMessageFromJSON(json: any): TaxiChatMessage {
    return TaxiChatMessageFromJSONTyped(json, false);
}

export function TaxiChatMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxiChatMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'message': json['message'],
        'sender': json['sender'],
        'timestamp': json['timestamp'],
    };
}

export function TaxiChatMessageToJSON(value?: TaxiChatMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'message': value.message,
        'sender': value.sender,
        'timestamp': value.timestamp,
    };
}

