/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './Money';

/**
 * 
 * @export
 * @interface TaxiAccountReportEntry
 */
export interface TaxiAccountReportEntry {
    /**
     * 
     * @type {Money}
     * @memberof TaxiAccountReportEntry
     */
    amount: Money;
    /**
     * 
     * @type {string}
     * @memberof TaxiAccountReportEntry
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof TaxiAccountReportEntry
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TaxiAccountReportEntry
     */
    notes: string;
    /**
     * 
     * @type {Money}
     * @memberof TaxiAccountReportEntry
     */
    saldo: Money;
}

/**
 * Check if a given object implements the TaxiAccountReportEntry interface.
 */
export function instanceOfTaxiAccountReportEntry(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "notes" in value;
    isInstance = isInstance && "saldo" in value;

    return isInstance;
}

export function TaxiAccountReportEntryFromJSON(json: any): TaxiAccountReportEntry {
    return TaxiAccountReportEntryFromJSONTyped(json, false);
}

export function TaxiAccountReportEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxiAccountReportEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': MoneyFromJSON(json['amount']),
        'date': json['date'],
        'id': json['id'],
        'notes': json['notes'],
        'saldo': MoneyFromJSON(json['saldo']),
    };
}

export function TaxiAccountReportEntryToJSON(value?: TaxiAccountReportEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': MoneyToJSON(value.amount),
        'date': value.date,
        'id': value.id,
        'notes': value.notes,
        'saldo': MoneyToJSON(value.saldo),
    };
}

