/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaxiChatMessageRequest
 */
export interface TaxiChatMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof TaxiChatMessageRequest
     */
    message: string;
    /**
     * 
     * @type {number}
     * @memberof TaxiChatMessageRequest
     */
    tripId: number;
}

/**
 * Check if a given object implements the TaxiChatMessageRequest interface.
 */
export function instanceOfTaxiChatMessageRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "tripId" in value;

    return isInstance;
}

export function TaxiChatMessageRequestFromJSON(json: any): TaxiChatMessageRequest {
    return TaxiChatMessageRequestFromJSONTyped(json, false);
}

export function TaxiChatMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxiChatMessageRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'tripId': json['trip_id'],
    };
}

export function TaxiChatMessageRequestToJSON(value?: TaxiChatMessageRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'trip_id': value.tripId,
    };
}

