/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './Money';
import type { RNDynamicView } from './RNDynamicView';
import {
    RNDynamicViewFromJSON,
    RNDynamicViewFromJSONTyped,
    RNDynamicViewToJSON,
} from './RNDynamicView';

/**
 * 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * 
     * @type {Money}
     * @memberof Transaction
     */
    amount: Money;
    /**
     * 
     * @type {Money}
     * @memberof Transaction
     */
    balance?: Money;
    /**
     * 
     * @type {RNDynamicView}
     * @memberof Transaction
     */
    depositInstructions?: RNDynamicView;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    paymentLink?: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    paymentLinkMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    pubId: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    qrcodeInstructions?: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    qrcodeUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    transactionType?: TransactionTransactionTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof Transaction
     */
    when: Date;
}


/**
 * @export
 */
export const TransactionTransactionTypeEnum = {
    Deposit: 'deposit',
    Transfer: 'transfer',
    Purchase: 'purchase'
} as const;
export type TransactionTransactionTypeEnum = typeof TransactionTransactionTypeEnum[keyof typeof TransactionTransactionTypeEnum];


/**
 * Check if a given object implements the Transaction interface.
 */
export function instanceOfTransaction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "pubId" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "when" in value;

    return isInstance;
}

export function TransactionFromJSON(json: any): Transaction {
    return TransactionFromJSONTyped(json, false);
}

export function TransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transaction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': MoneyFromJSON(json['amount']),
        'balance': !exists(json, 'balance') ? undefined : MoneyFromJSON(json['balance']),
        'depositInstructions': !exists(json, 'deposit_instructions') ? undefined : RNDynamicViewFromJSON(json['deposit_instructions']),
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'paymentLink': !exists(json, 'payment_link') ? undefined : json['payment_link'],
        'paymentLinkMessage': !exists(json, 'payment_link_message') ? undefined : json['payment_link_message'],
        'pubId': json['pub_id'],
        'qrcodeInstructions': !exists(json, 'qrcode_instructions') ? undefined : json['qrcode_instructions'],
        'qrcodeUrl': !exists(json, 'qrcode_url') ? undefined : json['qrcode_url'],
        'status': json['status'],
        'title': json['title'],
        'transactionType': !exists(json, 'transaction_type') ? undefined : json['transaction_type'],
        'when': (new Date(json['when'])),
    };
}

export function TransactionToJSON(value?: Transaction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': MoneyToJSON(value.amount),
        'balance': MoneyToJSON(value.balance),
        'deposit_instructions': RNDynamicViewToJSON(value.depositInstructions),
        'notes': value.notes,
        'payment_link': value.paymentLink,
        'payment_link_message': value.paymentLinkMessage,
        'pub_id': value.pubId,
        'qrcode_instructions': value.qrcodeInstructions,
        'qrcode_url': value.qrcodeUrl,
        'status': value.status,
        'title': value.title,
        'transaction_type': value.transactionType,
        'when': (value.when.toISOString()),
    };
}

