/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PassportPermission } from './PassportPermission';
import {
    PassportPermissionFromJSON,
    PassportPermissionFromJSONTyped,
    PassportPermissionToJSON,
} from './PassportPermission';

/**
 * 
 * @export
 * @interface UpdateTokenResponseMobil
 */
export interface UpdateTokenResponseMobil {
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateTokenResponseMobil
     */
    assignments?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateTokenResponseMobil
     */
    locomotoUrl: string;
    /**
     * 
     * @type {Array<PassportPermission>}
     * @memberof UpdateTokenResponseMobil
     */
    passportPermissionsDescriptions?: Array<PassportPermission>;
    /**
     * 
     * @type {string}
     * @memberof UpdateTokenResponseMobil
     */
    passportPublicKey?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTokenResponseMobil
     */
    token: string;
}

/**
 * Check if a given object implements the UpdateTokenResponseMobil interface.
 */
export function instanceOfUpdateTokenResponseMobil(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "locomotoUrl" in value;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function UpdateTokenResponseMobilFromJSON(json: any): UpdateTokenResponseMobil {
    return UpdateTokenResponseMobilFromJSONTyped(json, false);
}

export function UpdateTokenResponseMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTokenResponseMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assignments': !exists(json, 'assignments') ? undefined : json['assignments'],
        'locomotoUrl': json['locomoto_url'],
        'passportPermissionsDescriptions': !exists(json, 'passport_permissions_descriptions') ? undefined : ((json['passport_permissions_descriptions'] as Array<any>).map(PassportPermissionFromJSON)),
        'passportPublicKey': !exists(json, 'passport_public_key') ? undefined : json['passport_public_key'],
        'token': json['token'],
    };
}

export function UpdateTokenResponseMobilToJSON(value?: UpdateTokenResponseMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'assignments': value.assignments,
        'locomoto_url': value.locomotoUrl,
        'passport_permissions_descriptions': value.passportPermissionsDescriptions === undefined ? undefined : ((value.passportPermissionsDescriptions as Array<any>).map(PassportPermissionToJSON)),
        'passport_public_key': value.passportPublicKey,
        'token': value.token,
    };
}

