/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTokenRequestMobil
 */
export interface UpdateTokenRequestMobil {
    /**
     * 
     * @type {string}
     * @memberof UpdateTokenRequestMobil
     */
    token: string;
}

/**
 * Check if a given object implements the UpdateTokenRequestMobil interface.
 */
export function instanceOfUpdateTokenRequestMobil(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function UpdateTokenRequestMobilFromJSON(json: any): UpdateTokenRequestMobil {
    return UpdateTokenRequestMobilFromJSONTyped(json, false);
}

export function UpdateTokenRequestMobilFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTokenRequestMobil {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function UpdateTokenRequestMobilToJSON(value?: UpdateTokenRequestMobil | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

