/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViaRapidaStartPhoneValidationRequest
 */
export interface ViaRapidaStartPhoneValidationRequest {
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaStartPhoneValidationRequest
     */
    method: ViaRapidaStartPhoneValidationRequestMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaStartPhoneValidationRequest
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaStartPhoneValidationRequest
     */
    pushNotificationOs?: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaStartPhoneValidationRequest
     */
    pushNotificationToken?: string;
}


/**
 * @export
 */
export const ViaRapidaStartPhoneValidationRequestMethodEnum = {
    Voice: 'voice',
    Sms: 'sms'
} as const;
export type ViaRapidaStartPhoneValidationRequestMethodEnum = typeof ViaRapidaStartPhoneValidationRequestMethodEnum[keyof typeof ViaRapidaStartPhoneValidationRequestMethodEnum];


/**
 * Check if a given object implements the ViaRapidaStartPhoneValidationRequest interface.
 */
export function instanceOfViaRapidaStartPhoneValidationRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "method" in value;
    isInstance = isInstance && "phone" in value;

    return isInstance;
}

export function ViaRapidaStartPhoneValidationRequestFromJSON(json: any): ViaRapidaStartPhoneValidationRequest {
    return ViaRapidaStartPhoneValidationRequestFromJSONTyped(json, false);
}

export function ViaRapidaStartPhoneValidationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaStartPhoneValidationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'method': json['method'],
        'phone': json['phone'],
        'pushNotificationOs': !exists(json, 'push_notification_os') ? undefined : json['push_notification_os'],
        'pushNotificationToken': !exists(json, 'push_notification_token') ? undefined : json['push_notification_token'],
    };
}

export function ViaRapidaStartPhoneValidationRequestToJSON(value?: ViaRapidaStartPhoneValidationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'method': value.method,
        'phone': value.phone,
        'push_notification_os': value.pushNotificationOs,
        'push_notification_token': value.pushNotificationToken,
    };
}

