/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './Money';
import type { ViaRapidaPaymentMethodOption } from './ViaRapidaPaymentMethodOption';
import {
    ViaRapidaPaymentMethodOptionFromJSON,
    ViaRapidaPaymentMethodOptionFromJSONTyped,
    ViaRapidaPaymentMethodOptionToJSON,
} from './ViaRapidaPaymentMethodOption';
import type { ViaRapidaPaymentMethodPerception } from './ViaRapidaPaymentMethodPerception';
import {
    ViaRapidaPaymentMethodPerceptionFromJSON,
    ViaRapidaPaymentMethodPerceptionFromJSONTyped,
    ViaRapidaPaymentMethodPerceptionToJSON,
} from './ViaRapidaPaymentMethodPerception';

/**
 * 
 * @export
 * @interface ViaRapidaPaymentMethod
 */
export interface ViaRapidaPaymentMethod {
    /**
     * 
     * @type {Money}
     * @memberof ViaRapidaPaymentMethod
     */
    deliveryPrice: Money;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaPaymentMethod
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof ViaRapidaPaymentMethod
     */
    enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaPaymentMethod
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaPaymentMethod
     */
    image?: string;
    /**
     * 
     * @type {Array<ViaRapidaPaymentMethodOption>}
     * @memberof ViaRapidaPaymentMethod
     */
    options?: Array<ViaRapidaPaymentMethodOption>;
    /**
     * 
     * @type {Array<ViaRapidaPaymentMethodPerception>}
     * @memberof ViaRapidaPaymentMethod
     */
    perceptions?: Array<ViaRapidaPaymentMethodPerception>;
    /**
     * 
     * @type {number}
     * @memberof ViaRapidaPaymentMethod
     */
    sortValue?: number;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaPaymentMethod
     */
    title: string;
    /**
     * 
     * @type {Money}
     * @memberof ViaRapidaPaymentMethod
     */
    total: Money;
}

/**
 * Check if a given object implements the ViaRapidaPaymentMethod interface.
 */
export function instanceOfViaRapidaPaymentMethod(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "deliveryPrice" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "enabled" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function ViaRapidaPaymentMethodFromJSON(json: any): ViaRapidaPaymentMethod {
    return ViaRapidaPaymentMethodFromJSONTyped(json, false);
}

export function ViaRapidaPaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaPaymentMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deliveryPrice': MoneyFromJSON(json['delivery_price']),
        'description': json['description'],
        'enabled': json['enabled'],
        'id': json['id'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        'options': !exists(json, 'options') ? undefined : ((json['options'] as Array<any>).map(ViaRapidaPaymentMethodOptionFromJSON)),
        'perceptions': !exists(json, 'perceptions') ? undefined : ((json['perceptions'] as Array<any>).map(ViaRapidaPaymentMethodPerceptionFromJSON)),
        'sortValue': !exists(json, 'sort_value') ? undefined : json['sort_value'],
        'title': json['title'],
        'total': MoneyFromJSON(json['total']),
    };
}

export function ViaRapidaPaymentMethodToJSON(value?: ViaRapidaPaymentMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'delivery_price': MoneyToJSON(value.deliveryPrice),
        'description': value.description,
        'enabled': value.enabled,
        'id': value.id,
        'image': value.image,
        'options': value.options === undefined ? undefined : ((value.options as Array<any>).map(ViaRapidaPaymentMethodOptionToJSON)),
        'perceptions': value.perceptions === undefined ? undefined : ((value.perceptions as Array<any>).map(ViaRapidaPaymentMethodPerceptionToJSON)),
        'sort_value': value.sortValue,
        'title': value.title,
        'total': MoneyToJSON(value.total),
    };
}

