/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './Money';
import type { ShortAddress } from './ShortAddress';
import {
    ShortAddressFromJSON,
    ShortAddressFromJSONTyped,
    ShortAddressToJSON,
} from './ShortAddress';
import type { ViaRapida3PItem } from './ViaRapida3PItem';
import {
    ViaRapida3PItemFromJSON,
    ViaRapida3PItemFromJSONTyped,
    ViaRapida3PItemToJSON,
} from './ViaRapida3PItem';
import type { ViaRapida3PSeller } from './ViaRapida3PSeller';
import {
    ViaRapida3PSellerFromJSON,
    ViaRapida3PSellerFromJSONTyped,
    ViaRapida3PSellerToJSON,
} from './ViaRapida3PSeller';
import type { ViaRapidaStoreQuote } from './ViaRapidaStoreQuote';
import {
    ViaRapidaStoreQuoteFromJSON,
    ViaRapidaStoreQuoteFromJSONTyped,
    ViaRapidaStoreQuoteToJSON,
} from './ViaRapidaStoreQuote';
import type { ViaRapidaStoreQuoteResponse } from './ViaRapidaStoreQuoteResponse';
import {
    ViaRapidaStoreQuoteResponseFromJSON,
    ViaRapidaStoreQuoteResponseFromJSONTyped,
    ViaRapidaStoreQuoteResponseToJSON,
} from './ViaRapidaStoreQuoteResponse';

/**
 * 
 * @export
 * @interface ViaRapida3PCartDataResponse
 */
export interface ViaRapida3PCartDataResponse {
    /**
     * 
     * @type {Money}
     * @memberof ViaRapida3PCartDataResponse
     */
    balance?: Money;
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PCartDataResponse
     */
    couponCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PCartDataResponse
     */
    couponStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PCartDataResponse
     */
    deliveryPrice?: string;
    /**
     * 
     * @type {Array<ViaRapidaStoreQuoteResponse>}
     * @memberof ViaRapida3PCartDataResponse
     */
    quotesStatus?: Array<ViaRapidaStoreQuoteResponse>;
    /**
     * 
     * @type {ViaRapida3PSeller}
     * @memberof ViaRapida3PCartDataResponse
     */
    seller: ViaRapida3PSeller;
    /**
     * 
     * @type {Array<ViaRapida3PItem>}
     * @memberof ViaRapida3PCartDataResponse
     */
    sellerItems?: Array<ViaRapida3PItem>;
    /**
     * 
     * @type {Array<ViaRapidaStoreQuote>}
     * @memberof ViaRapida3PCartDataResponse
     */
    sellerQuotes?: Array<ViaRapidaStoreQuote>;
    /**
     * 
     * @type {ShortAddress}
     * @memberof ViaRapida3PCartDataResponse
     */
    warehouse?: ShortAddress;
}

/**
 * Check if a given object implements the ViaRapida3PCartDataResponse interface.
 */
export function instanceOfViaRapida3PCartDataResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "seller" in value;

    return isInstance;
}

export function ViaRapida3PCartDataResponseFromJSON(json: any): ViaRapida3PCartDataResponse {
    return ViaRapida3PCartDataResponseFromJSONTyped(json, false);
}

export function ViaRapida3PCartDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapida3PCartDataResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'balance': !exists(json, 'balance') ? undefined : MoneyFromJSON(json['balance']),
        'couponCode': !exists(json, 'coupon_code') ? undefined : json['coupon_code'],
        'couponStatus': !exists(json, 'coupon_status') ? undefined : json['coupon_status'],
        'deliveryPrice': !exists(json, 'delivery_price') ? undefined : json['delivery_price'],
        'quotesStatus': !exists(json, 'quotes_status') ? undefined : ((json['quotes_status'] as Array<any>).map(ViaRapidaStoreQuoteResponseFromJSON)),
        'seller': ViaRapida3PSellerFromJSON(json['seller']),
        'sellerItems': !exists(json, 'seller_items') ? undefined : ((json['seller_items'] as Array<any>).map(ViaRapida3PItemFromJSON)),
        'sellerQuotes': !exists(json, 'seller_quotes') ? undefined : ((json['seller_quotes'] as Array<any>).map(ViaRapidaStoreQuoteFromJSON)),
        'warehouse': !exists(json, 'warehouse') ? undefined : ShortAddressFromJSON(json['warehouse']),
    };
}

export function ViaRapida3PCartDataResponseToJSON(value?: ViaRapida3PCartDataResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'balance': MoneyToJSON(value.balance),
        'coupon_code': value.couponCode,
        'coupon_status': value.couponStatus,
        'delivery_price': value.deliveryPrice,
        'quotes_status': value.quotesStatus === undefined ? undefined : ((value.quotesStatus as Array<any>).map(ViaRapidaStoreQuoteResponseToJSON)),
        'seller': ViaRapida3PSellerToJSON(value.seller),
        'seller_items': value.sellerItems === undefined ? undefined : ((value.sellerItems as Array<any>).map(ViaRapida3PItemToJSON)),
        'seller_quotes': value.sellerQuotes === undefined ? undefined : ((value.sellerQuotes as Array<any>).map(ViaRapidaStoreQuoteToJSON)),
        'warehouse': ShortAddressToJSON(value.warehouse),
    };
}

