/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Endpoint } from './Endpoint';
import {
    EndpointFromJSON,
    EndpointFromJSONTyped,
    EndpointToJSON,
} from './Endpoint';

/**
 * 
 * @export
 * @interface ViaRapidaEndpointsResponse
 */
export interface ViaRapidaEndpointsResponse {
    /**
     * 
     * @type {Array<Endpoint>}
     * @memberof ViaRapidaEndpointsResponse
     */
    endpoints: Array<Endpoint>;
}

/**
 * Check if a given object implements the ViaRapidaEndpointsResponse interface.
 */
export function instanceOfViaRapidaEndpointsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "endpoints" in value;

    return isInstance;
}

export function ViaRapidaEndpointsResponseFromJSON(json: any): ViaRapidaEndpointsResponse {
    return ViaRapidaEndpointsResponseFromJSONTyped(json, false);
}

export function ViaRapidaEndpointsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaEndpointsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'endpoints': ((json['endpoints'] as Array<any>).map(EndpointFromJSON)),
    };
}

export function ViaRapidaEndpointsResponseToJSON(value?: ViaRapidaEndpointsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'endpoints': ((value.endpoints as Array<any>).map(EndpointToJSON)),
    };
}

