/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViaRapida3PSellerReviewsRequest
 */
export interface ViaRapida3PSellerReviewsRequest {
    /**
     * 
     * @type {number}
     * @memberof ViaRapida3PSellerReviewsRequest
     */
    sellerId?: number;
}

/**
 * Check if a given object implements the ViaRapida3PSellerReviewsRequest interface.
 */
export function instanceOfViaRapida3PSellerReviewsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ViaRapida3PSellerReviewsRequestFromJSON(json: any): ViaRapida3PSellerReviewsRequest {
    return ViaRapida3PSellerReviewsRequestFromJSONTyped(json, false);
}

export function ViaRapida3PSellerReviewsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapida3PSellerReviewsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sellerId': !exists(json, 'seller_id') ? undefined : json['seller_id'],
    };
}

export function ViaRapida3PSellerReviewsRequestToJSON(value?: ViaRapida3PSellerReviewsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'seller_id': value.sellerId,
    };
}

