/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViaRapidaCheckAgeRegisteredResponse
 */
export interface ViaRapidaCheckAgeRegisteredResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ViaRapidaCheckAgeRegisteredResponse
     */
    checkOver18: boolean;
}

/**
 * Check if a given object implements the ViaRapidaCheckAgeRegisteredResponse interface.
 */
export function instanceOfViaRapidaCheckAgeRegisteredResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "checkOver18" in value;

    return isInstance;
}

export function ViaRapidaCheckAgeRegisteredResponseFromJSON(json: any): ViaRapidaCheckAgeRegisteredResponse {
    return ViaRapidaCheckAgeRegisteredResponseFromJSONTyped(json, false);
}

export function ViaRapidaCheckAgeRegisteredResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaCheckAgeRegisteredResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checkOver18': json['check_over18'],
    };
}

export function ViaRapidaCheckAgeRegisteredResponseToJSON(value?: ViaRapidaCheckAgeRegisteredResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'check_over18': value.checkOver18,
    };
}

