/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViaRapidaUpdatePushNotificationTokenRequest
 */
export interface ViaRapidaUpdatePushNotificationTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaUpdatePushNotificationTokenRequest
     */
    os: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaUpdatePushNotificationTokenRequest
     */
    token: string;
}

/**
 * Check if a given object implements the ViaRapidaUpdatePushNotificationTokenRequest interface.
 */
export function instanceOfViaRapidaUpdatePushNotificationTokenRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "os" in value;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function ViaRapidaUpdatePushNotificationTokenRequestFromJSON(json: any): ViaRapidaUpdatePushNotificationTokenRequest {
    return ViaRapidaUpdatePushNotificationTokenRequestFromJSONTyped(json, false);
}

export function ViaRapidaUpdatePushNotificationTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaUpdatePushNotificationTokenRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'os': json['os'],
        'token': json['token'],
    };
}

export function ViaRapidaUpdatePushNotificationTokenRequestToJSON(value?: ViaRapidaUpdatePushNotificationTokenRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'os': value.os,
        'token': value.token,
    };
}

