/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ViaRapidaDriver } from './ViaRapidaDriver';
import {
    ViaRapidaDriverFromJSON,
    ViaRapidaDriverFromJSONTyped,
    ViaRapidaDriverToJSON,
} from './ViaRapidaDriver';

/**
 * 
 * @export
 * @interface ViaRapidaDeliveryRating
 */
export interface ViaRapidaDeliveryRating {
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaDeliveryRating
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof ViaRapidaDeliveryRating
     */
    deliveryId: number;
    /**
     * 
     * @type {ViaRapidaDriver}
     * @memberof ViaRapidaDeliveryRating
     */
    driver: ViaRapidaDriver;
    /**
     * 
     * @type {number}
     * @memberof ViaRapidaDeliveryRating
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaDeliveryRating
     */
    orderType?: ViaRapidaDeliveryRatingOrderTypeEnum;
    /**
     * 
     * @type {ViaRapidaDriver}
     * @memberof ViaRapidaDeliveryRating
     */
    seller?: ViaRapidaDriver;
}


/**
 * @export
 */
export const ViaRapidaDeliveryRatingOrderTypeEnum = {
    _1p: '1p',
    _3p: '3p',
    Taxi: 'taxi'
} as const;
export type ViaRapidaDeliveryRatingOrderTypeEnum = typeof ViaRapidaDeliveryRatingOrderTypeEnum[keyof typeof ViaRapidaDeliveryRatingOrderTypeEnum];


/**
 * Check if a given object implements the ViaRapidaDeliveryRating interface.
 */
export function instanceOfViaRapidaDeliveryRating(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "deliveryId" in value;
    isInstance = isInstance && "driver" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function ViaRapidaDeliveryRatingFromJSON(json: any): ViaRapidaDeliveryRating {
    return ViaRapidaDeliveryRatingFromJSONTyped(json, false);
}

export function ViaRapidaDeliveryRatingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaDeliveryRating {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': json['date'],
        'deliveryId': json['delivery_id'],
        'driver': ViaRapidaDriverFromJSON(json['driver']),
        'id': json['id'],
        'orderType': !exists(json, 'order_type') ? undefined : json['order_type'],
        'seller': !exists(json, 'seller') ? undefined : ViaRapidaDriverFromJSON(json['seller']),
    };
}

export function ViaRapidaDeliveryRatingToJSON(value?: ViaRapidaDeliveryRating | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date,
        'delivery_id': value.deliveryId,
        'driver': ViaRapidaDriverToJSON(value.driver),
        'id': value.id,
        'order_type': value.orderType,
        'seller': ViaRapidaDriverToJSON(value.seller),
    };
}

