/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CartItem1P } from './CartItem1P';
import {
    CartItem1PFromJSON,
    CartItem1PFromJSONTyped,
    CartItem1PToJSON,
} from './CartItem1P';

/**
 * 
 * @export
 * @interface ViaRapida1PCartDataRequest
 */
export interface ViaRapida1PCartDataRequest {
    /**
     * 
     * @type {string}
     * @memberof ViaRapida1PCartDataRequest
     */
    couponCode?: string;
    /**
     * 
     * @type {Array<CartItem1P>}
     * @memberof ViaRapida1PCartDataRequest
     */
    itemIds?: Array<CartItem1P>;
}

/**
 * Check if a given object implements the ViaRapida1PCartDataRequest interface.
 */
export function instanceOfViaRapida1PCartDataRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ViaRapida1PCartDataRequestFromJSON(json: any): ViaRapida1PCartDataRequest {
    return ViaRapida1PCartDataRequestFromJSONTyped(json, false);
}

export function ViaRapida1PCartDataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapida1PCartDataRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'couponCode': !exists(json, 'coupon_code') ? undefined : json['coupon_code'],
        'itemIds': !exists(json, 'item_ids') ? undefined : ((json['item_ids'] as Array<any>).map(CartItem1PFromJSON)),
    };
}

export function ViaRapida1PCartDataRequestToJSON(value?: ViaRapida1PCartDataRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'coupon_code': value.couponCode,
        'item_ids': value.itemIds === undefined ? undefined : ((value.itemIds as Array<any>).map(CartItem1PToJSON)),
    };
}

