/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViaRapidaTaxiGetSharedOrderStatusRequest
 */
export interface ViaRapidaTaxiGetSharedOrderStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaTaxiGetSharedOrderStatusRequest
     */
    shareId?: string;
}

/**
 * Check if a given object implements the ViaRapidaTaxiGetSharedOrderStatusRequest interface.
 */
export function instanceOfViaRapidaTaxiGetSharedOrderStatusRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ViaRapidaTaxiGetSharedOrderStatusRequestFromJSON(json: any): ViaRapidaTaxiGetSharedOrderStatusRequest {
    return ViaRapidaTaxiGetSharedOrderStatusRequestFromJSONTyped(json, false);
}

export function ViaRapidaTaxiGetSharedOrderStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaTaxiGetSharedOrderStatusRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shareId': !exists(json, 'share_id') ? undefined : json['share_id'],
    };
}

export function ViaRapidaTaxiGetSharedOrderStatusRequestToJSON(value?: ViaRapidaTaxiGetSharedOrderStatusRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'share_id': value.shareId,
    };
}

