/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViaRapidaStoreFetchQuoteRequest
 */
export interface ViaRapidaStoreFetchQuoteRequest {
    /**
     * 
     * @type {number}
     * @memberof ViaRapidaStoreFetchQuoteRequest
     */
    quoteId: number;
}

/**
 * Check if a given object implements the ViaRapidaStoreFetchQuoteRequest interface.
 */
export function instanceOfViaRapidaStoreFetchQuoteRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "quoteId" in value;

    return isInstance;
}

export function ViaRapidaStoreFetchQuoteRequestFromJSON(json: any): ViaRapidaStoreFetchQuoteRequest {
    return ViaRapidaStoreFetchQuoteRequestFromJSONTyped(json, false);
}

export function ViaRapidaStoreFetchQuoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaStoreFetchQuoteRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'quoteId': json['quote_id'],
    };
}

export function ViaRapidaStoreFetchQuoteRequestToJSON(value?: ViaRapidaStoreFetchQuoteRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'quote_id': value.quoteId,
    };
}

