/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViaRapidaStartPhoneValidationResponse
 */
export interface ViaRapidaStartPhoneValidationResponse {
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaStartPhoneValidationResponse
     */
    provider: ViaRapidaStartPhoneValidationResponseProviderEnum;
}


/**
 * @export
 */
export const ViaRapidaStartPhoneValidationResponseProviderEnum = {
    Firebase: 'firebase',
    Twilio: 'twilio',
    Manual: 'manual'
} as const;
export type ViaRapidaStartPhoneValidationResponseProviderEnum = typeof ViaRapidaStartPhoneValidationResponseProviderEnum[keyof typeof ViaRapidaStartPhoneValidationResponseProviderEnum];


/**
 * Check if a given object implements the ViaRapidaStartPhoneValidationResponse interface.
 */
export function instanceOfViaRapidaStartPhoneValidationResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "provider" in value;

    return isInstance;
}

export function ViaRapidaStartPhoneValidationResponseFromJSON(json: any): ViaRapidaStartPhoneValidationResponse {
    return ViaRapidaStartPhoneValidationResponseFromJSONTyped(json, false);
}

export function ViaRapidaStartPhoneValidationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaStartPhoneValidationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'provider': json['provider'],
    };
}

export function ViaRapidaStartPhoneValidationResponseToJSON(value?: ViaRapidaStartPhoneValidationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'provider': value.provider,
    };
}

