/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ViaRapidaPaymentMethod } from './ViaRapidaPaymentMethod';
import {
    ViaRapidaPaymentMethodFromJSON,
    ViaRapidaPaymentMethodFromJSONTyped,
    ViaRapidaPaymentMethodToJSON,
} from './ViaRapidaPaymentMethod';

/**
 * 
 * @export
 * @interface ViaRapidaPaymentMethodsResponse
 */
export interface ViaRapidaPaymentMethodsResponse {
    /**
     * 
     * @type {Array<ViaRapidaPaymentMethod>}
     * @memberof ViaRapidaPaymentMethodsResponse
     */
    paymentMethods?: Array<ViaRapidaPaymentMethod>;
}

/**
 * Check if a given object implements the ViaRapidaPaymentMethodsResponse interface.
 */
export function instanceOfViaRapidaPaymentMethodsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ViaRapidaPaymentMethodsResponseFromJSON(json: any): ViaRapidaPaymentMethodsResponse {
    return ViaRapidaPaymentMethodsResponseFromJSONTyped(json, false);
}

export function ViaRapidaPaymentMethodsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaPaymentMethodsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'paymentMethods': !exists(json, 'payment_methods') ? undefined : ((json['payment_methods'] as Array<any>).map(ViaRapidaPaymentMethodFromJSON)),
    };
}

export function ViaRapidaPaymentMethodsResponseToJSON(value?: ViaRapidaPaymentMethodsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'payment_methods': value.paymentMethods === undefined ? undefined : ((value.paymentMethods as Array<any>).map(ViaRapidaPaymentMethodToJSON)),
    };
}

