/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViaRapidaPhoneValidationPushNotificationChallengeRequest
 */
export interface ViaRapidaPhoneValidationPushNotificationChallengeRequest {
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaPhoneValidationPushNotificationChallengeRequest
     */
    token: string;
}

/**
 * Check if a given object implements the ViaRapidaPhoneValidationPushNotificationChallengeRequest interface.
 */
export function instanceOfViaRapidaPhoneValidationPushNotificationChallengeRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function ViaRapidaPhoneValidationPushNotificationChallengeRequestFromJSON(json: any): ViaRapidaPhoneValidationPushNotificationChallengeRequest {
    return ViaRapidaPhoneValidationPushNotificationChallengeRequestFromJSONTyped(json, false);
}

export function ViaRapidaPhoneValidationPushNotificationChallengeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaPhoneValidationPushNotificationChallengeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function ViaRapidaPhoneValidationPushNotificationChallengeRequestToJSON(value?: ViaRapidaPhoneValidationPushNotificationChallengeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

