/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Coordinates } from './Coordinates';
import {
    CoordinatesFromJSON,
    CoordinatesFromJSONTyped,
    CoordinatesToJSON,
} from './Coordinates';

/**
 * 
 * @export
 * @interface ViaRapidaReverseGeocodeResponseAddress
 */
export interface ViaRapidaReverseGeocodeResponseAddress {
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaReverseGeocodeResponseAddress
     */
    administrativeDivision: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaReverseGeocodeResponseAddress
     */
    city: string;
    /**
     * 
     * @type {Coordinates}
     * @memberof ViaRapidaReverseGeocodeResponseAddress
     */
    coordinates?: Coordinates;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaReverseGeocodeResponseAddress
     */
    country: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaReverseGeocodeResponseAddress
     */
    department?: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaReverseGeocodeResponseAddress
     */
    floor?: string;
    /**
     * 
     * @type {number}
     * @memberof ViaRapidaReverseGeocodeResponseAddress
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaReverseGeocodeResponseAddress
     */
    number?: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaReverseGeocodeResponseAddress
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaReverseGeocodeResponseAddress
     */
    street: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaReverseGeocodeResponseAddress
     */
    zip?: string;
}

/**
 * Check if a given object implements the ViaRapidaReverseGeocodeResponseAddress interface.
 */
export function instanceOfViaRapidaReverseGeocodeResponseAddress(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "administrativeDivision" in value;
    isInstance = isInstance && "city" in value;
    isInstance = isInstance && "country" in value;
    isInstance = isInstance && "street" in value;

    return isInstance;
}

export function ViaRapidaReverseGeocodeResponseAddressFromJSON(json: any): ViaRapidaReverseGeocodeResponseAddress {
    return ViaRapidaReverseGeocodeResponseAddressFromJSONTyped(json, false);
}

export function ViaRapidaReverseGeocodeResponseAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaReverseGeocodeResponseAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'administrativeDivision': json['administrative_division'],
        'city': json['city'],
        'coordinates': !exists(json, 'coordinates') ? undefined : CoordinatesFromJSON(json['coordinates']),
        'country': json['country'],
        'department': !exists(json, 'department') ? undefined : json['department'],
        'floor': !exists(json, 'floor') ? undefined : json['floor'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'number': !exists(json, 'number') ? undefined : json['number'],
        'phoneNumber': !exists(json, 'phone_number') ? undefined : json['phone_number'],
        'street': json['street'],
        'zip': !exists(json, 'zip') ? undefined : json['zip'],
    };
}

export function ViaRapidaReverseGeocodeResponseAddressToJSON(value?: ViaRapidaReverseGeocodeResponseAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'administrative_division': value.administrativeDivision,
        'city': value.city,
        'coordinates': CoordinatesToJSON(value.coordinates),
        'country': value.country,
        'department': value.department,
        'floor': value.floor,
        'id': value.id,
        'number': value.number,
        'phone_number': value.phoneNumber,
        'street': value.street,
        'zip': value.zip,
    };
}

