/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './Money';

/**
 * 
 * @export
 * @interface ViaRapida3PItemOptionOf
 */
export interface ViaRapida3PItemOptionOf {
    /**
     * 
     * @type {number}
     * @memberof ViaRapida3PItemOptionOf
     */
    id: number;
    /**
     * 
     * @type {Money}
     * @memberof ViaRapida3PItemOptionOf
     */
    nextPrice?: Money;
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PItemOptionOf
     */
    optionsGroupName: string;
    /**
     * 
     * @type {Money}
     * @memberof ViaRapida3PItemOptionOf
     */
    price?: Money;
    /**
     * 
     * @type {boolean}
     * @memberof ViaRapida3PItemOptionOf
     */
    priceUpdatePending: boolean;
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PItemOptionOf
     */
    title: string;
}

/**
 * Check if a given object implements the ViaRapida3PItemOptionOf interface.
 */
export function instanceOfViaRapida3PItemOptionOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "optionsGroupName" in value;
    isInstance = isInstance && "priceUpdatePending" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function ViaRapida3PItemOptionOfFromJSON(json: any): ViaRapida3PItemOptionOf {
    return ViaRapida3PItemOptionOfFromJSONTyped(json, false);
}

export function ViaRapida3PItemOptionOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapida3PItemOptionOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nextPrice': !exists(json, 'next_price') ? undefined : MoneyFromJSON(json['next_price']),
        'optionsGroupName': json['options_group_name'],
        'price': !exists(json, 'price') ? undefined : MoneyFromJSON(json['price']),
        'priceUpdatePending': json['price_update_pending'],
        'title': json['title'],
    };
}

export function ViaRapida3PItemOptionOfToJSON(value?: ViaRapida3PItemOptionOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'next_price': MoneyToJSON(value.nextPrice),
        'options_group_name': value.optionsGroupName,
        'price': MoneyToJSON(value.price),
        'price_update_pending': value.priceUpdatePending,
        'title': value.title,
    };
}

