/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViaRapida3PCartItemOptionsGroupSelections
 */
export interface ViaRapida3PCartItemOptionsGroupSelections {
    /**
     * 
     * @type {Array<number>}
     * @memberof ViaRapida3PCartItemOptionsGroupSelections
     */
    optionItemIds: Array<number>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ViaRapida3PCartItemOptionsGroupSelections
     */
    optionItemTitles: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ViaRapida3PCartItemOptionsGroupSelections
     */
    optionsGroupId: number;
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PCartItemOptionsGroupSelections
     */
    optionsGroupTitle: string;
    /**
     * 
     * @type {number}
     * @memberof ViaRapida3PCartItemOptionsGroupSelections
     */
    variantParentId?: number;
}

/**
 * Check if a given object implements the ViaRapida3PCartItemOptionsGroupSelections interface.
 */
export function instanceOfViaRapida3PCartItemOptionsGroupSelections(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "optionItemIds" in value;
    isInstance = isInstance && "optionItemTitles" in value;
    isInstance = isInstance && "optionsGroupId" in value;
    isInstance = isInstance && "optionsGroupTitle" in value;

    return isInstance;
}

export function ViaRapida3PCartItemOptionsGroupSelectionsFromJSON(json: any): ViaRapida3PCartItemOptionsGroupSelections {
    return ViaRapida3PCartItemOptionsGroupSelectionsFromJSONTyped(json, false);
}

export function ViaRapida3PCartItemOptionsGroupSelectionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapida3PCartItemOptionsGroupSelections {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'optionItemIds': json['option_item_ids'],
        'optionItemTitles': json['option_item_titles'],
        'optionsGroupId': json['options_group_id'],
        'optionsGroupTitle': json['options_group_title'],
        'variantParentId': !exists(json, 'variant_parent_id') ? undefined : json['variant_parent_id'],
    };
}

export function ViaRapida3PCartItemOptionsGroupSelectionsToJSON(value?: ViaRapida3PCartItemOptionsGroupSelections | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'option_item_ids': value.optionItemIds,
        'option_item_titles': value.optionItemTitles,
        'options_group_id': value.optionsGroupId,
        'options_group_title': value.optionsGroupTitle,
        'variant_parent_id': value.variantParentId,
    };
}

