/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViaRapidaDeleteAccountRequest
 */
export interface ViaRapidaDeleteAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaDeleteAccountRequest
     */
    store: string;
}

/**
 * Check if a given object implements the ViaRapidaDeleteAccountRequest interface.
 */
export function instanceOfViaRapidaDeleteAccountRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "store" in value;

    return isInstance;
}

export function ViaRapidaDeleteAccountRequestFromJSON(json: any): ViaRapidaDeleteAccountRequest {
    return ViaRapidaDeleteAccountRequestFromJSONTyped(json, false);
}

export function ViaRapidaDeleteAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaDeleteAccountRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'store': json['store'],
    };
}

export function ViaRapidaDeleteAccountRequestToJSON(value?: ViaRapidaDeleteAccountRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'store': value.store,
    };
}

