/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViaRapidaAddEmailRequest
 */
export interface ViaRapidaAddEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaAddEmailRequest
     */
    cuit?: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaAddEmailRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaAddEmailRequest
     */
    firstname: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaAddEmailRequest
     */
    lastname: string;
}

/**
 * Check if a given object implements the ViaRapidaAddEmailRequest interface.
 */
export function instanceOfViaRapidaAddEmailRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "firstname" in value;
    isInstance = isInstance && "lastname" in value;

    return isInstance;
}

export function ViaRapidaAddEmailRequestFromJSON(json: any): ViaRapidaAddEmailRequest {
    return ViaRapidaAddEmailRequestFromJSONTyped(json, false);
}

export function ViaRapidaAddEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaAddEmailRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cuit': !exists(json, 'cuit') ? undefined : json['cuit'],
        'email': json['email'],
        'firstname': json['firstname'],
        'lastname': json['lastname'],
    };
}

export function ViaRapidaAddEmailRequestToJSON(value?: ViaRapidaAddEmailRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cuit': value.cuit,
        'email': value.email,
        'firstname': value.firstname,
        'lastname': value.lastname,
    };
}

