/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViarapidaOrderStatus
 */
export interface ViarapidaOrderStatus {
    /**
     * 
     * @type {string}
     * @memberof ViarapidaOrderStatus
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof ViarapidaOrderStatus
     */
    readable: string;
    /**
     * 
     * @type {number}
     * @memberof ViarapidaOrderStatus
     */
    value: number;
}

/**
 * Check if a given object implements the ViarapidaOrderStatus interface.
 */
export function instanceOfViarapidaOrderStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "readable" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function ViarapidaOrderStatusFromJSON(json: any): ViarapidaOrderStatus {
    return ViarapidaOrderStatusFromJSONTyped(json, false);
}

export function ViarapidaOrderStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViarapidaOrderStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'readable': json['readable'],
        'value': json['value'],
    };
}

export function ViarapidaOrderStatusToJSON(value?: ViarapidaOrderStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'readable': value.readable,
        'value': value.value,
    };
}

