/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Bin } from './Bin';
import {
    BinFromJSON,
    BinFromJSONTyped,
    BinToJSON,
} from './Bin';

/**
 * 
 * @export
 * @interface ViaRapidaCategoriesSearchResponse
 */
export interface ViaRapidaCategoriesSearchResponse {
    /**
     * 
     * @type {Array<Bin>}
     * @memberof ViaRapidaCategoriesSearchResponse
     */
    categories: Array<Bin>;
}

/**
 * Check if a given object implements the ViaRapidaCategoriesSearchResponse interface.
 */
export function instanceOfViaRapidaCategoriesSearchResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "categories" in value;

    return isInstance;
}

export function ViaRapidaCategoriesSearchResponseFromJSON(json: any): ViaRapidaCategoriesSearchResponse {
    return ViaRapidaCategoriesSearchResponseFromJSONTyped(json, false);
}

export function ViaRapidaCategoriesSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaCategoriesSearchResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categories': ((json['categories'] as Array<any>).map(BinFromJSON)),
    };
}

export function ViaRapidaCategoriesSearchResponseToJSON(value?: ViaRapidaCategoriesSearchResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'categories': ((value.categories as Array<any>).map(BinToJSON)),
    };
}

