/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Coordinates } from './Coordinates';
import {
    CoordinatesFromJSON,
    CoordinatesFromJSONTyped,
    CoordinatesToJSON,
} from './Coordinates';

/**
 * 
 * @export
 * @interface ViaRapidaAddAddressRequest
 */
export interface ViaRapidaAddAddressRequest {
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaAddAddressRequest
     */
    administrativeDivision: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaAddAddressRequest
     */
    city: string;
    /**
     * 
     * @type {Coordinates}
     * @memberof ViaRapidaAddAddressRequest
     */
    coordinates?: Coordinates;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaAddAddressRequest
     */
    country: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaAddAddressRequest
     */
    department?: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaAddAddressRequest
     */
    floor?: string;
    /**
     * 
     * @type {number}
     * @memberof ViaRapidaAddAddressRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaAddAddressRequest
     */
    number: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaAddAddressRequest
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaAddAddressRequest
     */
    street: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaAddAddressRequest
     */
    zip?: string;
    /**
     * 
     * @type {number}
     * @memberof ViaRapidaAddAddressRequest
     */
    zoneId?: number;
}

/**
 * Check if a given object implements the ViaRapidaAddAddressRequest interface.
 */
export function instanceOfViaRapidaAddAddressRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "administrativeDivision" in value;
    isInstance = isInstance && "city" in value;
    isInstance = isInstance && "country" in value;
    isInstance = isInstance && "number" in value;
    isInstance = isInstance && "street" in value;

    return isInstance;
}

export function ViaRapidaAddAddressRequestFromJSON(json: any): ViaRapidaAddAddressRequest {
    return ViaRapidaAddAddressRequestFromJSONTyped(json, false);
}

export function ViaRapidaAddAddressRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaAddAddressRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'administrativeDivision': json['administrative_division'],
        'city': json['city'],
        'coordinates': !exists(json, 'coordinates') ? undefined : CoordinatesFromJSON(json['coordinates']),
        'country': json['country'],
        'department': !exists(json, 'department') ? undefined : json['department'],
        'floor': !exists(json, 'floor') ? undefined : json['floor'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'number': json['number'],
        'phoneNumber': !exists(json, 'phone_number') ? undefined : json['phone_number'],
        'street': json['street'],
        'zip': !exists(json, 'zip') ? undefined : json['zip'],
        'zoneId': !exists(json, 'zone_id') ? undefined : json['zone_id'],
    };
}

export function ViaRapidaAddAddressRequestToJSON(value?: ViaRapidaAddAddressRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'administrative_division': value.administrativeDivision,
        'city': value.city,
        'coordinates': CoordinatesToJSON(value.coordinates),
        'country': value.country,
        'department': value.department,
        'floor': value.floor,
        'id': value.id,
        'number': value.number,
        'phone_number': value.phoneNumber,
        'street': value.street,
        'zip': value.zip,
        'zone_id': value.zoneId,
    };
}

