/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViaRapidaProcessEmailConfirmationRequest
 */
export interface ViaRapidaProcessEmailConfirmationRequest {
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaProcessEmailConfirmationRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaProcessEmailConfirmationRequest
     */
    email: string;
}

/**
 * Check if a given object implements the ViaRapidaProcessEmailConfirmationRequest interface.
 */
export function instanceOfViaRapidaProcessEmailConfirmationRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function ViaRapidaProcessEmailConfirmationRequestFromJSON(json: any): ViaRapidaProcessEmailConfirmationRequest {
    return ViaRapidaProcessEmailConfirmationRequestFromJSONTyped(json, false);
}

export function ViaRapidaProcessEmailConfirmationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaProcessEmailConfirmationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'email': json['email'],
    };
}

export function ViaRapidaProcessEmailConfirmationRequestToJSON(value?: ViaRapidaProcessEmailConfirmationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'email': value.email,
    };
}

