/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ViaRapida3PItem } from './ViaRapida3PItem';
import {
    ViaRapida3PItemFromJSON,
    ViaRapida3PItemFromJSONTyped,
    ViaRapida3PItemToJSON,
} from './ViaRapida3PItem';

/**
 * 
 * @export
 * @interface ViaRapida3PCategory
 */
export interface ViaRapida3PCategory {
    /**
     * 
     * @type {number}
     * @memberof ViaRapida3PCategory
     */
    id: number;
    /**
     * 
     * @type {Array<ViaRapida3PItem>}
     * @memberof ViaRapida3PCategory
     */
    items?: Array<ViaRapida3PItem>;
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PCategory
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ViaRapida3PCategory
     */
    sellerId: number;
}

/**
 * Check if a given object implements the ViaRapida3PCategory interface.
 */
export function instanceOfViaRapida3PCategory(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "sellerId" in value;

    return isInstance;
}

export function ViaRapida3PCategoryFromJSON(json: any): ViaRapida3PCategory {
    return ViaRapida3PCategoryFromJSONTyped(json, false);
}

export function ViaRapida3PCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapida3PCategory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(ViaRapida3PItemFromJSON)),
        'name': json['name'],
        'sellerId': json['seller_id'],
    };
}

export function ViaRapida3PCategoryToJSON(value?: ViaRapida3PCategory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(ViaRapida3PItemToJSON)),
        'name': value.name,
        'seller_id': value.sellerId,
    };
}

