/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ViaRapida3PItemOptionsGroupOption } from './ViaRapida3PItemOptionsGroupOption';
import {
    ViaRapida3PItemOptionsGroupOptionFromJSON,
    ViaRapida3PItemOptionsGroupOptionFromJSONTyped,
    ViaRapida3PItemOptionsGroupOptionToJSON,
} from './ViaRapida3PItemOptionsGroupOption';

/**
 * 
 * @export
 * @interface ViaRapida3PItemOptionsGroup
 */
export interface ViaRapida3PItemOptionsGroup {
    /**
     * 
     * @type {number}
     * @memberof ViaRapida3PItemOptionsGroup
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof ViaRapida3PItemOptionsGroup
     */
    maxAllowed: number;
    /**
     * 
     * @type {number}
     * @memberof ViaRapida3PItemOptionsGroup
     */
    minRequired: number;
    /**
     * 
     * @type {Array<ViaRapida3PItemOptionsGroupOption>}
     * @memberof ViaRapida3PItemOptionsGroup
     */
    options: Array<ViaRapida3PItemOptionsGroupOption>;
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PItemOptionsGroup
     */
    title: string;
}

/**
 * Check if a given object implements the ViaRapida3PItemOptionsGroup interface.
 */
export function instanceOfViaRapida3PItemOptionsGroup(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "maxAllowed" in value;
    isInstance = isInstance && "minRequired" in value;
    isInstance = isInstance && "options" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function ViaRapida3PItemOptionsGroupFromJSON(json: any): ViaRapida3PItemOptionsGroup {
    return ViaRapida3PItemOptionsGroupFromJSONTyped(json, false);
}

export function ViaRapida3PItemOptionsGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapida3PItemOptionsGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'maxAllowed': json['max_allowed'],
        'minRequired': json['min_required'],
        'options': ((json['options'] as Array<any>).map(ViaRapida3PItemOptionsGroupOptionFromJSON)),
        'title': json['title'],
    };
}

export function ViaRapida3PItemOptionsGroupToJSON(value?: ViaRapida3PItemOptionsGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'max_allowed': value.maxAllowed,
        'min_required': value.minRequired,
        'options': ((value.options as Array<any>).map(ViaRapida3PItemOptionsGroupOptionToJSON)),
        'title': value.title,
    };
}

