/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ViaRapidaTaxiOrderStatus } from './ViaRapidaTaxiOrderStatus';
import {
    ViaRapidaTaxiOrderStatusFromJSON,
    ViaRapidaTaxiOrderStatusFromJSONTyped,
    ViaRapidaTaxiOrderStatusToJSON,
} from './ViaRapidaTaxiOrderStatus';

/**
 * 
 * @export
 * @interface ViaRapidaTaxiGetSharedOrderStatusResponse
 */
export interface ViaRapidaTaxiGetSharedOrderStatusResponse {
    /**
     * 
     * @type {ViaRapidaTaxiOrderStatus}
     * @memberof ViaRapidaTaxiGetSharedOrderStatusResponse
     */
    order?: ViaRapidaTaxiOrderStatus;
}

/**
 * Check if a given object implements the ViaRapidaTaxiGetSharedOrderStatusResponse interface.
 */
export function instanceOfViaRapidaTaxiGetSharedOrderStatusResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ViaRapidaTaxiGetSharedOrderStatusResponseFromJSON(json: any): ViaRapidaTaxiGetSharedOrderStatusResponse {
    return ViaRapidaTaxiGetSharedOrderStatusResponseFromJSONTyped(json, false);
}

export function ViaRapidaTaxiGetSharedOrderStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaTaxiGetSharedOrderStatusResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'order': !exists(json, 'order') ? undefined : ViaRapidaTaxiOrderStatusFromJSON(json['order']),
    };
}

export function ViaRapidaTaxiGetSharedOrderStatusResponseToJSON(value?: ViaRapidaTaxiGetSharedOrderStatusResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order': ViaRapidaTaxiOrderStatusToJSON(value.order),
    };
}

