/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ViaRapidaProcessDeliveryRating } from './ViaRapidaProcessDeliveryRating';
import {
    ViaRapidaProcessDeliveryRatingFromJSON,
    ViaRapidaProcessDeliveryRatingFromJSONTyped,
    ViaRapidaProcessDeliveryRatingToJSON,
} from './ViaRapidaProcessDeliveryRating';

/**
 * 
 * @export
 * @interface ViaRapidaProcessDeliveryRatingsRequest
 */
export interface ViaRapidaProcessDeliveryRatingsRequest {
    /**
     * 
     * @type {Array<ViaRapidaProcessDeliveryRating>}
     * @memberof ViaRapidaProcessDeliveryRatingsRequest
     */
    ratings?: Array<ViaRapidaProcessDeliveryRating>;
}

/**
 * Check if a given object implements the ViaRapidaProcessDeliveryRatingsRequest interface.
 */
export function instanceOfViaRapidaProcessDeliveryRatingsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ViaRapidaProcessDeliveryRatingsRequestFromJSON(json: any): ViaRapidaProcessDeliveryRatingsRequest {
    return ViaRapidaProcessDeliveryRatingsRequestFromJSONTyped(json, false);
}

export function ViaRapidaProcessDeliveryRatingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaProcessDeliveryRatingsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ratings': !exists(json, 'ratings') ? undefined : ((json['ratings'] as Array<any>).map(ViaRapidaProcessDeliveryRatingFromJSON)),
    };
}

export function ViaRapidaProcessDeliveryRatingsRequestToJSON(value?: ViaRapidaProcessDeliveryRatingsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ratings': value.ratings === undefined ? undefined : ((value.ratings as Array<any>).map(ViaRapidaProcessDeliveryRatingToJSON)),
    };
}

