/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MercadoPagoAuthorization } from './MercadoPagoAuthorization';
import {
    MercadoPagoAuthorizationFromJSON,
    MercadoPagoAuthorizationFromJSONTyped,
    MercadoPagoAuthorizationToJSON,
} from './MercadoPagoAuthorization';
import type { ViaRapida3PCart } from './ViaRapida3PCart';
import {
    ViaRapida3PCartFromJSON,
    ViaRapida3PCartFromJSONTyped,
    ViaRapida3PCartToJSON,
} from './ViaRapida3PCart';

/**
 * 
 * @export
 * @interface ViaRapida3PMercadoPagoCheckout
 */
export interface ViaRapida3PMercadoPagoCheckout {
    /**
     * 
     * @type {MercadoPagoAuthorization}
     * @memberof ViaRapida3PMercadoPagoCheckout
     */
    authorization: MercadoPagoAuthorization;
    /**
     * 
     * @type {ViaRapida3PCart}
     * @memberof ViaRapida3PMercadoPagoCheckout
     */
    cart: ViaRapida3PCart;
    /**
     * 
     * @type {boolean}
     * @memberof ViaRapida3PMercadoPagoCheckout
     */
    useBalance?: boolean;
}

/**
 * Check if a given object implements the ViaRapida3PMercadoPagoCheckout interface.
 */
export function instanceOfViaRapida3PMercadoPagoCheckout(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "authorization" in value;
    isInstance = isInstance && "cart" in value;

    return isInstance;
}

export function ViaRapida3PMercadoPagoCheckoutFromJSON(json: any): ViaRapida3PMercadoPagoCheckout {
    return ViaRapida3PMercadoPagoCheckoutFromJSONTyped(json, false);
}

export function ViaRapida3PMercadoPagoCheckoutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapida3PMercadoPagoCheckout {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authorization': MercadoPagoAuthorizationFromJSON(json['authorization']),
        'cart': ViaRapida3PCartFromJSON(json['cart']),
        'useBalance': !exists(json, 'use_balance') ? undefined : json['use_balance'],
    };
}

export function ViaRapida3PMercadoPagoCheckoutToJSON(value?: ViaRapida3PMercadoPagoCheckout | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authorization': MercadoPagoAuthorizationToJSON(value.authorization),
        'cart': ViaRapida3PCartToJSON(value.cart),
        'use_balance': value.useBalance,
    };
}

