/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ViaRapida3PCart } from './ViaRapida3PCart';
import {
    ViaRapida3PCartFromJSON,
    ViaRapida3PCartFromJSONTyped,
    ViaRapida3PCartToJSON,
} from './ViaRapida3PCart';

/**
 * 
 * @export
 * @interface ViaRapida3PCashCheckout
 */
export interface ViaRapida3PCashCheckout {
    /**
     * 
     * @type {ViaRapida3PCart}
     * @memberof ViaRapida3PCashCheckout
     */
    cart: ViaRapida3PCart;
    /**
     * 
     * @type {boolean}
     * @memberof ViaRapida3PCashCheckout
     */
    useBalance?: boolean;
}

/**
 * Check if a given object implements the ViaRapida3PCashCheckout interface.
 */
export function instanceOfViaRapida3PCashCheckout(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cart" in value;

    return isInstance;
}

export function ViaRapida3PCashCheckoutFromJSON(json: any): ViaRapida3PCashCheckout {
    return ViaRapida3PCashCheckoutFromJSONTyped(json, false);
}

export function ViaRapida3PCashCheckoutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapida3PCashCheckout {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cart': ViaRapida3PCartFromJSON(json['cart']),
        'useBalance': !exists(json, 'use_balance') ? undefined : json['use_balance'],
    };
}

export function ViaRapida3PCashCheckoutToJSON(value?: ViaRapida3PCashCheckout | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cart': ViaRapida3PCartToJSON(value.cart),
        'use_balance': value.useBalance,
    };
}

