/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViaRapidaProcessDeliveryRatingsResponse
 */
export interface ViaRapidaProcessDeliveryRatingsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ViaRapidaProcessDeliveryRatingsResponse
     */
    modalVisible: boolean;
}

/**
 * Check if a given object implements the ViaRapidaProcessDeliveryRatingsResponse interface.
 */
export function instanceOfViaRapidaProcessDeliveryRatingsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "modalVisible" in value;

    return isInstance;
}

export function ViaRapidaProcessDeliveryRatingsResponseFromJSON(json: any): ViaRapidaProcessDeliveryRatingsResponse {
    return ViaRapidaProcessDeliveryRatingsResponseFromJSONTyped(json, false);
}

export function ViaRapidaProcessDeliveryRatingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaProcessDeliveryRatingsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'modalVisible': json['modal_visible'],
    };
}

export function ViaRapidaProcessDeliveryRatingsResponseToJSON(value?: ViaRapidaProcessDeliveryRatingsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'modal_visible': value.modalVisible,
    };
}

