/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Coordinates } from './Coordinates';
import {
    CoordinatesFromJSON,
    CoordinatesFromJSONTyped,
    CoordinatesToJSON,
} from './Coordinates';

/**
 * 
 * @export
 * @interface ViaRapidaReverseGeocodeRequest
 */
export interface ViaRapidaReverseGeocodeRequest {
    /**
     * 
     * @type {Coordinates}
     * @memberof ViaRapidaReverseGeocodeRequest
     */
    coordinates: Coordinates;
}

/**
 * Check if a given object implements the ViaRapidaReverseGeocodeRequest interface.
 */
export function instanceOfViaRapidaReverseGeocodeRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "coordinates" in value;

    return isInstance;
}

export function ViaRapidaReverseGeocodeRequestFromJSON(json: any): ViaRapidaReverseGeocodeRequest {
    return ViaRapidaReverseGeocodeRequestFromJSONTyped(json, false);
}

export function ViaRapidaReverseGeocodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaReverseGeocodeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'coordinates': CoordinatesFromJSON(json['coordinates']),
    };
}

export function ViaRapidaReverseGeocodeRequestToJSON(value?: ViaRapidaReverseGeocodeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'coordinates': CoordinatesToJSON(value.coordinates),
    };
}

