/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './Money';
import type { ViaRapida3PCartItemOptionsGroupSelections } from './ViaRapida3PCartItemOptionsGroupSelections';
import {
    ViaRapida3PCartItemOptionsGroupSelectionsFromJSON,
    ViaRapida3PCartItemOptionsGroupSelectionsFromJSONTyped,
    ViaRapida3PCartItemOptionsGroupSelectionsToJSON,
} from './ViaRapida3PCartItemOptionsGroupSelections';

/**
 * 
 * @export
 * @interface ViaRapida3PCartItem
 */
export interface ViaRapida3PCartItem {
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PCartItem
     */
    notes?: string;
    /**
     * 
     * @type {Array<ViaRapida3PCartItemOptionsGroupSelections>}
     * @memberof ViaRapida3PCartItem
     */
    options?: Array<ViaRapida3PCartItemOptionsGroupSelections>;
    /**
     * 
     * @type {number}
     * @memberof ViaRapida3PCartItem
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PCartItem
     */
    rowId: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PCartItem
     */
    sourceId: string;
    /**
     * 
     * @type {Money}
     * @memberof ViaRapida3PCartItem
     */
    total: Money;
}

/**
 * Check if a given object implements the ViaRapida3PCartItem interface.
 */
export function instanceOfViaRapida3PCartItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "quantity" in value;
    isInstance = isInstance && "rowId" in value;
    isInstance = isInstance && "sourceId" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function ViaRapida3PCartItemFromJSON(json: any): ViaRapida3PCartItem {
    return ViaRapida3PCartItemFromJSONTyped(json, false);
}

export function ViaRapida3PCartItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapida3PCartItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'options': !exists(json, 'options') ? undefined : ((json['options'] as Array<any>).map(ViaRapida3PCartItemOptionsGroupSelectionsFromJSON)),
        'quantity': json['quantity'],
        'rowId': json['row_id'],
        'sourceId': json['source_id'],
        'total': MoneyFromJSON(json['total']),
    };
}

export function ViaRapida3PCartItemToJSON(value?: ViaRapida3PCartItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'notes': value.notes,
        'options': value.options === undefined ? undefined : ((value.options as Array<any>).map(ViaRapida3PCartItemOptionsGroupSelectionsToJSON)),
        'quantity': value.quantity,
        'row_id': value.rowId,
        'source_id': value.sourceId,
        'total': MoneyToJSON(value.total),
    };
}

