/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Coordinates } from './Coordinates';
import {
    CoordinatesFromJSON,
    CoordinatesFromJSONTyped,
    CoordinatesToJSON,
} from './Coordinates';

/**
 * 
 * @export
 * @interface ViaRapidaTaxiEstimateRouteRequest
 */
export interface ViaRapidaTaxiEstimateRouteRequest {
    /**
     * 
     * @type {Coordinates}
     * @memberof ViaRapidaTaxiEstimateRouteRequest
     */
    origin: Coordinates;
    /**
     * 
     * @type {Array<Coordinates>}
     * @memberof ViaRapidaTaxiEstimateRouteRequest
     */
    waypoints: Array<Coordinates>;
}

/**
 * Check if a given object implements the ViaRapidaTaxiEstimateRouteRequest interface.
 */
export function instanceOfViaRapidaTaxiEstimateRouteRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "origin" in value;
    isInstance = isInstance && "waypoints" in value;

    return isInstance;
}

export function ViaRapidaTaxiEstimateRouteRequestFromJSON(json: any): ViaRapidaTaxiEstimateRouteRequest {
    return ViaRapidaTaxiEstimateRouteRequestFromJSONTyped(json, false);
}

export function ViaRapidaTaxiEstimateRouteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaTaxiEstimateRouteRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'origin': CoordinatesFromJSON(json['origin']),
        'waypoints': ((json['waypoints'] as Array<any>).map(CoordinatesFromJSON)),
    };
}

export function ViaRapidaTaxiEstimateRouteRequestToJSON(value?: ViaRapidaTaxiEstimateRouteRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'origin': CoordinatesToJSON(value.origin),
        'waypoints': ((value.waypoints as Array<any>).map(CoordinatesToJSON)),
    };
}

