/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DeliveryPrices } from './DeliveryPrices';
import {
    DeliveryPricesFromJSON,
    DeliveryPricesFromJSONTyped,
    DeliveryPricesToJSON,
} from './DeliveryPrices';
import type { Item } from './Item';
import {
    ItemFromJSON,
    ItemFromJSONTyped,
    ItemToJSON,
} from './Item';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './Money';
import type { ShortAddress } from './ShortAddress';
import {
    ShortAddressFromJSON,
    ShortAddressFromJSONTyped,
    ShortAddressToJSON,
} from './ShortAddress';

/**
 * 
 * @export
 * @interface ViaRapida1PCartDataResponse
 */
export interface ViaRapida1PCartDataResponse {
    /**
     * 
     * @type {Money}
     * @memberof ViaRapida1PCartDataResponse
     */
    balance?: Money;
    /**
     * 
     * @type {string}
     * @memberof ViaRapida1PCartDataResponse
     */
    couponCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapida1PCartDataResponse
     */
    couponStatus?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ViaRapida1PCartDataResponse
     */
    customerPickupOnlyEnabled?: boolean;
    /**
     * 
     * @type {DeliveryPrices}
     * @memberof ViaRapida1PCartDataResponse
     */
    deliveryPrices: DeliveryPrices;
    /**
     * 
     * @type {number}
     * @memberof ViaRapida1PCartDataResponse
     */
    deliveryZone: number;
    /**
     * 
     * @type {Array<Item>}
     * @memberof ViaRapida1PCartDataResponse
     */
    items?: Array<Item>;
    /**
     * 
     * @type {Money}
     * @memberof ViaRapida1PCartDataResponse
     */
    minSalesAmount: Money;
    /**
     * 
     * @type {boolean}
     * @memberof ViaRapida1PCartDataResponse
     */
    phoneValidationRequired: boolean;
    /**
     * 
     * @type {ShortAddress}
     * @memberof ViaRapida1PCartDataResponse
     */
    warehouse?: ShortAddress;
}

/**
 * Check if a given object implements the ViaRapida1PCartDataResponse interface.
 */
export function instanceOfViaRapida1PCartDataResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "deliveryPrices" in value;
    isInstance = isInstance && "deliveryZone" in value;
    isInstance = isInstance && "minSalesAmount" in value;
    isInstance = isInstance && "phoneValidationRequired" in value;

    return isInstance;
}

export function ViaRapida1PCartDataResponseFromJSON(json: any): ViaRapida1PCartDataResponse {
    return ViaRapida1PCartDataResponseFromJSONTyped(json, false);
}

export function ViaRapida1PCartDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapida1PCartDataResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'balance': !exists(json, 'balance') ? undefined : MoneyFromJSON(json['balance']),
        'couponCode': !exists(json, 'coupon_code') ? undefined : json['coupon_code'],
        'couponStatus': !exists(json, 'coupon_status') ? undefined : json['coupon_status'],
        'customerPickupOnlyEnabled': !exists(json, 'customer_pickup_only_enabled') ? undefined : json['customer_pickup_only_enabled'],
        'deliveryPrices': DeliveryPricesFromJSON(json['delivery_prices']),
        'deliveryZone': json['delivery_zone'],
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(ItemFromJSON)),
        'minSalesAmount': MoneyFromJSON(json['min_sales_amount']),
        'phoneValidationRequired': json['phone_validation_required'],
        'warehouse': !exists(json, 'warehouse') ? undefined : ShortAddressFromJSON(json['warehouse']),
    };
}

export function ViaRapida1PCartDataResponseToJSON(value?: ViaRapida1PCartDataResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'balance': MoneyToJSON(value.balance),
        'coupon_code': value.couponCode,
        'coupon_status': value.couponStatus,
        'customer_pickup_only_enabled': value.customerPickupOnlyEnabled,
        'delivery_prices': DeliveryPricesToJSON(value.deliveryPrices),
        'delivery_zone': value.deliveryZone,
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(ItemToJSON)),
        'min_sales_amount': MoneyToJSON(value.minSalesAmount),
        'phone_validation_required': value.phoneValidationRequired,
        'warehouse': ShortAddressToJSON(value.warehouse),
    };
}

