/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ImageMetadata } from './ImageMetadata';
import {
    ImageMetadataFromJSON,
    ImageMetadataFromJSONTyped,
    ImageMetadataToJSON,
} from './ImageMetadata';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './Money';
import type { ViaRapida3PItemOptionOf } from './ViaRapida3PItemOptionOf';
import {
    ViaRapida3PItemOptionOfFromJSON,
    ViaRapida3PItemOptionOfFromJSONTyped,
    ViaRapida3PItemOptionOfToJSON,
} from './ViaRapida3PItemOptionOf';

/**
 * 
 * @export
 * @interface ViaRapida3PItemOptionsGroupOptionItem
 */
export interface ViaRapida3PItemOptionsGroupOptionItem {
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PItemOptionsGroupOptionItem
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PItemOptionsGroupOptionItem
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ViaRapida3PItemOptionsGroupOptionItem
     */
    id: number;
    /**
     * 
     * @type {Array<ImageMetadata>}
     * @memberof ViaRapida3PItemOptionsGroupOptionItem
     */
    images?: Array<ImageMetadata>;
    /**
     * 
     * @type {boolean}
     * @memberof ViaRapida3PItemOptionsGroupOptionItem
     */
    isAvailable: boolean;
    /**
     * 
     * @type {Money}
     * @memberof ViaRapida3PItemOptionsGroupOptionItem
     */
    nextPrice?: Money;
    /**
     * 
     * @type {Array<ViaRapida3PItemOptionOf>}
     * @memberof ViaRapida3PItemOptionsGroupOptionItem
     */
    optionOf?: Array<ViaRapida3PItemOptionOf>;
    /**
     * 
     * @type {number}
     * @memberof ViaRapida3PItemOptionsGroupOptionItem
     */
    parent?: number;
    /**
     * 
     * @type {Money}
     * @memberof ViaRapida3PItemOptionsGroupOptionItem
     */
    price: Money;
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PItemOptionsGroupOptionItem
     */
    shareLink?: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PItemOptionsGroupOptionItem
     */
    shareLinkMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PItemOptionsGroupOptionItem
     */
    title: string;
}

/**
 * Check if a given object implements the ViaRapida3PItemOptionsGroupOptionItem interface.
 */
export function instanceOfViaRapida3PItemOptionsGroupOptionItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "category" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "isAvailable" in value;
    isInstance = isInstance && "price" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function ViaRapida3PItemOptionsGroupOptionItemFromJSON(json: any): ViaRapida3PItemOptionsGroupOptionItem {
    return ViaRapida3PItemOptionsGroupOptionItemFromJSONTyped(json, false);
}

export function ViaRapida3PItemOptionsGroupOptionItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapida3PItemOptionsGroupOptionItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'category': json['category'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'id': json['id'],
        'images': !exists(json, 'images') ? undefined : ((json['images'] as Array<any>).map(ImageMetadataFromJSON)),
        'isAvailable': json['is_available'],
        'nextPrice': !exists(json, 'next_price') ? undefined : MoneyFromJSON(json['next_price']),
        'optionOf': !exists(json, 'option_of') ? undefined : ((json['option_of'] as Array<any>).map(ViaRapida3PItemOptionOfFromJSON)),
        'parent': !exists(json, 'parent') ? undefined : json['parent'],
        'price': MoneyFromJSON(json['price']),
        'shareLink': !exists(json, 'share_link') ? undefined : json['share_link'],
        'shareLinkMessage': !exists(json, 'share_link_message') ? undefined : json['share_link_message'],
        'title': json['title'],
    };
}

export function ViaRapida3PItemOptionsGroupOptionItemToJSON(value?: ViaRapida3PItemOptionsGroupOptionItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'category': value.category,
        'description': value.description,
        'id': value.id,
        'images': value.images === undefined ? undefined : ((value.images as Array<any>).map(ImageMetadataToJSON)),
        'is_available': value.isAvailable,
        'next_price': MoneyToJSON(value.nextPrice),
        'option_of': value.optionOf === undefined ? undefined : ((value.optionOf as Array<any>).map(ViaRapida3PItemOptionOfToJSON)),
        'parent': value.parent,
        'price': MoneyToJSON(value.price),
        'share_link': value.shareLink,
        'share_link_message': value.shareLinkMessage,
        'title': value.title,
    };
}

