/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ShortAddress } from './ShortAddress';
import {
    ShortAddressFromJSON,
    ShortAddressFromJSONTyped,
    ShortAddressToJSON,
} from './ShortAddress';

/**
 * 
 * @export
 * @interface ViaRapidaListAddressesResponse
 */
export interface ViaRapidaListAddressesResponse {
    /**
     * 
     * @type {Array<ShortAddress>}
     * @memberof ViaRapidaListAddressesResponse
     */
    addresses?: Array<ShortAddress>;
    /**
     * 
     * @type {number}
     * @memberof ViaRapidaListAddressesResponse
     */
    defaultZoneId: number;
    /**
     * 
     * @type {number}
     * @memberof ViaRapidaListAddressesResponse
     */
    taxiZoneId?: number;
}

/**
 * Check if a given object implements the ViaRapidaListAddressesResponse interface.
 */
export function instanceOfViaRapidaListAddressesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "defaultZoneId" in value;

    return isInstance;
}

export function ViaRapidaListAddressesResponseFromJSON(json: any): ViaRapidaListAddressesResponse {
    return ViaRapidaListAddressesResponseFromJSONTyped(json, false);
}

export function ViaRapidaListAddressesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaListAddressesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addresses': !exists(json, 'addresses') ? undefined : ((json['addresses'] as Array<any>).map(ShortAddressFromJSON)),
        'defaultZoneId': json['default_zone_id'],
        'taxiZoneId': !exists(json, 'taxi_zone_id') ? undefined : json['taxi_zone_id'],
    };
}

export function ViaRapidaListAddressesResponseToJSON(value?: ViaRapidaListAddressesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addresses': value.addresses === undefined ? undefined : ((value.addresses as Array<any>).map(ShortAddressToJSON)),
        'default_zone_id': value.defaultZoneId,
        'taxi_zone_id': value.taxiZoneId,
    };
}

