/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ViaRapida3PSellerEvent } from './ViaRapida3PSellerEvent';
import {
    ViaRapida3PSellerEventFromJSON,
    ViaRapida3PSellerEventFromJSONTyped,
    ViaRapida3PSellerEventToJSON,
} from './ViaRapida3PSellerEvent';

/**
 * 
 * @export
 * @interface ViaRapida3PSellersEventsResponse
 */
export interface ViaRapida3PSellersEventsResponse {
    /**
     * 
     * @type {Array<ViaRapida3PSellerEvent>}
     * @memberof ViaRapida3PSellersEventsResponse
     */
    events?: Array<ViaRapida3PSellerEvent>;
}

/**
 * Check if a given object implements the ViaRapida3PSellersEventsResponse interface.
 */
export function instanceOfViaRapida3PSellersEventsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ViaRapida3PSellersEventsResponseFromJSON(json: any): ViaRapida3PSellersEventsResponse {
    return ViaRapida3PSellersEventsResponseFromJSONTyped(json, false);
}

export function ViaRapida3PSellersEventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapida3PSellersEventsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'events': !exists(json, 'events') ? undefined : ((json['events'] as Array<any>).map(ViaRapida3PSellerEventFromJSON)),
    };
}

export function ViaRapida3PSellersEventsResponseToJSON(value?: ViaRapida3PSellersEventsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'events': value.events === undefined ? undefined : ((value.events as Array<any>).map(ViaRapida3PSellerEventToJSON)),
    };
}

