/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './Money';

/**
 * 
 * @export
 * @interface ViaRapidaPaymentMethodPerception
 */
export interface ViaRapidaPaymentMethodPerception {
    /**
     * 
     * @type {string}
     * @memberof ViaRapidaPaymentMethodPerception
     */
    name: string;
    /**
     * 
     * @type {Money}
     * @memberof ViaRapidaPaymentMethodPerception
     */
    total: Money;
}

/**
 * Check if a given object implements the ViaRapidaPaymentMethodPerception interface.
 */
export function instanceOfViaRapidaPaymentMethodPerception(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function ViaRapidaPaymentMethodPerceptionFromJSON(json: any): ViaRapidaPaymentMethodPerception {
    return ViaRapidaPaymentMethodPerceptionFromJSONTyped(json, false);
}

export function ViaRapidaPaymentMethodPerceptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaPaymentMethodPerception {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'total': MoneyFromJSON(json['total']),
    };
}

export function ViaRapidaPaymentMethodPerceptionToJSON(value?: ViaRapidaPaymentMethodPerception | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'total': MoneyToJSON(value.total),
    };
}

