/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
} from './Money';
import type { Route } from './Route';
import {
    RouteFromJSON,
    RouteFromJSONTyped,
    RouteToJSON,
} from './Route';

/**
 * 
 * @export
 * @interface ViaRapidaTaxiEstimateRouteResponse
 */
export interface ViaRapidaTaxiEstimateRouteResponse {
    /**
     * 
     * @type {Money}
     * @memberof ViaRapidaTaxiEstimateRouteResponse
     */
    estimationHigh?: Money;
    /**
     * 
     * @type {Money}
     * @memberof ViaRapidaTaxiEstimateRouteResponse
     */
    estimationLow?: Money;
    /**
     * 
     * @type {Route}
     * @memberof ViaRapidaTaxiEstimateRouteResponse
     */
    route?: Route;
    /**
     * 
     * @type {boolean}
     * @memberof ViaRapidaTaxiEstimateRouteResponse
     */
    taxisAvailable: boolean;
}

/**
 * Check if a given object implements the ViaRapidaTaxiEstimateRouteResponse interface.
 */
export function instanceOfViaRapidaTaxiEstimateRouteResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "taxisAvailable" in value;

    return isInstance;
}

export function ViaRapidaTaxiEstimateRouteResponseFromJSON(json: any): ViaRapidaTaxiEstimateRouteResponse {
    return ViaRapidaTaxiEstimateRouteResponseFromJSONTyped(json, false);
}

export function ViaRapidaTaxiEstimateRouteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapidaTaxiEstimateRouteResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'estimationHigh': !exists(json, 'estimation_high') ? undefined : MoneyFromJSON(json['estimation_high']),
        'estimationLow': !exists(json, 'estimation_low') ? undefined : MoneyFromJSON(json['estimation_low']),
        'route': !exists(json, 'route') ? undefined : RouteFromJSON(json['route']),
        'taxisAvailable': json['taxis_available'],
    };
}

export function ViaRapidaTaxiEstimateRouteResponseToJSON(value?: ViaRapidaTaxiEstimateRouteResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'estimation_high': MoneyToJSON(value.estimationHigh),
        'estimation_low': MoneyToJSON(value.estimationLow),
        'route': RouteToJSON(value.route),
        'taxis_available': value.taxisAvailable,
    };
}

