/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViaRapida3PSellersEventsRequest
 */
export interface ViaRapida3PSellersEventsRequest {
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PSellersEventsRequest
     */
    storeType?: string;
}

/**
 * Check if a given object implements the ViaRapida3PSellersEventsRequest interface.
 */
export function instanceOfViaRapida3PSellersEventsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ViaRapida3PSellersEventsRequestFromJSON(json: any): ViaRapida3PSellersEventsRequest {
    return ViaRapida3PSellersEventsRequestFromJSONTyped(json, false);
}

export function ViaRapida3PSellersEventsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapida3PSellersEventsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'storeType': !exists(json, 'store_type') ? undefined : json['store_type'],
    };
}

export function ViaRapida3PSellersEventsRequestToJSON(value?: ViaRapida3PSellersEventsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'store_type': value.storeType,
    };
}

