/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ViaRapida3PCartItem } from './ViaRapida3PCartItem';
import {
    ViaRapida3PCartItemFromJSON,
    ViaRapida3PCartItemFromJSONTyped,
    ViaRapida3PCartItemToJSON,
} from './ViaRapida3PCartItem';

/**
 * 
 * @export
 * @interface ViaRapida3PCartDataRequest
 */
export interface ViaRapida3PCartDataRequest {
    /**
     * 
     * @type {number}
     * @memberof ViaRapida3PCartDataRequest
     */
    addressId?: number;
    /**
     * 
     * @type {Array<ViaRapida3PCartItem>}
     * @memberof ViaRapida3PCartDataRequest
     */
    cartItems?: Array<ViaRapida3PCartItem>;
    /**
     * 
     * @type {string}
     * @memberof ViaRapida3PCartDataRequest
     */
    couponCode?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ViaRapida3PCartDataRequest
     */
    quoteIds?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof ViaRapida3PCartDataRequest
     */
    sellerId: number;
}

/**
 * Check if a given object implements the ViaRapida3PCartDataRequest interface.
 */
export function instanceOfViaRapida3PCartDataRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sellerId" in value;

    return isInstance;
}

export function ViaRapida3PCartDataRequestFromJSON(json: any): ViaRapida3PCartDataRequest {
    return ViaRapida3PCartDataRequestFromJSONTyped(json, false);
}

export function ViaRapida3PCartDataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViaRapida3PCartDataRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addressId': !exists(json, 'address_id') ? undefined : json['address_id'],
        'cartItems': !exists(json, 'cart_items') ? undefined : ((json['cart_items'] as Array<any>).map(ViaRapida3PCartItemFromJSON)),
        'couponCode': !exists(json, 'coupon_code') ? undefined : json['coupon_code'],
        'quoteIds': !exists(json, 'quote_ids') ? undefined : json['quote_ids'],
        'sellerId': json['seller_id'],
    };
}

export function ViaRapida3PCartDataRequestToJSON(value?: ViaRapida3PCartDataRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address_id': value.addressId,
        'cart_items': value.cartItems === undefined ? undefined : ((value.cartItems as Array<any>).map(ViaRapida3PCartItemToJSON)),
        'coupon_code': value.couponCode,
        'quote_ids': value.quoteIds,
        'seller_id': value.sellerId,
    };
}

