/* tslint:disable */
/* eslint-disable */
/**
 * ViaRapida API
 * ViaRapida API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contacto@viarapida.com.ar
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ZoneInformation
 */
export interface ZoneInformation {
    /**
     * 
     * @type {string}
     * @memberof ZoneInformation
     */
    expDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ZoneInformation
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof ZoneInformation
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof ZoneInformation
     */
    zone: string;
}

/**
 * Check if a given object implements the ZoneInformation interface.
 */
export function instanceOfZoneInformation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "quantity" in value;
    isInstance = isInstance && "zone" in value;

    return isInstance;
}

export function ZoneInformationFromJSON(json: any): ZoneInformation {
    return ZoneInformationFromJSONTyped(json, false);
}

export function ZoneInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZoneInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expDate': !exists(json, 'exp_date') ? undefined : json['exp_date'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'quantity': json['quantity'],
        'zone': json['zone'],
    };
}

export function ZoneInformationToJSON(value?: ZoneInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exp_date': value.expDate,
        'id': value.id,
        'quantity': value.quantity,
        'zone': value.zone,
    };
}

